### ISSUE TITLE
ERROR: test_creating_and_reading_multiple_sheets (pandas.io.tests.test_excel.ExcelReaderTests)

### ISSUE THREAD

**Issue by jlec** [pydata/pandas#10120]
======================================================================
ERROR: test_creating_and_reading_multiple_sheets (pandas.io.tests.test_excel.ExcelReaderTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/pandas-0.16.1/work/pandas-0.16.1-python3_3/lib/pandas/io/tests/test_excel.py", line 474, in test_creating_and_reading_multiple_sheets
    for sheetname, df in dfs.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/pandas-0.16.1/work/pandas-0.16.1-python3_3/lib/pandas/io/tests/test_excel.py", line 475, in test_creating_and_reading_multiple_sheets
    df.to_excel(ew,sheetname)
  File "/var/tmp/portage/dev-python/pandas-0.16.1/work/pandas-0.16.1-python3_3/lib/pandas/io/excel.py", line 619, in __exit__
    self.close()
  File "/var/tmp/portage/dev-python/pandas-0.16.1/work/pandas-0.16.1-python3_3/lib/pandas/io/excel.py", line 623, in close
    return self.save()
  File "/var/tmp/portage/dev-python/pandas-0.16.1/work/pandas-0.16.1-python3_3/lib/pandas/io/excel.py", line 651, in save
    return self.book.save(self.path)
  File "/usr/lib64/python3.3/site-packages/openpyxl/workbook/workbook.py", line 280, in save
    save_workbook(self, filename)
  File "/usr/lib64/python3.3/site-packages/openpyxl/writer/excel.py", line 211, in save_workbook
    writer.save(filename)
  File "/usr/lib64/python3.3/site-packages/openpyxl/writer/excel.py", line 194, in save
    self.write_data(archive)
  File "/usr/lib64/python3.3/site-packages/openpyxl/writer/excel.py", line 88, in write_data
    archive.writestr(ARC_WORKBOOK_RELS, write_workbook_rels(self.workbook))
  File "/usr/lib64/python3.3/site-packages/openpyxl/writer/workbook.py", line 316, in write_workbook_rels
    i += 1
UnboundLocalError: local variable 'i' referenced before assignment

**Comment by jreback** [comment]
pls show ``pd.show_versions()``

**Comment by jlec** [comment]
Happens with version 0.16.1 and HEAD.

pd.show_versions()

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.9.final.0
python-bits: 64
OS: Linux
OS-release: 4.0.2-lh
machine: x86_64
processor: Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz
byteorder: little
LC_ALL: None
LANG: en_GB.utf8

pandas: 0.16.0
nose: 1.3.6
Cython: 0.22
numpy: 1.8.2
scipy: 0.15.1
statsmodels: 0.6.1
IPython: 3.1.0
sphinx: 1.3.1
patsy: 0.3.0
dateutil: 2.4.2
pytz: 2015.2
bottleneck: 0.8.0
tables: 3.1.1
numexpr: 2.4.1
matplotlib: 1.4.3
openpyxl: 2.1.0
xlrd: 0.9.3
xlwt: 1.0.0
xlsxwriter: None
lxml: 3.4.3
bs4: 4.3.2
html5lib: 0.999
httplib2: 0.9.1
apiclient: None
sqlalchemy: None
pymysql: None
psycopg2: None

**Comment by jlec** [comment]
I see even more error using openpyxl-2.2.2

**Comment by jreback** [comment]
this looks like a problem with ``openpyxl`` itself. pls report there.

**Comment by Themanwithoutaplan** [comment]
FWIW this is really a problem with distutills. setup.py install is being run on a checkout and is disregarding the manifest. Python's packaging strikes again.

**Comment by jlec** [comment]
Please don't mix things up. It is run on the pypi hosted tarballs.

**Comment by Themanwithoutaplan** [comment]
The issue you're hitting with openpyxl is precisely because you're not using the tarball from PyPI but a checkout.

**Comment by jlec** [comment]
You are wrong,

here the results for 2.0.2, 2.1.0 and 2.2.2 from pypi:

======================================================================
ERROR: test_creating_and_reading_multiple_sheets (pandas.io.tests.test_excel.ExcelReaderTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/local/src/opensource/pandas/pandas/io/tests/test_excel.py", line 474, in test_creating_and_reading_multiple_sheets
    for sheetname, df in dfs.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/local/src/opensource/pandas/pandas/io/tests/test_excel.py", line 475, in test_creating_and_reading_multiple_sheets
    df.to_excel(ew,sheetname)
  File "/local/src/opensource/pandas/pandas/io/excel.py", line 619, in __exit__
    self.close()
  File "/local/src/opensource/pandas/pandas/io/excel.py", line 623, in close
    return self.save()
  File "/local/src/opensource/pandas/pandas/io/excel.py", line 651, in save
    return self.book.save(self.path)
  File "/usr/lib64/python3.4/site-packages/openpyxl/workbook/workbook.py", line 267, in save
    save_workbook(self, filename)
  File "/usr/lib64/python3.4/site-packages/openpyxl/writer/excel.py", line 185, in save_workbook
    writer.save(filename)
  File "/usr/lib64/python3.4/site-packages/openpyxl/writer/excel.py", line 168, in save
    self.write_data(archive)
  File "/usr/lib64/python3.4/site-packages/openpyxl/writer/excel.py", line 86, in write_data
    archive.writestr(ARC_WORKBOOK, write_workbook(self.workbook))
  File "/usr/lib64/python3.4/site-packages/openpyxl/writer/workbook.py", line 231, in write_workbook
    {'activeTab': '%d' % workbook.get_index(workbook.get_active_sheet()),
  File "/usr/lib64/python3.4/site-packages/openpyxl/workbook/workbook.py", line 131, in get_active_sheet
    return self.active
  File "/usr/lib64/python3.4/site-packages/openpyxl/workbook/workbook.py", line 136, in active
    return self.worksheets[self._active_sheet_index]
IndexError: list index out of range

======================================================================
ERROR: test_creating_and_reading_multiple_sheets (pandas.io.tests.test_excel.ExcelReaderTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/local/src/opensource/pandas/pandas/io/tests/test_excel.py", line 474, in test_creating_and_reading_multiple_sheets
    for sheetname, df in dfs.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/local/src/opensource/pandas/pandas/io/tests/test_excel.py", line 475, in test_creating_and_reading_multiple_sheets
    df.to_excel(ew,sheetname)
  File "/local/src/opensource/pandas/pandas/io/excel.py", line 619, in __exit__
    self.close()
  File "/local/src/opensource/pandas/pandas/io/excel.py", line 623, in close
    return self.save()
  File "/local/src/opensource/pandas/pandas/io/excel.py", line 651, in save
    return self.book.save(self.path)
  File "/usr/lib64/python3.4/site-packages/openpyxl/workbook/workbook.py", line 280, in save
    save_workbook(self, filename)
  File "/usr/lib64/python3.4/site-packages/openpyxl/writer/excel.py", line 211, in save_workbook
    writer.save(filename)
  File "/usr/lib64/python3.4/site-packages/openpyxl/writer/excel.py", line 194, in save
    self.write_data(archive)
  File "/usr/lib64/python3.4/site-packages/openpyxl/writer/excel.py", line 88, in write_data
    archive.writestr(ARC_WORKBOOK_RELS, write_workbook_rels(self.workbook))
  File "/usr/lib64/python3.4/site-packages/openpyxl/writer/workbook.py", line 316, in write_workbook_rels
    i += 1
UnboundLocalError: local variable 'i' referenced before assignment

======================================================================
ERROR: test_creating_and_reading_multiple_sheets (pandas.io.tests.test_excel.ExcelReaderTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/local/src/opensource/pandas/pandas/io/tests/test_excel.py", line 474, in test_creating_and_reading_multiple_sheets
    for sheetname, df in dfs.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/local/src/opensource/pandas/pandas/io/tests/test_excel.py", line 475, in test_creating_and_reading_multiple_sheets
    df.to_excel(ew,sheetname)
  File "/local/src/opensource/pandas/pandas/io/excel.py", line 619, in __exit__
    self.close()
  File "/local/src/opensource/pandas/pandas/io/excel.py", line 623, in close
    return self.save()
  File "/local/src/opensource/pandas/pandas/io/excel.py", line 651, in save
    return self.book.save(self.path)
  File "/usr/lib64/python3.4/site-packages/openpyxl/workbook/workbook.py", line 280, in save
    save_workbook(self, filename)
  File "/usr/lib64/python3.4/site-packages/openpyxl/writer/excel.py", line 211, in save_workbook
    writer.save(filename)
  File "/usr/lib64/python3.4/site-packages/openpyxl/writer/excel.py", line 194, in save
    self.write_data(archive)
  File "/usr/lib64/python3.4/site-packages/openpyxl/writer/excel.py", line 88, in write_data
    archive.writestr(ARC_WORKBOOK_RELS, write_workbook_rels(self.workbook))
  File "/usr/lib64/python3.4/site-packages/openpyxl/writer/workbook.py", line 316, in write_workbook_rels
    i += 1
UnboundLocalError: local variable 'i' referenced before assignment

**Comment by Themanwithoutaplan** [comment]
Needs openpyxl specific tests.
