### ISSUE TITLE
FAIL: test_sum (pandas.tests.test_series.TestSeries)

### ISSUE THREAD

**Issue by jlec** [pydata/pandas#10146]
======================================================================
FAIL: test_sum (pandas.tests.test_series.TestSeries)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/pandas-0.16.1/work/pandas-0.16.1-python3_3/lib/pandas/tests/test_series.py", line 2302, in test_sum
    self._check_stat_op('sum', np.sum)
  File "/var/tmp/portage/dev-python/pandas-0.16.1/work/pandas-0.16.1-python3_3/lib/pandas/tests/test_series.py", line 2666, in _check_stat_op
    testit()
  File "/var/tmp/portage/dev-python/pandas-0.16.1/work/pandas-0.16.1-python3_3/lib/pandas/tests/test_series.py", line 2639, in testit
    self.assertTrue(np.isnan(f(allna)))
AssertionError: False is not true

----------------------------------------------------------------------

INSTALLED VERSIONS
------------------
commit: None
python: 3.4.3.final.0
python-bits: 64
OS: Linux
OS-release: 4.0.2-lh-nvidia
machine: x86_64
processor: Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz
byteorder: little
LC_ALL: None
LANG: en_GB.utf8

pandas: 0.16.1
nose: 1.3.6
Cython: 0.22
numpy: 1.9.2
scipy: 0.15.1
statsmodels: None
IPython: 3.1.0
sphinx: 1.3.1
patsy: None
dateutil: 2.4.2
pytz: 2015.4
bottleneck: 1.0.0
tables: 3.1.1
numexpr: 2.4.1
matplotlib: 1.4.3
openpyxl: 2.2.2
xlrd: 0.9.3
xlwt: 1.0.0
xlsxwriter: None
lxml: 3.4.4
bs4: 4.3.2
html5lib: 0.999
httplib2: 0.9.1
apiclient: None
sqlalchemy: None
pymysql: 0.6.6.None
psycopg2: 2.6 (dt dec pq3 ext lo64)

**Comment by shoyer** [comment]
This is a dup of #9422... which we really should fix
