### ISSUE TITLE
0.16.1 No columns to parse from file 

### ISSUE THREAD

**Issue by shadow-identity** [pydata/pandas#10227]
I've updated Pandas from 0.14.1 (all was good) to 0.16.1 and now I have that exception:
```
Error
Traceback (most recent call last):
  File "/home/nedr/progs/MEA-FormBuilder/formbuilder_core/tests/test_reports.py", line 618, in test_no_reports
    response = self.request(request)
  File "/home/nedr/progs/MEA-FormBuilder/formbuilder_core/tests/test_common.py", line 56, in request
    HTTP_COOKIE={})
  File "/home/nedr/progs/env/mea-formbuilder/lib/python2.7/site-packages/django/test/client.py", line 479, in post
    secure=secure, **extra)
  File "/home/nedr/progs/env/mea-formbuilder/lib/python2.7/site-packages/django/test/client.py", line 294, in post
    secure=secure, **extra)
  File "/home/nedr/progs/env/mea-formbuilder/lib/python2.7/site-packages/django/test/client.py", line 355, in generic
    return self.request(**r)
  File "/home/nedr/progs/env/mea-formbuilder/lib/python2.7/site-packages/django/test/client.py", line 437, in request
    six.reraise(*exc_info)
  File "/home/nedr/progs/env/mea-formbuilder/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/nedr/progs/env/mea-formbuilder/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/nedr/progs/MEA-FormBuilder/formbuilder_core/views.py", line 160, in dispatch
    result = self.view(request)
  File "/home/nedr/progs/MEA-FormBuilder/formbuilder_core/views.py", line 236, in view
    return getattr(handler, action)(**args)
  File "/home/nedr/progs/MEA-FormBuilder/formbuilder_core/utils.py", line 74, in inner
    result = func(*args, **kwargs)
  File "/home/nedr/progs/MEA-FormBuilder/formbuilder_core/utils.py", line 102, in inner
    return func(*args, **kwargs)
  File "/home/nedr/progs/MEA-FormBuilder/formbuilder_core/utils.py", line 120, in inner
    return F(*args, **kwargs)
  File "/home/nedr/progs/MEA-FormBuilder/formbuilder_core/utils.py", line 902, in get_stat
    self._get_pandas_dataframe()
  File "/home/nedr/progs/MEA-FormBuilder/formbuilder_core/utils.py", line 881, in _get_pandas_dataframe
    self.data = pandas.read_csv(cStringIO.StringIO(self.report.body))
  File "/home/nedr/progs/env/mea-formbuilder/lib/python2.7/site-packages/pandas/io/parsers.py", line 474, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/nedr/progs/env/mea-formbuilder/lib/python2.7/site-packages/pandas/io/parsers.py", line 250, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/nedr/progs/env/mea-formbuilder/lib/python2.7/site-packages/pandas/io/parsers.py", line 566, in __init__
    self._make_engine(self.engine)
  File "/home/nedr/progs/env/mea-formbuilder/lib/python2.7/site-packages/pandas/io/parsers.py", line 705, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/nedr/progs/env/mea-formbuilder/lib/python2.7/site-packages/pandas/io/parsers.py", line 1072, in __init__
    self._reader = _parser.TextReader(src, **kwds)
  File "pandas/parser.pyx", line 512, in pandas.parser.TextReader.__cinit__ (pandas/parser.c:4814)
ValueError: No columns to parse from file
```

**Comment by jorisvandenbossche** [comment]
@shadow-identity You will have to provide some more details ..

E.g. provide some example data that reproduces the error. How does `cStringIO.StringIO(self.report.body)` look like?

**Comment by shadow-identity** [comment]
@jorisvandenbossche `self.report.body` is just a blank string (`''`)
`cStringIO.StringIO` returns file-like object from string
So exception raises only when file is blank. In other cases (`self.report.body` contains csv) all works fine. 
It is unexpected for me because with 0.14.1 exception not raises.

**Comment by jreback** [comment]
This raises in 0.14.1 as well. ``CParserError: Passed header=0 but only 0 lines in file``. So this is correct.

**Comment by shadow-identity** [comment]
@jorisvandenbossche I'm using this code:
```
        try:
            self.data = pandas.read_csv(cStringIO.StringIO(self.report.body))
        except CParserError as e:
            raise formbuilder_core.views.ValidationException('report', 'insufficient')
```
And I need to just install 0.14.1 back to disappear exception I've reported...

**Comment by jorisvandenbossche** [comment]
Ah, so it seems the exception type has changed from CParseError to ValueError. So you can probably catch both to have the code work for both pandas versions

**Comment by szeitlin** [comment]
Yeah I'm noticing something similar, but even more strange. If I try to read the file and it fails, once that exception is raised, I can't get it to work even with the correct parameters. However, if I independently read the file with the correct parameters, it does work. It's like it won't let go of the exception once it's raised (?). e.g. this works, so I know there's nothing wrong with my file:

`pd.read_csv('myfile.csv', header=4)`

but this doesn't work:


         try:
             one = pd.read_csv(csvfile)
         except CParserError as e:                          #it is catching the error
             two = pd.read_csv(csvfile, header=4)         #this fails


But it used to work with very similar code (in version 15.1):


            try:
               df = pd.read_csv(fullpath)
               print("successfully read file named " + filename)
           except pd.parser.CParserError as e:
               print("parser error, I'll try again")
               try:
                   df = pd.read_csv(fullpath, skiprows=4)
                   print("successfully read file named " + filename)
               except Exception as e:
                   raise FileTypeUnknownError
                   print(type(e))


(note that I also tried to catch it as a ValueError, but it still fails with "No columns to parse from file")
