### ISSUE TITLE
BUG: Cannot store complex valued Series/DataFrame/Panel/Panel4D as 'table' to hdf

### ISSUE THREAD

**Issue by bashtage** [pydata/pandas#10447]
Attempting to store a Panel4D of complext128 results in an error. This is true if I use table or fixed formats (different errors) [I am showing the last call from pandas as well as the actual error]

```python
pd.Panel4D(np.tile(np.array([1+1j,2+2j]),[2,2,2,1])).to_hdf('complex.h5','complex',format='t')

Traceback (most recent call last):
...
  File "/miniconda/envs/py34/lib/python3.4/site-packages/pandas/io/pytables.py", line 1930, in get_atom_data
    return self.get_atom_coltype(kind=kind)(shape=block.shape[0])
...
  File "/miniconda/envs/py34/lib/python3.4/site-packages/tables/atom.py", line 740, in __init__
    "to avoid confusions with PyTables 1.X complex atom names, "
TypeError: to avoid confusions with PyTables 1.X complex atom names, please use ``ComplexAtom(itemsize=N)``, where N=8 for single precision complex atoms, and N=16 for double precision complex atoms
```

```
INSTALLED VERSIONS
------------------
commit: None
python: 3.4.3.final.0
python-bits: 64
OS: Linux
OS-release: 2.6.32-504.16.2.el6.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

pandas: 0.16.2
nose: 1.3.7
Cython: 0.22
numpy: 1.9.2
scipy: None
statsmodels: None
IPython: 3.1.0
sphinx: None
patsy: 0.3.0
dateutil: 2.4.2
pytz: 2015.4
bottleneck: None
tables: 3.1.1
numexpr: 2.3.1
matplotlib: None
openpyxl: 2.0.2
xlrd: 0.9.3
xlwt: 1.0.0
xlsxwriter: 0.7.3
lxml: 3.4.4
bs4: 4.3.2
html5lib: 0.999
httplib2: None
apiclient: None
sqlalchemy: None
pymysql: None
psycopg2: None
```

If you try fixed, you get
```
TypeError: cannot properly create the storer for: [_STORER_MAP] [group->/complex (Group) '',value-><class 'pandas.core.panelnd.Panel4D'>,format->fixed,append->False,kwargs->{'encoding': None}]
```

**Comment by jreback** [comment]
>3d not supported in fixed at all (as pretty useless - u generally need/want to append to these)

complex is not supported very well in the exporters 
but of course fixes welcome

**Comment by bashtage** [comment]
Turns out this is true for all types, not just Panel4D
