### ISSUE TITLE
Can't get it to read a csv

### ISSUE THREAD

**Issue by nscaramuzzo** [pydata/pandas#10457]
Typed in 
pd.read_csv('Department_of_Recreation_and_Parks_Facility_and_Park_Information.csv')

and get this back: 
-bash: syntax error near unexpected token `'Department_of_Recreation_and_Parks__Facility_and_Park_Information.csv''

The file exists in the folder

**Comment by nscaramuzzo** [comment]
more info:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Nick_Muzzo/anaconda/envs/test.py/lib/python2.7/site-packages/pandas/io/parsers.py", line 474, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/Users/Nick_Muzzo/anaconda/envs/test.py/lib/python2.7/site-packages/pandas/io/parsers.py", line 250, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Users/Nick_Muzzo/anaconda/envs/test.py/lib/python2.7/site-packages/pandas/io/parsers.py", line 566, in __init__
    self._make_engine(self.engine)
  File "/Users/Nick_Muzzo/anaconda/envs/test.py/lib/python2.7/site-packages/pandas/io/parsers.py", line 705, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/Users/Nick_Muzzo/anaconda/envs/test.py/lib/python2.7/site-packages/pandas/io/parsers.py", line 1072, in __init__
    self._reader = _parser.TextReader(src, **kwds)
  File "pandas/parser.pyx", line 350, in pandas.parser.TextReader.__cinit__ (pandas/parser.c:3173)
  File "pandas/parser.pyx", line 594, in pandas.parser.TextReader._setup_parser_source (pandas/parser.c:5912)
IOError: File Department_of_Recreation_and_Parks_Facility_and_Park_Information.csv does not exist

**Comment by rockg** [comment]
I'm not sure it's clear what directory you are in.  Try providing the full path to your file when calling read_csv.

**Comment by nscaramuzzo** [comment]
Tried that and it still gives me the same traceback

**Comment by nscaramuzzo** [comment]
also it won't recognize this line: import matplotlib.pyplot as plt

**Comment by sinhrks** [comment]
Pls provide your directory structure, then try:

```
import os 
os.getcwd()
# your current working directory will be displayed
os.path.exists('Department_of_Recreation_and_Parks__Facility_and_Park_Information.csv')
# Must be True, otherwise it is unrelated to pandas
```

Not sure why you're caring ``matplotlib``. If you trying a script taken from somewhere, you can attach the link.

**Comment by nscaramuzzo** [comment]
/Nick_Muzzo/Downloads is where it lives. As for the matplotlib bit, it was what the script required.

**Comment by sinhrks** [comment]
The file tries is this CSV, correct?

- https://catalog.data.gov/dataset/department-of-recreation-and-parks-facility-and-park-information-e7cff

The CSV file is: ``'Department_of_Recreation_and_Parks__Facility_and_Park_Information.csv'``

And your error says: 

```
IOError: File Department_of_Recreation_and_Parks_Facility_and_Park_Information.csv does not exist
```

Maybe filename is incorrect? (2 underscores between "Parks" and "Facility")

**Comment by nscaramuzzo** [comment]
Oh God, really? SMH. Thanks

**Comment by sinhrks** [comment]
NP:)

**Comment by ajinkyasirsikar** [comment]
I am getting this error when i am trying to get to read the CSV file. Kindly help.


>>> import pandas as pd
>>> df= pd.read_csv('FBI-CRIME11.csv')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ajinkyasirsikar/anaconda/envs/py35/lib/python3.5/site-packages/pandas/io/parsers.py", line 491, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/Users/ajinkyasirsikar/anaconda/envs/py35/lib/python3.5/site-packages/pandas/io/parsers.py", line 268, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Users/ajinkyasirsikar/anaconda/envs/py35/lib/python3.5/site-packages/pandas/io/parsers.py", line 583, in __init__
    self._make_engine(self.engine)
  File "/Users/ajinkyasirsikar/anaconda/envs/py35/lib/python3.5/site-packages/pandas/io/parsers.py", line 724, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/Users/ajinkyasirsikar/anaconda/envs/py35/lib/python3.5/site-packages/pandas/io/parsers.py", line 1093, in __init__
    self._reader = _parser.TextReader(src, **kwds)
  File "pandas/parser.pyx", line 350, in pandas.parser.TextReader.__cinit__ (pandas/parser.c:3229)
  File "pandas/parser.pyx", line 583, in pandas.parser.TextReader._setup_parser_source (pandas/parser.c:6042)
OSError: File b'FBI-CRIME11.csv' does not exist

**Comment by rockg** [comment]
You need to provide the full path to the file not just the name.

**Comment by ajinkyasirsikar** [comment]
okay so instead of just mentioning 'FBI-CRIME11.csv' in "df= pd.read_csv('FBI-CRIME11.csv')" i have to mention the full path inside the quotes?

**Comment by rockg** [comment]
Yes...`df = pd.read_csv('/example/path/FBI-CRIME11.csv')`

**Comment by ajinkyasirsikar** [comment]
Wow awesome thanks a lot @rockg. it worked!!!

**Comment by varun97gopal** [comment]
Traceback (most recent call last):
  File "D:/competitions/image/funs.py", line 6, in <module>
    data=pd.read_csv("D:\competitions\image\train.csv")
  File "C:\Users\varun\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pandas\io\parsers.py", line 678, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\varun\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pandas\io\parsers.py", line 440, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\Users\varun\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pandas\io\parsers.py", line 787, in __init__
    self._make_engine(self.engine)
  File "C:\Users\varun\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pandas\io\parsers.py", line 1014, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "C:\Users\varun\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pandas\io\parsers.py", line 1708, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas\_libs\parsers.pyx", line 384, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas\_libs\parsers.pyx", line 695, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: File b'D:\\competitions\\image\train.csv' does not exist



i am too getting an error like this please me i think it is due to the pandas module what should i do?
