### ISSUE TITLE
test_concat_categorical fails on 32bit

### ISSUE THREAD

**Issue by yarikoptic** [pydata/pandas#10478]
```======================================================================
FAIL: test_concat_categorical (pandas.tests.test_categorical.TestCategoricalAsBlock)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/buildd/pandas-0.16.2+git58-g01995b2/debian/tmp/usr/lib/python2.7/dist-packages/pandas/tests/test_categorical.py", line 2985, in test_concat_categorical
    tm.assert_frame_equal(df_expected, df_concat)
  File "/tmp/buildd/pandas-0.16.2+git58-g01995b2/debian/tmp/usr/lib/python2.7/dist-packages/pandas/util/testing.py", line 746, in assert_frame_equal
    check_names=check_names)
  File "/tmp/buildd/pandas-0.16.2+git58-g01995b2/debian/tmp/usr/lib/python2.7/dist-packages/pandas/util/testing.py", line 675, in assert_series_equal
    assert_attr_equal('dtype', left, right)
  File "/tmp/buildd/pandas-0.16.2+git58-g01995b2/debian/tmp/usr/lib/python2.7/dist-packages/pandas/util/testing.py", line 552, in assert_attr_equal
    assert_equal(left_attr,right_attr,"attr is not equal [{0}]" .format(attr))
  File "/tmp/buildd/pandas-0.16.2+git58-g01995b2/debian/tmp/usr/lib/python2.7/dist-packages/pandas/util/testing.py", line 533, in assert_equal
    assert a == b, "%s: %r != %r" % (msg.format(a,b), a, b)
AssertionError: attr is not equal [dtype]: dtype('int64') != dtype('int32')

```
got while building 0.16.2+git58-g01995b2

**Comment by jreback** [comment]
closed by https://github.com/pydata/pandas/commit/054821dc90ded4263edf7c8d5b333c1d65ff53a4
