### ISSUE TITLE
DataFrame.to_hdf cannot pass file handle (buffer)

### ISSUE THREAD

**Issue by joshlk** [pydata/pandas#10491]
When writing a DataFrame to hdf format ('to_hdf' method) you cannot pass a file handle instead of a string. i.e. you can't:

```python
with open('test.hdf') as f:
    df.to_hdf(f, "df")
```

This raises an error:
```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "C:\Anaconda\lib\site-packages\pandas\core\generic.py", line 896, in to_hdf
    return pytables.to_hdf(path_or_buf, key, self, **kwargs)
  File "C:\Anaconda\lib\site-packages\pandas\io\pytables.py", line 286, in to_hdf
    f(path_or_buf)
  File "C:\Anaconda\lib\site-packages\pandas\io\pytables.py", line 279, in <lambda>
    f = lambda store: store.put(key, value, **kwargs)
AttributeError: 'file' object has no attribute 'put'
```

This is inconsistent with the 'to_csv' method where you can do this. In the docs it states that you can pass a file buffer to both 'to_hdf' and 'to_csv'.

**Comment by bashtage** [comment]
I think the current implementation in master `HDFStore` or a path.  I also think `HDFStore`s can be created with a generic buffer.

**Comment by jreback** [comment]
we have a tests for this and this would make a nice cookbook recipe.

you still need to give it a string path, but it wont' actually generate a file, see the docs [here](http://www.pytables.org/cookbook/inmemory_hdf5_files.html) for how to actually get the image (e.g. the bytes). I am not sure that you can write directly to a ``Bytes`` type of object, but if you use this method you can say send the bytes over the wire for reconstruction (though this is simpler with say ``msgpack`` support``)

```
store = HDFStore(path,mode='a',driver='H5FD_CORE',driver_core_backing_store=0)
store['df'] = df
store.append('df2',df)
store.close
```

**Comment by joshlk** [comment]
The doc string currently states:

> DataFrame.to_hdf(path_or_buf, key, **kwargs):
>         path_or_buf : the path (string) or buffer to put the store

Should it be changed so its more specific and says you should provide a HDFStore?

**Comment by jreback** [comment]
yes could change the arg names / doc-string to be more clear

**Comment by jreback** [comment]
@joshlk going to leave this one open if you (or someone!) wants to add a cookbook recipe for using in-memory stores

**Comment by yzard** [comment]
```store = HDFStore(path,mode='a',driver='H5FD_CORE',driver_core_backing_store=0)
store['df'] = df
store.append('df2',df)
store.close
`

**Comment by jbrockmendel** [comment]
Covered in cookbook L1346-1363, closing.
