### ISSUE TITLE
BUG: combine_first fails for empty Index and a MultiIndex

### ISSUE THREAD

**Issue by santegoeds** [pydata/pandas#10635]
Using `combine_first` on an empty frame with a single-column index fails if the other frame has a multi-index and is not empty.

This used to work for pandas version 0.14.1

```python
import pandas as pd

midx = pd.MultiIndex.from_arrays([[-1], [1]])

a = pd.DataFrame({'a': [1]}, index=midx)
print a

b = pd.DataFrame({'a': []})
print b

print b.combine_first(a)
```

```
$ python x.py 
      a
-1 1  1
Empty DataFrame
Columns: [a]
Index: []
Traceback (most recent call last):
  File "x.py", line 11, in <module>
    print b.combine_first(a)
  File "/users/is/ahlpypi/egg_cache/p/pandas-0.16.2_ahl1-py2.7-linux-x86_64.egg/pandas/core/frame.py", line 3388, in combine_first
    return self.combine(other, combiner, overwrite=False)
  File "/users/is/ahlpypi/egg_cache/p/pandas-0.16.2_ahl1-py2.7-linux-x86_64.egg/pandas/core/frame.py", line 3283, in combine
    this, other = self.align(other, copy=False)
  File "/users/is/ahlpypi/egg_cache/p/pandas-0.16.2_ahl1-py2.7-linux-x86_64.egg/pandas/core/generic.py", line 3374, in align
    fill_axis=fill_axis)
  File "/users/is/ahlpypi/egg_cache/p/pandas-0.16.2_ahl1-py2.7-linux-x86_64.egg/pandas/core/generic.py", line 3395, in _align_frame
    return_indexers=True)
  File "/users/is/ahlpypi/egg_cache/p/pandas-0.16.2_ahl1-py2.7-linux-x86_64.egg/pandas/core/index.py", line 2005, in join
    return self._join_multi(other, how=how, return_indexers=return_indexers)
  File "/users/is/ahlpypi/egg_cache/p/pandas-0.16.2_ahl1-py2.7-linux-x86_64.egg/pandas/core/index.py", line 2098, in _join_multi
    raise ValueError("cannot join with no level specified and no overlapping names")
ValueError: cannot join with no level specified and no overlapping names
```

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.3.final.0
python-bits: 64
OS: Linux
OS-release: 2.6.18-400.1.1.el5
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_GB

pandas: 0.16.2
nose: 1.3.0
Cython: 0.22
numpy: 1.9.2
scipy: 0.9.0
statsmodels: None
IPython: 3.2.0-1
sphinx: None
patsy: None
dateutil: 2.4.2
pytz: 2015.2
bottleneck: None
tables: 3.2.0
numexpr: 2.4.3
matplotlib: 1.3.1
openpyxl: None
xlrd: None
xlwt: 0.7.4
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
httplib2: $Rev$
apiclient: None
sqlalchemy: 0.9.4
pymysql: None
psycopg2: None

**Comment by jreback** [comment]
In 0.14.1 ``.align`` became more strict, so this raises that error. I am -0 on whether this should work silently, this is almost always an error that you are doing this in the first place. As a user I think that you would want to know that you have a completely different kind of index.

**Comment by santegoeds** [comment]
Thanks @jreback - I understand and it's not an issue for me if it remains unsupported.
