### ISSUE TITLE
incorrect quoting for windows building in conda?

### ISSUE THREAD

**Issue by ruidc** [pydata/pandas#10745]
trying to build master in clean windows x64 miniconda environment, gcc itself is in windows path:
```
writing build\temp.win-amd64-2.7\Release\pandas\index.def
C:\Program Files\mingw-builds\x64-4.8.1-posix-seh-rev5\mingw64\bin\dllwrap.exe -DMS_WIN64 -mdll -static --entry _DllMain@12 --output-lib build\temp.win-amd64-2.7\Release\pandas\libindex.a --def build\temp.win-amd64-2.7\Release\pandas\index.def -s build\temp.win-amd64-2.7\Release\pandas\index.o build\temp.win-amd64-2.7\Release\pandas\src\datetime\np_datetime.o build\temp.win-amd64-2.7\Release\pandas\src\datetime\np_datetime_strings.o -LC:\Miniconda\envs\pandas_dev\libs -LC:\Miniconda\envs\pandas_dev\PCbuild\amd64 -lpython27 -lmsvcr90 -o c:\Dev\src\pandas\pandas\index.pyd
'gcc" "-Wl' is not recognized as an internal or external command,
operable program or batch file.
dllwrap: gcc exited with status 1
error: command 'C:\\Program Files\\mingw-builds\\x64-4.8.1-posix-seh-rev5\\mingw64\\bin\\dllwrap.exe' failed with exit status 1
```

**Comment by jreback** [comment]
was just going to post some conda builds for you.

use ``conda build conda.recipe --no-test`` to build it (then ``conda install`` install the binary)

**Comment by jreback** [comment]
make sure you have ``libpython`` installed, see here: http://pandas.pydata.org/pandas-docs/stable/contributing.html#creating-a-development-environment

**Comment by ruidc** [comment]
thanks, having issues running it, should i raise with upstream?:

```
[pandas_dev] c:\Dev\src\pandas>conda build conda.recipe --no-test
Removing old build environment
Removing old work directory
BUILD START: pandas--nppy27_0
Fetching package metadata: ......
Solving package specifications: .
The following NEW packages will be INSTALLED:

    cython:     0.22.1-py27_0
    dateutil:   2.4.1-py27_0
    libpython:  1.0-py27_1
    mingw:      4.7-1
    numpy:      1.9.2-py27_0
    pip:        7.1.0-py27_0
    python:     2.7.10-0
    pytz:       2015.4-py27_0
    setuptools: 18.0.1-py27_0
    six:        1.9.0-py27_0

Linking packages ...
[      COMPLETE      ]|##################################################| 100%
Removing old work directory
Cloning into bare repository 'C:/Miniconda/conda-bld/git_cache/Dev_src_pandas'...
done.
checkout: u'f00e51cd4eb96537357b33932c9d78711ca4bdc9'
Cloning into 'C:\Miniconda\conda-bld\work'...
done.
Note: checking out 'f00e51cd4eb96537357b33932c9d78711ca4bdc9'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at f00e51c... Merge pull request #10743 from kawochen/TST-TestMsgpack-gen
==> git log -n1 <==

An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Miniconda\Scripts\conda-build-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Miniconda\lib\site-packages\conda_build\main_build.py", line 173, in main
    args_func(args, p)
  File "C:\Miniconda\lib\site-packages\conda_build\main_build.py", line 400, in args_func
    args.func(args, p)
  File "C:\Miniconda\lib\site-packages\conda_build\main_build.py", line 358, in execute
    channel_urls=channel_urls, override_channels=args.override_channels)
  File "C:\Miniconda\lib\site-packages\conda_build\build.py", line 354, in build
    source.provide(m.path, m.get_section('source'))
  File "C:\Miniconda\lib\site-packages\conda_build\source.py", line 253, in provide
    git_source(meta, recipe_dir)
  File "C:\Miniconda\lib\site-packages\conda_build\source.py", line 136, in git_source
    git_info()
  File "C:\Miniconda\lib\site-packages\conda_build\source.py", line 165, in git_info
    print(stdout + u'\n')
  File "C:\Miniconda\lib\encodings\cp850.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u20ac' in position 291: character maps to <undefined>
```

**Comment by ruidc** [comment]
and conda info:
```
[pandas_dev] c:\Dev\src\pandas>conda info
Current conda install:

             platform : win-64
        conda version : 3.15.1
  conda-build version : 1.16.0
       python version : 2.7.9.final.0
     requests version : 2.7.0
     root environment : C:\Miniconda  (writable)
  default environment : C:\Miniconda\envs\pandas_dev
     envs directories : C:\Miniconda\envs
        package cache : C:\Miniconda\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

**Comment by ruidc** [comment]
i was indeed following that,
```
[pandas_dev] c:\Dev\src\pandas>conda list
# packages in environment at C:\Miniconda\envs\pandas_dev:
#
cython                    0.22.1                   py27_0
jinja2                    2.8                      py27_0
libpython                 1.0                      py27_1
markupsafe                0.23                     py27_0
mingw                     4.7                           1
nose                      1.3.7                    py27_0
numpy                     1.9.2                    py27_0
pip                       7.1.0                    py27_0
python                    2.7.10                        0
python-dateutil           2.4.2                    py27_0
pytz                      2015.4                   py27_0
setuptools                18.0.1                   py27_0
six                       1.9.0                    py27_0
```

**Comment by jreback** [comment]
no, somehow unicode got committed in the log (from the last pr). going to fix. hold on a min.

**Comment by jreback** [comment]
I reverted then redid the offending commit. So you can give a try again (I will post some builds on binstar as well), my build process is not totally active yet (to make builds for all platforms on every commit).

also I do think this is an issue with the latest conda, very odd. You want to post a bug report to conda? thxs.

**Comment by jreback** [comment]
i put up the latest build, use the ``-c pandas`` to get it

```
[pandas] C:\Users\Jeff Reback\pandas>conda install pandas -c pandas --dry
Fetching package metadata: ......
Solving package specifications: .
Package plan for installation in environment C:\Miniconda\envs\pandas:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    pandas-v0.16.2             |       nppy27_286         5.1 MB

The following NEW packages will be INSTALLED:

    dateutil: 2.4.1-py27_0
    pandas:   v0.16.2-nppy27_286

Dry run: exiting
```

**Comment by ruidc** [comment]
refreshed and retried, am back to my original error above - have raised the issue upstream.

trying to use your new build:
```
[pandas_snap] c:\Dev\src\pandas>conda list
# packages in environment at C:\Miniconda\envs\pandas_snap:
#
cython                    0.22.1                   py27_0
dateutil                  2.4.1                    py27_0
ipython                   3.2.1                    py27_0
libpython                 1.0                      py27_1
mingw                     4.7                           1
nose                      1.3.7                    py27_0
numpy                     1.9.2                    py27_0
pandas                    v0.16.2              nppy27_286
pip                       7.1.0                    py27_0
pyreadline                2.0                      py27_0
python                    2.7.10                        0
python-dateutil           2.4.2                    py27_0
pytz                      2015.4                   py27_0
setuptools                18.0.1                   py27_0
six                       1.9.0                    py27_0
```

and now get this:

```
In [1]: import pandas
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-d6ac987968b6> in <module>()
----> 1 import pandas

c:\Dev\src\pandas\pandas\__init__.py in <module>()
     11                       "pandas from the source directory, you may need to run "
     12                       "'python setup.py build_ext --inplace' to build the C "
---> 13                       "extensions first.".format(module))
     14
     15 from datetime import datetime

ImportError: C extension: hashtable not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace' to build the C extensions first.
```

**Comment by jreback** [comment]
you can't be in the actual build directory

**Comment by ruidc** [comment]
ah, indeed, confirmed that https://github.com/pydata/pandas/issues/10732 is fixed with this build.
Now i need to distill the changes since 0.14.2 to consider backporting. Many thanks for the fix and support.

**Comment by jreback** [comment]
ok, gr8!
