### ISSUE TITLE
TST: testing issue on windows

### ISSUE THREAD

**Issue by jreback** [pydata/pandas#10822]
xref #7599 

@sinhrks 

This fails on windows (actually doesn't on a windows vm, you need an actual windows machine....weird)

```
======================================================================                                                                                        
ERROR: test_invalid_index_types (pandas.tseries.tests.test_frequencies.TestFrequencyInference)                                                                
----------------------------------------------------------------------                                                                                        
Traceback (most recent call last):                                                                                                                            
  File "c:\Users\Jeff Reback\Documents\GitHub\pandas\build\lib.win32-2.7\pandas\tseries\tests\test_frequencies.py", line 505, in test_invalid_index_types     
    self.assertRaises(ValueError, lambda : frequencies.infer_freq(i))                                                                                         
  File "c:\Users\Jeff Reback\Documents\GitHub\pandas\build\lib.win32-2.7\pandas\util\testing.py", line 1831, in assertRaises                                  
    _callable(*args, **kwargs)                                                                                                                                
  File "c:\Users\Jeff Reback\Documents\GitHub\pandas\build\lib.win32-2.7\pandas\tseries\tests\test_frequencies.py", line 505, in <lambda>                     
    self.assertRaises(ValueError, lambda : frequencies.infer_freq(i))                                                                                         
  File "c:\Users\Jeff Reback\Documents\GitHub\pandas\build\lib.win32-2.7\pandas\tseries\frequencies.py", line 813, in infer_freq                              
    index = pd.DatetimeIndex(index)                                                                                                                           
  File "c:\Users\Jeff Reback\Documents\GitHub\pandas\build\lib.win32-2.7\pandas\util\decorators.py", line 89, in wrapper                                      
    return func(*args, **kwargs)                                                                                                                              
  File "c:\Users\Jeff Reback\Documents\GitHub\pandas\build\lib.win32-2.7\pandas\tseries\index.py", line 302, in __new__                                       
    subarr = tools.to_datetime(data, box=False)                                                                                                               
  File "c:\Users\Jeff Reback\Documents\GitHub\pandas\build\lib.win32-2.7\pandas\util\decorators.py", line 89, in wrapper                                      
    return func(*args, **kwargs)                                                                                                                              
  File "c:\Users\Jeff Reback\Documents\GitHub\pandas\build\lib.win32-2.7\pandas\tseries\tools.py", line 267, in to_datetime                                   
    unit=unit, infer_datetime_format=infer_datetime_format)                                                                                                   
  File "c:\Users\Jeff Reback\Documents\GitHub\pandas\build\lib.win32-2.7\pandas\tseries\tools.py", line 376, in _to_datetime                                  
    return _convert_listlike(arg, box, format)                                                                                                                
  File "c:\Users\Jeff Reback\Documents\GitHub\pandas\build\lib.win32-2.7\pandas\tseries\tools.py", line 355, in _convert_listlike                             
    require_iso8601=require_iso8601)                                                                                                                          
  File "tslib.pyx", line 1809, in pandas.tslib.array_to_datetime (pandas\tslib.c:31227)                                                                       
  File "tslib.pyx", line 1995, in pandas.tslib.array_to_datetime (pandas\tslib.c:30864)                                                                       
  File "tslib.pyx", line 1989, in pandas.tslib.array_to_datetime (pandas\tslib.c:30754)                                                                       
  File "tslib.pyx", line 1596, in pandas.tslib.parse_datetime_string (pandas\tslib.c:24749)                                                                   
  File "C:\python27-32\lib\site-packages\python_dateutil-2.2-py2.7.egg\dateutil\parser.py", line 748, in parse                                                
    return DEFAULTPARSER.parse(timestr, **kwargs)                                                                                                             
  File "C:\python27-32\lib\site-packages\python_dateutil-2.2-py2.7.egg\dateutil\parser.py", line 310, in parse                                                
    res, skipped_tokens = self._parse(timestr, **kwargs)                                                                                                      
TypeError: 'NoneType' object is not iterable    
```

**Comment by jreback** [comment]
you can directly repro by doing this:

```
v = tm.makeUnicodeIndex(5).values
pd.DatetimeIndex(v)
```

**Comment by sinhrks** [comment]
Thanks, will check.

**Comment by jreback** [comment]
closed by https://github.com/pydata/pandas/commit/f30e42397aadfad3c3bbab5df735026e6ac3c212

@sinhrks though just skipping, so if you ever have a chance :)
