### ISSUE TITLE
Test failure: test_none_comparison

### ISSUE THREAD

**Issue by cel4** [pydata/pandas#10835]
`test_none_comparison` fails for me for all versions of `numpy>=1.9.0`. I don't see this issue in any `numpy-1.8.x`  version.

```
ERROR: test_none_comparison (pandas.tests.test_base.TestIndexOps)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ch/repo/pandas/.tox/py34/lib/python3.4/site-packages/pandas/tests/test_base.py", line 303, in test_none_comparison
    result = None != o
  File "/Users/ch/repo/pandas/.tox/py34/lib/python3.4/site-packages/pandas/core/generic.py", line 723, in __nonzero__
    .format(self.__class__.__name__))
ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
```

**Comment by jreback** [comment]
pls supply system details. I have seen this fail, but cannot repro.

**Comment by cel4** [comment]
```
INSTALLED VERSIONS
------------------
commit: None
python: 3.4.2.final.0
python-bits: 64
OS: Darwin
OS-release: 14.5.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: de_DE.UTF-8
LANG: de_DE.UTF-8

pandas: 0.16.2+340.ge4368de.dirty
nose: 1.3.7
Cython: 0.23
numpy: 1.9.2
scipy: None
statsmodels: None
IPython: None
sphinx: None
patsy: None
dateutil: 2.4.2
pytz: 2015.4
bottleneck: None
tables: None
numexpr: None
matplotlib: None
openpyxl: 1.8.6
xlrd: 0.9.4
xlwt: None
xlsxwriter: 0.7.3
lxml: 3.4.4
bs4: 4.4.0
html5lib: 0.999999
httplib2: None
apiclient: None
sqlalchemy: 1.0.8
pymysql: None
psycopg2: None
```

**Comment by kawochen** [comment]
Can you show your tox.ini?

**Comment by cel4** [comment]
```
# Tox (http://tox.testrun.org/) is a tool for running tests
# in multiple virtualenvs. This configuration file will run the
# test suite on all supported python versions. To use it, "pip install tox"
# and then run "tox" from this directory.

[tox]
envlist = py26, py27, py33, py34
#envlist = py27, py33, py34


[testenv]
deps =
    numpy
#    numpy==1.8.2
    cython
    nose
    pytz>=2011k
    python-dateutil
    beautifulsoup4
    lxml
    openpyxl<2.0.0
    xlsxwriter
    xlrd
    six
    sqlalchemy
    html5lib

# cd to anything but the default {toxinidir} which
# contains the pandas subdirectory and confuses
# nose away from the fresh install in site-packages
changedir = {envdir}

commands =
    # TODO:  --exe because of GH #761
    {envbindir}/nosetests --exe pandas {posargs:-A "not network and not disabled"}
    # cleanup the temp. build dir created by the tox build
#    /bin/rm -rf {toxinidir}/build

    # quietly rollback the install.
    # Note this line will only be reached if the
    # previous lines succeed (in particular, the tests),
    # but an uninstall is really only required when
    # files are removed from the source tree, in which case,
    # stale versions of files will will remain in the venv
    # until the next time uninstall is run.
    #
    # tox should provide a preinstall-commands hook.
    pip uninstall pandas -qy

[testenv:py26]
deps =
    boto
    bigquery
    {[testenv]deps}

[testenv:py27]
deps =
    boto
    bigquery
    {[testenv]deps}

[testenv:py33]
deps =
    {[testenv]deps}

[testenv:py34]
deps =
    {[testenv]deps}
```

**Comment by jreback** [comment]
This was failing *sometimes* on windows. https://github.com/pydata/pandas/commit/3bf4dc68b078b23203bc76a16076db89937f18b8

not really sure why, feel free to investigate
