### ISSUE TITLE
0.16.2: HTML docs fail to make, "TypeError: an integer is required (got type str)"

### ISSUE THREAD

**Issue by unsystemizer** [pydata/pandas#10831]
* `pip3 install --upgrade pandas` # installed 0.16.2
* Download 0.16.2 source, unzip, use `pip3` to install Sphinx (1.3.1, and dependencies such as sphinx-rtd-theme (0.1.8))
* run `make.py html` in `doc` folder

```
C:\Python34\pandas-0.16.2\doc>c:\Python34\python.exe make.py html
Traceback (most recent call last):
  File "C:\Python34\Scripts\sphinx-build-script.py", line 9, in <module>
    load_entry_point('Sphinx==1.3.1', 'console_scripts', 'sphinx-build')()
  File "C:\Python34\lib\site-packages\sphinx\__init__.py", line 51, in main
    sys.exit(build_main(argv))
  File "C:\Python34\lib\site-packages\sphinx\__init__.py", line 61, in build_main
    from sphinx import cmdline
  File "C:\Python34\lib\site-packages\sphinx\cmdline.py", line 23, in <module>
    from sphinx.application import Sphinx
  File "C:\Python34\lib\site-packages\sphinx\application.py", line 37, in <module>
    from sphinx.builders import BUILTIN_BUILDERS
  File "C:\Python34\lib\site-packages\sphinx\builders\__init__.py", line 23, in <module>
    from sphinx.util import i18n, path_stabilize
  File "C:\Python34\lib\site-packages\sphinx\util\i18n.py", line 15, in <module>
    from babel.messages.pofile import read_po
  File "C:\Python34\lib\site-packages\babel\messages\__init__.py", line 12, in <module>
    from babel.messages.catalog import *
  File "C:\Python34\lib\site-packages\babel\messages\catalog.py", line 23, in <module>
    from babel.dates import format_datetime
  File "C:\Python34\lib\site-packages\babel\dates.py", line 28, in <module>
    from babel.util import UTC, LOCALTZ
  File "C:\Python34\lib\site-packages\babel\util.py", line 278, in <module>
    from babel import localtime
  File "C:\Python34\lib\site-packages\babel\localtime\__init__.py", line 21, in <module>
    from babel.localtime._win32 import _get_localzone
  File "C:\Python34\lib\site-packages\babel\localtime\_win32.py", line 18, in <module>
    tz_names = get_global('windows_zone_mapping')
  File "C:\Python34\lib\site-packages\babel\core.py", line 58, in get_global
    _global_data = pickle.load(fileobj)
TypeError: an integer is required (got type str)
Building HTML failed.
```

**Comment by jorisvandenbossche** [comment]
The error message seems to deal with babel and i18n, which is for translated docs. Since pandas does not use this, this seems more an issue with your sphinx installation. 

Can you try with a small test project to see if this builds correctly? (see sphinx quickstart)

BTW, sphinx-rtd-theme is no dependency for the pandas docs

**Comment by unsystemizer** [comment]
sphinx-rtd-theme was installed automatically together with  sphinx (pip3 install sphinx).

I uninstalled Babel, and installed sphinx again:

```
C:\Windows\system32>c:\Python34\Scripts\pip.exe install sphinx
Downloading/unpacking sphinx
  Downloading Sphinx-1.3.1.tar.gz (3.5MB): 3.5MB downloaded
  Running setup.py egg_info for package sphinx

    warning: no files found matching 'TODO'
    no previously-included directories found matching 'doc\_build'
Requirement already satisfied (use --upgrade to upgrade): six>=1.4 in c:\python34\lib\site-packages (from sphinx)
Requirement already satisfied (use --upgrade to upgrade): Jinja2>=2.3 in c:\python34\lib\site-packages (from sphinx)
Requirement already satisfied (use --upgrade to upgrade): Pygments>=2.0 in c:\python34\lib\site-packages (from sphinx)
Requirement already satisfied (use --upgrade to upgrade): docutils>=0.11 in c:\python34\lib\site-packages (from sphinx)
Requirement already satisfied (use --upgrade to upgrade): snowballstemmer>=1.1 in c:\python34\lib\site-packages (from sphinx)
Downloading/unpacking babel>=1.3 (from sphinx)
  Downloading Babel-2.0.tar.gz (3.4MB):  21%  749kB
```

Then I was back to those Babel errors. Since this isn't a pandas problem, feel free to close this issue.
