### ISSUE TITLE
EuroSciPy 2015 Sprint: Problem installing pandas from source on a Mac OS X

### ISSUE THREAD

**Issue by springcoil** [pydata/pandas#10933]
I'm at the EuroSciPy 2015 sprint, I just found this issue when trying to update my Pandas development environment, I installed a fresh conda development environment and then got the following error. 
>>> import pandas as pd
Traceback (most recent call last):
  File "/Users/peadarcoyle/OpenSource/pandas/pandas/__init__.py", line 7, in <module>
    from pandas import hashtable, tslib, lib
ImportError: dlopen(/Users/peadarcoyle/OpenSource/pandas/pandas/hashtable.so, 2): Symbol not found: _PyCObject_Type
  Referenced from: /Users/peadarcoyle/OpenSource/pandas/pandas/hashtable.so
  Expected in: dynamic lookup

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/peadarcoyle/OpenSource/pandas/pandas/__init__.py", line 13, in <module>
    "extensions first.".format(module))
ImportError: C extension: dlopen(/Users/peadarcoyle/OpenSource/pandas/pandas/hashtable.so, 2): Symbol not found: _PyCObject_Type
  Referenced from: /Users/peadarcoyle/OpenSource/pandas/pandas/hashtable.so
  Expected in: dynamic lookup
 not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace' to build the C extensions first.

I tried running the same python setup.py build_ext --inplace command. 

My python version is Python 3.4.3 |Continuum Analytics, Inc.| (default, Mar  6 2015, 12:07:41)
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin

Has anyone seen an error like this before?

**Comment by springcoil** [comment]
Ok thanks to @jorisvandenbossche for helping me fix this. 
I used python setup.py build_ext --inplace -f to force a build and did a bit of rebasing to update my branch.

**Comment by IamGianluca** [comment]
I've encountered a similar issue. In my case the problem manifests only in PyCharm when I try to debug some code. I've already tried to force building the c dependencies using `python setup.py build_ext --inplace -f` but that didn't help.

The error I get is:

```
/Users/grossi/anaconda/envs/pandas_dev/bin/python3.4 "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py" --multiproc --qt-support --client 127.0.0.1 --port 62593 --file "/Applications/PyCharm CE.app/Contents/helpers/pycharm/noserunner.py" /Users/grossi/PycharmProjects/pandas-IamGianluca/pandas/tests/test_indexing.py
Testing started at 21:45 ...
Connected to pydev debugger (build 143.595)
pydev debugger: process 23639 is connecting








Error
Traceback (most recent call last):
  File "/Users/grossi/PycharmProjects/pandas-IamGianluca/pandas/__init__.py", line 7, in <module>
    from pandas import hashtable, tslib, lib
ImportError: dlopen(/Users/grossi/PycharmProjects/pandas-IamGianluca/pandas/hashtable.so, 2): Symbol not found: _PyCObject_Type
  Referenced from: /Users/grossi/PycharmProjects/pandas-IamGianluca/pandas/hashtable.so
  Expected in: dynamic lookup


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/grossi/anaconda/envs/pandas_dev/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/Users/grossi/anaconda/envs/pandas_dev/lib/python3.4/unittest/case.py", line 577, in run
    testMethod()
  File "/Users/grossi/anaconda/envs/pandas_dev/lib/python3.4/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/Users/grossi/anaconda/envs/pandas_dev/lib/python3.4/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/grossi/anaconda/envs/pandas_dev/lib/python3.4/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/grossi/anaconda/envs/pandas_dev/lib/python3.4/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/grossi/anaconda/envs/pandas_dev/lib/python3.4/imp.py", line 245, in load_module
    return load_package(name, filename)
  File "/Users/grossi/anaconda/envs/pandas_dev/lib/python3.4/imp.py", line 217, in load_package
    return methods.load()
  File "<frozen importlib._bootstrap>", line 1220, in load
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/Users/grossi/PycharmProjects/pandas-IamGianluca/pandas/__init__.py", line 13, in <module>
    "extensions first.".format(module))
ImportError: C extension: dlopen(/Users/grossi/PycharmProjects/pandas-IamGianluca/pandas/hashtable.so, 2): Symbol not found: _PyCObject_Type
  Referenced from: /Users/grossi/PycharmProjects/pandas-IamGianluca/pandas/hashtable.so
  Expected in: dynamic lookup
 not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace' to build the C extensions first.


E

======================================================================
ERROR: Failure: ImportError (C extension: dlopen(/Users/grossi/PycharmProjects/pandas-IamGianluca/pandas/hashtable.so, 2): Symbol not found: _PyCObject_Type
  Referenced from: /Users/grossi/PycharmProjects/pandas-IamGianluca/pandas/hashtable.so
  Expected in: dynamic lookup
 not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace' to build the C extensions first.)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/grossi/PycharmProjects/pandas-IamGianluca/pandas/__init__.py", line 7, in <module>
    from pandas import hashtable, tslib, lib
ImportError: dlopen(/Users/grossi/PycharmProjects/pandas-IamGianluca/pandas/hashtable.so, 2): Symbol not found: _PyCObject_Type
  Referenced from: /Users/grossi/PycharmProjects/pandas-IamGianluca/pandas/hashtable.so
  Expected in: dynamic lookup


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/grossi/anaconda/envs/pandas_dev/lib/python3.4/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/Users/grossi/anaconda/envs/pandas_dev/lib/python3.4/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/grossi/anaconda/envs/pandas_dev/lib/python3.4/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/grossi/anaconda/envs/pandas_dev/lib/python3.4/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/grossi/anaconda/envs/pandas_dev/lib/python3.4/imp.py", line 245, in load_module
    return load_package(name, filename)
  File "/Users/grossi/anaconda/envs/pandas_dev/lib/python3.4/imp.py", line 217, in load_package
    return methods.load()
  File "<frozen importlib._bootstrap>", line 1220, in load
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/Users/grossi/PycharmProjects/pandas-IamGianluca/pandas/__init__.py", line 13, in <module>
    "extensions first.".format(module))
ImportError: C extension: dlopen(/Users/grossi/PycharmProjects/pandas-IamGianluca/pandas/hashtable.so, 2): Symbol not found: _PyCObject_Type
  Referenced from: /Users/grossi/PycharmProjects/pandas-IamGianluca/pandas/hashtable.so
  Expected in: dynamic lookup
 not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace' to build the C extensions first.

----------------------------------------------------------------------
Ran 1 test in 0.006s

FAILED (errors=1)


Process finished with exit code 1

```
