### ISSUE TITLE
tseries and TestSeries test errors on Python 3.3 and OSX

### ISSUE THREAD

**Issue by matthew-brett** [pydata/pandas#11232]
Building and testing OSX wheels for 0.17.0, I am getting these errors on Python 3.3 (not 2.7 or 3.4 or 3.5):

```
======================================================================
FAIL: test_isin (pandas.tseries.tests.test_timedeltas.TestTimedeltaIndex)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/travis/build/MacPython/pandas-wheels/venv/lib/python3.3/site-packages/pandas/tseries/tests/test_timedeltas.py", line 1406, in test_isin
    self.assertTrue(result.all())
AssertionError: False is not true

======================================================================
FAIL: test_isin (pandas.tseries.tests.test_timeseries.TestDatetimeIndex)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/travis/build/MacPython/pandas-wheels/venv/lib/python3.3/site-packages/pandas/tseries/tests/test_timeseries.py", line 2923, in test_isin
    self.assertTrue(result.all())
AssertionError: False is not true

======================================================================
FAIL: test_isin_with_i8 (pandas.tests.test_series.TestSeries)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/travis/build/MacPython/pandas-wheels/venv/lib/python3.3/site-packages/pandas/tests/test_series.py", line 7268, in test_isin_with_i8
    assert_series_equal(result, expected)
  File "/Users/travis/build/MacPython/pandas-wheels/venv/lib/python3.3/site-packages/pandas/util/testing.py", line 925, in assert_series_equal
    check_less_precise, obj='{0}'.format(obj))
  File "pandas/src/testing.pyx", line 58, in pandas._testing.assert_almost_equal (pandas/src/testing.c:3809)
  File "pandas/src/testing.pyx", line 147, in pandas._testing.assert_almost_equal (pandas/src/testing.c:2685)
  File "/Users/travis/build/MacPython/pandas-wheels/venv/lib/python3.3/site-packages/pandas/util/testing.py", line 798, in raise_assert_detail
    raise AssertionError(msg)
AssertionError: Series are different

Series values are different (40.0 %)
[left]:  [False, False, False, False, False]
[right]: [True, True, False, False, False]
```

Full log at https://s3.amazonaws.com/archive.travis-ci.org/jobs/83497520/log.txt

I think I'm testing with the same parameters as the Linux test runs.  Am I missing something?

**Comment by jreback** [comment]
can you show ``pd.show_versions()`` on this setup. I cannot repro on py3.3 macosx.

**Comment by matthew-brett** [comment]
I just set a run going with `python -c 'import pandas; pandas.show_versions()'` added:

https://travis-ci.org/MacPython/pandas-wheels/jobs/83722994

Is it possible it's the numpy version?   Python 3.3 tests against 1.7.1, but 3.4 and 3.5 test against latest numpy (because of some other incompatibilities).

**Comment by matthew-brett** [comment]
I can reproduce on my local machine with numpy==1.7.1, no failures for numpy==1.8.1.

**Comment by jreback** [comment]
I found it
some really odd numpy / cython behavior with numpy 1.7.1
