### ISSUE TITLE
importing pandas will cause a file called "parser.py" in the CWD to be imported

### ISSUE THREAD

**Issue by reidmcy** [pydata/pandas#11251]
In python3 when I import pandas from the interactive session, if there is a file called `parser.py` in the current working directory the file is imported as part of the process. I am running Mac OS 10.10.5 with python 3.4.3 and using pandas 0.16.2 installed with homebrew.

pandas should not be importing random files when it is imported. The only reason I noticed this is that the file had a syntax error. If my `parser.py` had been doing file operations on import this could have causes serious harm.

My full version of pandas is
 \>>> pd.show_versions()

INSTALLED VERSIONS
------------------
commit: None
python: 3.4.3.final.0
python-bits: 64
OS: Darwin
OS-release: 14.5.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_CA.UTF-8

pandas: 0.16.2
nose: 1.3.6
Cython: None
numpy: 1.9.2
scipy: 0.15.1
statsmodels: None
IPython: 4.0.0
sphinx: 1.3.1
patsy: None
dateutil: 2.4.2
pytz: 2015.2
bottleneck: None
tables: None
numexpr: None
matplotlib: 1.4.3
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: 4.4.0
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: None
pymysql: None
psycopg2: None
>>> 

To see this I wrote a small file called `parser.py` and put it in \ ran python (with -v) then imported pandas. Below is a condesed part of the output.

   Reids-MBP:/ Reid$ echo "Print('You are in my parser.py')" > parser.py
   Reids-MBP:/ Reid$ echo "Fail here" >> parser.py
   Reids-MBP:/ Reid$ python3 -v
   ...
   \>>> import pandas
   ...
   '/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/xml/parsers/__pycache__/expat.cpython-34.pyc'
   # extension module loaded from '/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/lib-dynload/pyexpat.so'
   import 'xml.parsers.expat' # <_frozen_importlib.SourceFileLoader object at 0x10c1024e0>
   import 'plistlib' # <_frozen_importlib.SourceFileLoader object at 0x10be529b0>
   # destroy pkg_resources
   Traceback (most recent call last):
     File "<stdin>", line 1, in <module>
     File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
     File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
     File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
     File "<frozen importlib._bootstrap>", line 1129, in _exec
     File "<frozen importlib._bootstrap>", line 1471, in exec_module
     File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
     File "/usr/local/lib/python3.4/site-packages/pandas/__init__.py", line 7, in <module>
       from pandas import hashtable, tslib, lib
     File "<frozen importlib._bootstrap>", line 2284, in _handle_fromlist
     File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
     File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
     File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
     File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
     File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
     File "<frozen importlib._bootstrap>", line 539, in _check_name_wrapper
     File "<frozen importlib._bootstrap>", line 1715, in load_module
     File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
     File "pandas/tslib.pyx", line 50, in init pandas.tslib (pandas/tslib.c:73946)
     File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
     File "<frozen importlib._bootstrap>", line 2212, in _find_and_load_unlocked
     File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
     File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
     File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
     File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
     File "<frozen importlib._bootstrap>", line 1129, in _exec
     File "<frozen importlib._bootstrap>", line 1471, in exec_module
     File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
     File "/usr/local/lib/python3.4/site-packages/pytz/__init__.py", line 29, in <module>
       from pkg_resources import resource_stream
     File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
     File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
     File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
     File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
     File "/usr/local/lib/python3.4/site-packages/setuptools-15.2-py3.4.egg/pkg_resources/__init__.py", line 77, in <module>
     File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
     File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
     File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
     File "<frozen importlib._bootstrap>", line 1129, in _exec
     File "<frozen importlib._bootstrap>", line 1467, in exec_module
     File "<frozen importlib._bootstrap>", line 1572, in get_code
     File "<frozen importlib._bootstrap>", line 1532, in source_to_code
     File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
     File "/parser.py", line 2
       Fail here
               ^
   SyntaxError: invalid syntax
   \>>>

**Comment by jreback** [comment]
This is ``pkg_resources`` from the standard library importing. It imports its only internal parser module directly (and not from a namespace). your ``parser.py`` shadows this and hence hits the error. I would suggest raising this on the python list.

```
(py3.4)bash-3.2$ cat parser.py
Print('You are in my parser.py')
(py3.4)bash-3.2$ python
Python 3.4.3 |Continuum Analytics, Inc.| (default, Mar  6 2015, 12:07:41) 
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pkg_resources
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/Users/jreback/miniconda/envs/py3.4/lib/python3.4/site-packages/setuptools-18.3.2-py3.4.egg/pkg_resources/__init__.py", line 83, in <module>
  File "/Users/jreback/parser.py", line 1, in <module>
    Print('You are in my parser.py')
NameError: name 'Print' is not defined
```

**Comment by reidmcy** [comment]
Thank you for looking into this, I will.
