### ISSUE TITLE
read_csv not parsing numeric na_values against floats

### ISSUE THREAD

**Issue by jsegu** [pydata/pandas#11480]
On Pandas 0.17.0, `read_csv` fails with a `TypeError` when csv file contain floats and `na_values` contains numeric value(s). Consider this example:

```python
#!/usr/bin/env python2

import numpy as np
import pandas as pd
pd.show_versions()

# create a dataframe filled with integers 0 to 15
data = np.arange(16).reshape(4, 4)
df = pd.DataFrame(data, columns=list('ABCD'))

# save two csv files
df.to_csv('integers.csv')  # contains integers 0 to 15
(df/10).to_csv('floats.csv')  # contains floats 0.0 to 1.5

# this works
pd.read_csv('integers.csv', na_values='9999')

# this works
pd.read_csv('floats.csv', na_values='missing')

# this does not work
pd.read_csv('floats.csv', na_values='9999')
```

This raises the error below in my case:

```python
Traceback (most recent call last):
  File "./nabug.py", line 22, in <module>
    pd.read_csv('floats.csv', na_values='9999')
  File "/usr/lib/python2.7/site-packages/pandas/io/parsers.py", line 491, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/lib/python2.7/site-packages/pandas/io/parsers.py", line 278, in _read
    return parser.read()
  File "/usr/lib/python2.7/site-packages/pandas/io/parsers.py", line 740, in read
    ret = self._engine.read(nrows)
  File "/usr/lib/python2.7/site-packages/pandas/io/parsers.py", line 1187, in read
    data = self._reader.read(nrows)
  File "pandas/parser.pyx", line 766, in pandas.parser.TextReader.read (pandas/parser.c:8082)
  File "pandas/parser.pyx", line 788, in pandas.parser.TextReader._read_low_memory (pandas/parser.c:8338)
  File "pandas/parser.pyx", line 868, in pandas.parser.TextReader._read_rows (pandas/parser.c:9465)
  File "pandas/parser.pyx", line 975, in pandas.parser.TextReader._convert_column_data (pandas/parser.c:10858)
  File "pandas/parser.pyx", line 1035, in pandas.parser.TextReader._convert_tokens (pandas/parser.c:11744)
  File "pandas/parser.pyx", line 1085, in pandas.parser.TextReader._convert_with_dtype (pandas/parser.c:12634)
  File "pandas/parser.pyx", line 1499, in pandas.parser._try_double (pandas/parser.c:19996)
  File "pandas/parser.pyx", line 1818, in pandas.parser.kset_float64_from_list (pandas/parser.c:22852)
TypeError: 'set' object does not support indexing

```

Version information:

```python
INSTALLED VERSIONS
------------------
commit: None
python: 2.7.10.final.0
python-bits: 64
OS: Linux
OS-release: 4.1.11-1-MANJARO
machine: x86_64
processor: 
byteorder: little
LC_ALL: None
LANG: fr_CH.utf8

pandas: 0.17.0
nose: None
pip: None
setuptools: 18.4
Cython: None
numpy: 1.10.1
scipy: 0.16.0
statsmodels: None
IPython: 4.0.0
sphinx: None
patsy: None
dateutil: 2.4.2
pytz: 2015.6
blosc: None
bottleneck: None
tables: None
numexpr: None
matplotlib: 1.4.3
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
httplib2: 0.9.2
apiclient: None
sqlalchemy: None
pymysql: None
psycopg2: 2.6.1 (dt dec pq3 ext lo64)
```

I am otherwise just discovering this fantastic library (pandas). Thank you for the great work!

**Comment by jreback** [comment]
see #11374 

an incorrect .c file slipped in the 0.17.0 build that is building a new feature, and you hit the edge case. everything else is ok. this will be fixed in 0.17.1.
