### ISSUE TITLE
Empty preconstructed pandas results in error in Variable Explorer

### ISSUE THREAD

**Issue by Temmplar** [pydata/pandas#11490]
If I construct a DF like this:
iv_bd = pd.DataFrame(columns=['Jan','Feb','Mar'])

It causes an internal error instead of showing something like e.g. "empty Dataframe"

```
Spyder Internal Console

This console is used to report application
internal errors and to inspect Spyder
internals with the following commands:
  spy.app, spy.window, dir(spy)

Please don't use it to run your code

>>> /home/george/anaconda/lib/python2.7/site-packages/nbformat/current.py:19: UserWarning: nbformat.current is deprecated.

- use nbformat for read/write/validate public API
- use nbformat.vX directly to composing notebooks of a particular version

  """)
Traceback (most recent call last):
  File "/home/george/anaconda/lib/python2.7/site-packages/spyderlib/widgets/dicteditor.py", line 503, in createEditor
    if not editor.setup_and_check(value, title=key):
  File "/home/george/anaconda/lib/python2.7/site-packages/spyderlib/widgets/dataframeeditor.py", line 494, in setup_and_check
    self.dataModel = DataFrameModel(data, parent=self)
  File "/home/george/anaconda/lib/python2.7/site-packages/spyderlib/widgets/dataframeeditor.py", line 90, in __init__
    self.max_min_col_update()
  File "/home/george/anaconda/lib/python2.7/site-packages/spyderlib/widgets/dataframeeditor.py", line 124, in max_min_col_update
    mask = float_intran & (~ self.complex_intran)
  File "/home/george/anaconda/lib/python2.7/site-packages/pandas/core/generic.py", line 639, in __invert__
    arr = operator.inv(_values_from_object(self))
TypeError: ufunc 'invert' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
Traceback (most recent call last):
  File "/home/george/anaconda/lib/python2.7/site-packages/spyderlib/widgets/dicteditor.py", line 503, in createEditor
    if not editor.setup_and_check(value, title=key):
  File "/home/george/anaconda/lib/python2.7/site-packages/spyderlib/widgets/dataframeeditor.py", line 494, in setup_and_check
    self.dataModel = DataFrameModel(data, parent=self)
  File "/home/george/anaconda/lib/python2.7/site-packages/spyderlib/widgets/dataframeeditor.py", line 90, in __init__
    self.max_min_col_update()
  File "/home/george/anaconda/lib/python2.7/site-packages/spyderlib/widgets/dataframeeditor.py", line 124, in max_min_col_update
    mask = float_intran & (~ self.complex_intran)
  File "/home/george/anaconda/lib/python2.7/site-packages/pandas/core/generic.py", line 639, in __invert__
    arr = operator.inv(_values_from_object(self))
TypeError: ufunc 'invert' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
Traceback (most recent call last):
  File "/home/george/anaconda/lib/python2.7/site-packages/spyderlib/widgets/dicteditor.py", line 503, in createEditor
    if not editor.setup_and_check(value, title=key):
  File "/home/george/anaconda/lib/python2.7/site-packages/spyderlib/widgets/dataframeeditor.py", line 494, in setup_and_check
    self.dataModel = DataFrameModel(data, parent=self)
  File "/home/george/anaconda/lib/python2.7/site-packages/spyderlib/widgets/dataframeeditor.py", line 90, in __init__
    self.max_min_col_update()
  File "/home/george/anaconda/lib/python2.7/site-packages/spyderlib/widgets/dataframeeditor.py", line 124, in max_min_col_update
    mask = float_intran & (~ self.complex_intran)
  File "/home/george/anaconda/lib/python2.7/site-packages/pandas/core/generic.py", line 639, in __invert__
    arr = operator.inv(_values_from_object(self))
TypeError: ufunc 'invert' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
Traceback (most recent call last):
  File "/home/george/anaconda/lib/python2.7/site-packages/spyderlib/widgets/dicteditor.py", line 503, in createEditor
    if not editor.setup_and_check(value, title=key):
  File "/home/george/anaconda/lib/python2.7/site-packages/spyderlib/widgets/dataframeeditor.py", line 494, in setup_and_check
    self.dataModel = DataFrameModel(data, parent=self)
  File "/home/george/anaconda/lib/python2.7/site-packages/spyderlib/widgets/dataframeeditor.py", line 90, in __init__
    self.max_min_col_update()
  File "/home/george/anaconda/lib/python2.7/site-packages/spyderlib/widgets/dataframeeditor.py", line 124, in max_min_col_update
    mask = float_intran & (~ self.complex_intran)
  File "/home/george/anaconda/lib/python2.7/site-packages/pandas/core/generic.py", line 639, in __invert__
    arr = operator.inv(_values_from_object(self))
TypeError: ufunc 'invert' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

**Comment by jreback** [comment]
pls report to spyder

**Comment by Temmplar** [comment]
Oh sorry, mistake :)
