### ISSUE TITLE
pandas.tests.test_panel4d.TestPanel4d.test_sum fails in 0.17.0

### ISSUE THREAD

**Issue by neirbowj** [pydata/pandas#11495]
```
% nosetests -v pandas.tests.test_panel4d:TestPanel4d.test_sum
test_sum (pandas.tests.test_panel4d.TestPanel4d) ... FAIL

======================================================================
FAIL: test_sum (pandas.tests.test_panel4d.TestPanel4d)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pandas/tests/test_panel4d.py", line 49, in test_sum
    self._check_stat_op('sum', np.sum)
  File "/usr/local/lib/python2.7/site-packages/pandas/tests/test_panel4d.py", line 148, in _check_stat_op
    assert_panel_equal(result, obj.apply(skipna_wrapper, axis=i))
  File "/usr/local/lib/python2.7/site-packages/pandas/util/testing.py", line 1048, in assert_panelnd_equal
    assert_func(litem, ritem, check_less_precise=check_less_precise)
  File "/usr/local/lib/python2.7/site-packages/pandas/util/testing.py", line 1028, in assert_frame_equal
    obj='DataFrame.iloc[:, {0}]'.format(i))
  File "/usr/local/lib/python2.7/site-packages/pandas/util/testing.py", line 925, in assert_series_equal
    check_less_precise, obj='{0}'.format(obj))
  File "pandas/src/testing.pyx", line 58, in pandas._testing.assert_almost_equal (pandas/src/testing.c:3809)
  File "pandas/src/testing.pyx", line 147, in pandas._testing.assert_almost_equal (pandas/src/testing.c:2685)
  File "/usr/local/lib/python2.7/site-packages/pandas/util/testing.py", line 798, in raise_assert_detail
    raise AssertionError(msg)
AssertionError: DataFrame.iloc[:, 1] are different

DataFrame.iloc[:, 1] values are different (12.5 %)
[left]:  [0.0, 1.11252805895, -3.44337874224, 1.77230240341, -1.27472712412, -0.953662849233, -0.819950380871, 3.3111686889]
[right]: [nan, 1.11252805895, -3.44337874224, 1.77230240341, -1.27472712412, -0.953662849233, -0.819950380871, 3.3111686889]

----------------------------------------------------------------------
Ran 1 test in 0.169s

FAILED (failures=1)
```

```
$ python2.7 -m pandas.util.print_versions

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.10.final.0
python-bits: 64
OS: FreeBSD
OS-release: 10.1-STABLE
machine: amd64
processor: amd64
byteorder: little
LC_ALL: None
LANG: None

pandas: 0.17.0
nose: 1.3.7
pip: None
setuptools: 17.0
Cython: 0.23.4
numpy: 1.10.0
scipy: 0.16.0
statsmodels: None
IPython: 3.2.2
sphinx: None
patsy: None
dateutil: 2.3
pytz: 2015.7
blosc: None
bottleneck: 0.8.0
tables: 3.2.0
numexpr: 2.4.4
matplotlib: 1.4.3
openpyxl: 2.2.6
xlrd: 0.9.3
xlwt: 0.7.5
xlsxwriter: None
lxml: 3.4.1
bs4: 4.3.2
html5lib: 0.9999999
httplib2: None
apiclient: None
sqlalchemy: 0.7.10
pymysql: None
psycopg2: None
```

**Comment by jreback** [comment]
you are using a quite odd combination here. latest numpy (1.10), with quite old bottleneck (0.8.0). You would not normally do this (its hard to actually install this as you would have to install via source for everything).

And these have incompat ``np.nansum([np.nan])`` behavior. So pandas tests against the old behavior actually (which IMHO makes much more sense). Though allow the new behavior. Since you have an odd combination we are not supporting this in tests.

**Comment by neirbowj** [comment]
As for "you would have to install via source for everything", the current FreeBSD ports tree publishes [numpy 1.10.0](https://svnweb.freebsd.org/ports/head/math/py-numpy/Makefile?revision=400679) and [bottleneck 0.8.0](https://svnweb.freebsd.org/ports/head/math/py-bottleneck/Makefile?revision=400679), so users who install from the official repository of precompiled binary packages would get those versions, which is why I tested with that combination. I will work with the maintainer of the bottleneck port to update to a more modern version.
