### ISSUE TITLE
ValueError: unknown locale: UTF-8

### ISSUE THREAD

**Issue by datomnurdin** [pydata/pandas#11608]
I run the python script that contain Pandas (that one cause the problem) library I got this error:

    Traceback (most recent call last):
      File "test.py", line 2, in <module>
        import pandas
    ImportError: No module named pandas

But if I import from package path to make sure it detects Pandas library, I got this error message

    Traceback (most recent call last):
      File "test.py", line 3, in <module>
        import pandas
      File "/usr/local/lib/python2.7/site-packages/pandas/__init__.py", line 44, in <module>
        from pandas.core.api import *
      File "/usr/local/lib/python2.7/site-packages/pandas/core/api.py", line 9, in <module>
        from pandas.core.groupby import Grouper
      File "/usr/local/lib/python2.7/site-packages/pandas/core/groupby.py", line 16, in <module>
        from pandas.core.frame import DataFrame
      File "/usr/local/lib/python2.7/site-packages/pandas/core/frame.py", line 41, in <module>
        from pandas.core.series import Series
      File "/usr/local/lib/python2.7/site-packages/pandas/core/series.py", line 2864, in <module>
        import pandas.tools.plotting as _gfx
      File "/usr/local/lib/python2.7/site-packages/pandas/tools/plotting.py", line 28, in <module>
        import pandas.tseries.converter as conv
      File "/usr/local/lib/python2.7/site-packages/pandas/tseries/converter.py", line 7, in <module>
        import matplotlib.units as units
      File "/usr/local/lib/python2.7/site-packages/matplotlib/__init__.py", line 1131, in <module>
        rcParams = rc_params()
      File "/usr/local/lib/python2.7/site-packages/matplotlib/__init__.py", line 975, in rc_params
        return rc_params_from_file(fname, fail_on_error)
      File "/usr/local/lib/python2.7/site-packages/matplotlib/__init__.py", line 1100, in rc_params_from_file
        config_from_file = _rc_params_in_file(fname, fail_on_error)
      File "/usr/local/lib/python2.7/site-packages/matplotlib/__init__.py", line 1018, in _rc_params_in_file
        with _open_file_or_url(fname) as fd:
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
        return self.gen.next()
      File "/usr/local/lib/python2.7/site-packages/matplotlib/__init__.py", line 1000, in _open_file_or_url
        encoding = locale.getdefaultlocale()[1]
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 543, in getdefaultlocale
        return _parse_localename(localename)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 475, in _parse_localename
        raise ValueError, 'unknown locale: %s' % localename
    ValueError: unknown locale: UTF-8

I already update my `.bash_profile` and `.bashrc` with these lines but still not working even I already restart the terminal and my machine.

    export LANG="it_IT.UTF-8"  
    export LC_COLLATE="it_IT.UTF-8"  
    export LC_CTYPE="it_IT.UTF-8"  
    export LC_MESSAGES="it_IT.UTF-8"  
    export LC_MONETARY="it_IT.UTF-8"  
    export LC_NUMERIC="it_IT.UTF-8"  
    export LC_TIME="it_IT.UTF-8"  
    export LC_ALL="it_IT.UTF-8"

I'm also enabled `Set locale environment variables on startup` in the terminal preferences. 

[![enter image description here][1]][1]

I'm afraid the problem cause because of EI Capitan. Please advice. Thank you.

  [1]: http://i.stack.imgur.com/Yfo9e.png

**Comment by jreback** [comment]
you have some path issues. pls see the [installation docs](http://pandas.pydata.org/pandas-docs/stable/install.html)
