### ISSUE TITLE
read_csv: CparserError being ignored instead of raising an error

### ISSUE THREAD

**Issue by sandbox** [pydata/pandas#11654]
I'm having trouble with an install of pandas 0.17.0 not raising errors CParserErrors when encountering a badly formatted csv.

```
>>> import pandas as pd
>>> import StringIO
>>> dataframe = pd.read_csv(StringIO.StringIO('group,"this\nreally,error\ni,hope\n'), sep=',', header=None, skiprows=0, nrows=None, index_col=False, skipinitialspace=True)
Exception pandas.parser.CParserError: CParserError('Error tokenizing data. C error: EOF inside string starting at line 0',) in 'pandas.parser.TextReader._tokenize_rows' ignored
>>> dataframe
Empty DataFrame
Columns: [0]
Index: []
```

I'd expect an error to be raised instead of returning an empty Dataframe, an error like:
```
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/venv/lib/python2.7/site-packages/pandas/io/parsers.py", line 491, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/venv/lib/python2.7/site-packages/pandas/io/parsers.py", line 268, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/venv/lib/python2.7/site-packages/pandas/io/parsers.py", line 583, in __init__
    self._make_engine(self.engine)
  File "/venv/lib/python2.7/site-packages/pandas/io/parsers.py", line 724, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/venv/lib/python2.7/site-packages/pandas/io/parsers.py", line 1093, in __init__
    self._reader = _parser.TextReader(src, **kwds)
  File "pandas/parser.pyx", line 509, in pandas.parser.TextReader.__cinit__ (pandas/parser.c:4897)
  File "pandas/parser.pyx", line 709, in pandas.parser.TextReader._get_header (pandas/parser.c:7427)
  File "pandas/parser.pyx", line 820, in pandas.parser.TextReader._tokenize_rows (pandas/parser.c:8736)
  File "pandas/parser.pyx", line 1732, in pandas.parser.raise_parser_error (pandas/parser.c:22105)
pandas.parser.CParserError: Error tokenizing data. C error: EOF inside string starting at line 0
```

I installed pandas via pip 7.1.2 in a virtualenv and other environment information for the test that fails is:
```
Ubuntu 14.04.1 LTS (GNU/Linux 3.13.0-44-generic x86_64)
$ uname -a
Linux 3.13.0-44-generic #73-Ubuntu SMP Tue Dec 16 00:22:43 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
$ python
Python 2.7.10 (default, Nov 19 2015, 23:31:54)
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas as pd
>>> pd.show_versions()

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.10.final.0
python-bits: 64
OS: Linux
OS-release: 3.13.0-44-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

pandas: 0.17.0
nose: 1.3.4
pip: 7.1.2
setuptools: 18.2
Cython: 0.23.4
numpy: 1.10.1
scipy: 0.16.1
statsmodels: 0.6.1
IPython: None
sphinx: None
patsy: 0.3.0
dateutil: 2.2
pytz: 2014.7
blosc: None
bottleneck: 1.0.0
tables: None
numexpr: 2.4.6
matplotlib: None
openpyxl: 2.1.0
xlrd: 0.9.3
xlwt: 0.7.5
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 0.8.0
pymysql: None
psycopg2: 2.5.4 (dt dec pq3 ext)
```

Is there something I'm doing wrong or not setting up in the environment correctly?  Also is this the appropriate place to ask this question? Thanks for any help!

**Comment by jreback** [comment]
This raises on 0.17.0 (and master).

Not sure what the issue is.
```
In [1]: pd.read_csv(StringIO('group,"this\nreally,error\ni,hope\n'), sep=',', header=None, skiprows=0, nrows=None, index_col=False, skipinitialspace=True)
CParserError: Error tokenizing data. C error: EOF inside string starting at line 0
```

**Comment by sandbox** [comment]
Thanks for the response, I am able to get it to work on a different machine, and I think it has something to do with some compilation somewhere, maybe with Cython ignoring error returns http://docs.cython.org/src/userguide/language_basics.html#error-return-values 

But I can't tell exactly what part of the environments being different is causing the issue. One machine is a mac, the other a linux instance on AWS so there is a lot to go through

**Comment by jreback** [comment]
their was a incorrectly distributed c file for the parser for 0.17.0 - it had some newer features

so it's possible that made this fail

0.17.1 coming out tomorrow

so give that a try

pls reopen if still an issue

**Comment by sandbox** [comment]
Okay thanks that helps! I'll give that a try when 0.17.1 is released tomorrow

**Comment by sandbox** [comment]
Just test with 0.17.1 and it now works!

**Comment by jreback** [comment]
gr8

bug fixing at its best!
