### ISSUE TITLE
Can't get it to read a csv

### ISSUE THREAD

**Issue by ajinkyasirsikar** [pydata/pandas#11676]
I am getting this error. Kindly help.
>>> import pandas as pd
>>> df= pd.read_csv('FBI-CRIME11.csv')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ajinkyasirsikar/anaconda/envs/py35/lib/python3.5/site-packages/pandas/io/parsers.py", line 491, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/Users/ajinkyasirsikar/anaconda/envs/py35/lib/python3.5/site-packages/pandas/io/parsers.py", line 268, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Users/ajinkyasirsikar/anaconda/envs/py35/lib/python3.5/site-packages/pandas/io/parsers.py", line 583, in __init__
    self._make_engine(self.engine)
  File "/Users/ajinkyasirsikar/anaconda/envs/py35/lib/python3.5/site-packages/pandas/io/parsers.py", line 724, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/Users/ajinkyasirsikar/anaconda/envs/py35/lib/python3.5/site-packages/pandas/io/parsers.py", line 1093, in __init__
    self._reader = _parser.TextReader(src, **kwds)
  File "pandas/parser.pyx", line 350, in pandas.parser.TextReader.__cinit__ (pandas/parser.c:3229)
  File "pandas/parser.pyx", line 583, in pandas.parser.TextReader._setup_parser_source (pandas/parser.c:6042)
OSError: File b'FBI-CRIME11.csv' does not exist

**Comment by jreback** [comment]
the error says it all
your file is not in the current directory

**Comment by ajinkyasirsikar** [comment]
I am beginner. Can you please guide me through it.

**Comment by jreback** [comment]
just google for it

http://stackoverflow.com/questions/23572520/cant-read-open-or-do-anything-with-a-csv-file-python-3-4-windows

**Comment by ajinkyasirsikar** [comment]
Okay i will look for it. Thanks
