### ISSUE TITLE
Error 'unknown locale: UTF-8' on import (Mac OS X)

### ISSUE THREAD

**Issue by clstaudt** [pydata/pandas#11694]
I've recently upgraded to Python 3.5 and the newest version of pandas `pandas (0.17.1)`, but this broke the package for me. I'm on Mac OS X 10.9.5. What can I do?

    cls@clsmba ~> python3
    Python 3.5.0 (default, Sep 23 2015, 04:41:33) 
    [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import pandas
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/local/lib/python3.5/site-packages/pandas/__init__.py", line 44, in <module>
        from pandas.core.api import *
      File "/usr/local/lib/python3.5/site-packages/pandas/core/api.py", line 9, in <module>
        from pandas.core.groupby import Grouper
      File "/usr/local/lib/python3.5/site-packages/pandas/core/groupby.py", line 17, in <module>
        from pandas.core.frame import DataFrame
      File "/usr/local/lib/python3.5/site-packages/pandas/core/frame.py", line 41, in <module>
        from pandas.core.series import Series
      File "/usr/local/lib/python3.5/site-packages/pandas/core/series.py", line 2909, in <module>
        import pandas.tools.plotting as _gfx
      File "/usr/local/lib/python3.5/site-packages/pandas/tools/plotting.py", line 28, in <module>
        import pandas.tseries.converter as conv
      File "/usr/local/lib/python3.5/site-packages/pandas/tseries/converter.py", line 7, in <module>
        import matplotlib.units as units
      File "/usr/local/lib/python3.5/site-packages/matplotlib/__init__.py", line 1131, in <module>
        rcParams = rc_params()
      File "/usr/local/lib/python3.5/site-packages/matplotlib/__init__.py", line 975, in rc_params
        return rc_params_from_file(fname, fail_on_error)
      File "/usr/local/lib/python3.5/site-packages/matplotlib/__init__.py", line 1100, in rc_params_from_file
        config_from_file = _rc_params_in_file(fname, fail_on_error)
      File "/usr/local/lib/python3.5/site-packages/matplotlib/__init__.py", line 1018, in _rc_params_in_file
        with _open_file_or_url(fname) as fd:
      File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/contextlib.py", line 59, in __enter__
        return next(self.gen)
      File "/usr/local/lib/python3.5/site-packages/matplotlib/__init__.py", line 1000, in _open_file_or_url
        encoding = locale.getdefaultlocale()[1]
      File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/locale.py", line 559, in getdefaultlocale
        return _parse_localename(localename)
      File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/locale.py", line 487, in _parse_localename
        raise ValueError('unknown locale: %s' % localename)
    ValueError: unknown locale: UTF-8

**Comment by clstaudt** [comment]
This can be solved by setting shell variables, e.g. for fish shell:
set -x LC_ALL en_US.UTF-8 
set -x LANG en_US.UTF-8
May or may not be an issue of pandas.

**Comment by jreback** [comment]
you can also set this env variable

```
PYTHONIOENCODING=UTF-8
```

I don't think this a pandas, *maybe* its a matplotlib issue, cc @tacaswel

**Comment by tacaswell** [comment]
This is an apple-does-not-feel-compelled-to-play-by-the-rules issue.  Their default locale setting is not a valid locale name.

You should be able to trigger this on a mac by just doing

```python
import locale
locale.getdefaultlocale()
```
