### ISSUE TITLE
Timestamp subtraction of NaT with timezones

### ISSUE THREAD

**Issue by kdebrab** [pydata/pandas#11718]
In pandas 0.17.1, a TypeError is returned when trying to subtract a timezone-aware timestamp from a NaT timestamp:
```python
In [1]: import pandas as pd

In [2]: pd.Timestamp(None, tz='utc') - pd.Timestamp('now', tz='utc')
Traceback (most recent call last):

  File "<ipython-input-2-5e0738cec5fa>", line 1, in <module>
    pd.Timestamp(None, tz='utc') - pd.Timestamp('now', tz='utc')

  File "pandas\tslib.pyx", line 1099, in pandas.tslib._NaT.__sub__ (pandas\tslib.c:21618)

  File "pandas\tslib.pyx", line 1026, in pandas.tslib._Timestamp.__sub__ (pandas\tslib.c:20036)

TypeError: Timestamp subtraction must have the same timezones or no timezones
```
Subtracting a timezone unaware timestamp from a NaT timestamp is no problem. Also subtracting a NaT from a timezone aware timestamp works:
```python
In [3]: pd.Timestamp(None) - pd.Timestamp('now')
Out[3]: NaT

In [4]: pd.Timestamp('now', tz='utc') - pd.Timestamp(None, tz='utc')
Out[4]: NaT

In [5]: pd.Timestamp('now', tz='utc') - pd.Timestamp(None)
Out[5]: NaT
```

**Comment by sinhrks** [comment]
Thanks for the report. There seems to be several problems related to this. PR is appreciated!

```
# OK
pd.Timestamp('2011-01-01', tz='UTC') - pd.NaT
# NaT  
pd.DatetimeIndex(['2011-01-01'], tz='UTC') - pd.NaT
# TypeError: Timestamp subtraction must have the same timezones or no timezones

pd.NaT - pd.Timestamp('2011-01-01', tz='UTC')
# TypeError: Timestamp subtraction must have the same timezones or no timezones

pd.NaT - pd.DatetimeIndex(['2011-01-01'], tz='UTC')
# TypeError: Timestamp subtraction must have the same timezones or no timezones

# NG
pd.DatetimeIndex(['2011-01-01']) - pd.NaT
# TimedeltaIndex(['-91777 days +00:12:43.145224'], dtype='timedelta64[ns]', freq=None)

# OK
pd.NaT - pd.DatetimeIndex(['2011-01-01'])
# NaT

# OK
pd.NaT - pd.Timestamp('2011-01-01')
# NaT

# OK
pd.Timestamp('2011-01-01') - pd.NaT
# NaT
```

**Comment by jreback** [comment]
iirc there is an issue open about this - we need to have arithmetic methods on the  NaT scalar itself

**Comment by jreback** [comment]
some of this is being addressed by #11564

**Comment by jreback** [comment]
@sinhrks / @kawochen 

can you update this and see what we have left (e.g. that #11564) didn't already cover

**Comment by sinhrks** [comment]
Looks no changes from the output attached above. I'll take a look.
