### ISSUE TITLE
0.17.1 test_timestamp_compare and few others failures on arm64 (and possibly others)

### ISSUE THREAD

**Issue by yarikoptic** [pydata/pandas#11795]
https://buildd.debian.org/status/fetch.php?pkg=pandas&arch=arm64&ver=0.17.1-2&stamp=1449515678
so this one is not even big endian afaik
```
ERROR: test_timestamp_compare (pandas.tests.test_frame.TestDataFrame)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/«PKGBUILDDIR»/debian/tmp/usr/lib/python2.7/dist-packages/pandas/tests/test_frame.py", line 5749, in test_timestamp_compare
    expected = left_f(df, Timestamp('20010109'))
  File "/«PKGBUILDDIR»/debian/tmp/usr/lib/python2.7/dist-packages/pandas/core/ops.py", line 1116, in f
    return res.fillna(True).astype(bool)
  File "/«PKGBUILDDIR»/debian/tmp/usr/lib/python2.7/dist-packages/pandas/core/generic.py", line 2632, in astype
    dtype=dtype, copy=copy, raise_on_error=raise_on_error, **kwargs)
  File "/«PKGBUILDDIR»/debian/tmp/usr/lib/python2.7/dist-packages/pandas/core/internals.py", line 2864, in astype
    return self.apply('astype', dtype=dtype, **kwargs)
  File "/«PKGBUILDDIR»/debian/tmp/usr/lib/python2.7/dist-packages/pandas/core/internals.py", line 2823, in apply
    applied = getattr(b, f)(**kwargs)
  File "/«PKGBUILDDIR»/debian/tmp/usr/lib/python2.7/dist-packages/pandas/core/internals.py", line 430, in astype
    values=values, **kwargs)
  File "/«PKGBUILDDIR»/debian/tmp/usr/lib/python2.7/dist-packages/pandas/core/internals.py", line 2001, in _astype
    return super(DatetimeBlock, self)._astype(dtype=dtype, **kwargs)
  File "/«PKGBUILDDIR»/debian/tmp/usr/lib/python2.7/dist-packages/pandas/core/internals.py", line 472, in _astype
    values = com._astype_nansafe(values.ravel(), dtype, copy=True)
  File "/«PKGBUILDDIR»/debian/tmp/usr/lib/python2.7/dist-packages/pandas/core/common.py", line 2433, in _astype_nansafe
    (arr.dtype, dtype))
TypeError: cannot astype a datetimelike from [datetime64[ns]] to [bool]

======================================================================
FAIL: test_NaT_cast (pandas.tseries.tests.test_timeseries.TestSeriesDatetime64)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/«PKGBUILDDIR»/debian/tmp/usr/lib/python2.7/dist-packages/pandas/tseries/tests/test_timeseries.py", line 3516, in test_NaT_cast
    assert_series_equal(result, expected)
  File "/«PKGBUILDDIR»/debian/tmp/usr/lib/python2.7/dist-packages/pandas/util/testing.py", line 946, in assert_series_equal
    check_less_precise, obj='{0}'.format(obj))
  File "pandas/src/testing.pyx", line 58, in pandas._testing.assert_almost_equal (pandas/src/testing.c:3809)
  File "pandas/src/testing.pyx", line 147, in pandas._testing.assert_almost_equal (pandas/src/testing.c:2685)
  File "/«PKGBUILDDIR»/debian/tmp/usr/lib/python2.7/dist-packages/pandas/util/testing.py", line 819, in raise_assert_detail
    raise AssertionError(msg)
AssertionError: Series are different

Series values are different (100.0 %)
[left]:  [1970-01-01T00:00:00.000000000+0000]
[right]: [NaT]

======================================================================
FAIL: test_where_datetime (pandas.tests.test_series.TestSeries)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/«PKGBUILDDIR»/debian/tmp/usr/lib/python2.7/dist-packages/pandas/tests/test_series.py", line 2191, in test_where_datetime
    assert_series_equal(rs, expected)
  File "/«PKGBUILDDIR»/debian/tmp/usr/lib/python2.7/dist-packages/pandas/util/testing.py", line 946, in assert_series_equal
    check_less_precise, obj='{0}'.format(obj))
  File "pandas/src/testing.pyx", line 58, in pandas._testing.assert_almost_equal (pandas/src/testing.c:3809)
  File "pandas/src/testing.pyx", line 147, in pandas._testing.assert_almost_equal (pandas/src/testing.c:2685)
  File "/«PKGBUILDDIR»/debian/tmp/usr/lib/python2.7/dist-packages/pandas/util/testing.py", line 819, in raise_assert_detail
    raise AssertionError(msg)
AssertionError: Series are different

Series values are different (50.0 %)
[left]:  [1970-01-01T00:00:00.000000010+0000, 1970-01-01T00:00:00.000000000+0000]
[right]: [1970-01-01T00:00:00.000000010+0000, NaT]

======================================================================
FAIL: test_where_timedelta (pandas.tests.test_series.TestSeries)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/«PKGBUILDDIR»/debian/tmp/usr/lib/python2.7/dist-packages/pandas/tests/test_series.py", line 2212, in test_where_timedelta
    assert_series_equal(rs, expected)
  File "/«PKGBUILDDIR»/debian/tmp/usr/lib/python2.7/dist-packages/pandas/util/testing.py", line 946, in assert_series_equal
    check_less_precise, obj='{0}'.format(obj))
  File "pandas/src/testing.pyx", line 58, in pandas._testing.assert_almost_equal (pandas/src/testing.c:3809)
  File "pandas/src/testing.pyx", line 147, in pandas._testing.assert_almost_equal (pandas/src/testing.c:2685)
  File "/«PKGBUILDDIR»/debian/tmp/usr/lib/python2.7/dist-packages/pandas/util/testing.py", line 819, in raise_assert_detail
    raise AssertionError(msg)
AssertionError: Series are different

Series values are different (50.0 %)
[left]:  [10 nanoseconds, 0 nanoseconds]
[right]: [10 nanoseconds, NaT]
```

**Comment by jreback** [comment]
http://netwinder.osuosl.org/pub/netwinder/docs/arm/Apps04vC.html

so not really sure if its big or little.

in any event, we don't directly test this. so not really sure could do anything.

**Comment by yarikoptic** [comment]
similar failures happen on mips
https://buildd.debian.org/status/fetch.php?pkg=pandas&arch=mips&ver=0.17.1-2&stamp=1449539416
if I give you access to the mips box (well -- wouldn't call it a box really since it is of RPi size,  yet to find time to include it into nipy build farm) -- would you be willing to troubleshoot it? ;)

**Comment by jreback** [comment]
these have never been offically supported, nor do we have the resources to do it. If you can hook it up to travis then by all means.

**Comment by yarikoptic** [comment]
watchout for what you wish for!  so -- if I provide you means to hook it up to your PRs (not travis but in addition) -- would that be sufficient? ;)
