### ISSUE TITLE
ERR: better exception for converting bool to datetime with 0.17

### ISSUE THREAD

**Issue by kaotika** [pydata/pandas#11853]
While updating pandas-qt I stumbled about the following exception. Running the same with pandas 0.16 doesn't shows any exception. I think converting a bool to a datetime should raise some exception, but not the one shown. ;-)
 
```
import pandas as pd
import pytest

data = [
    ["text", 123, 12.3, True, "2015-12-16"]
]
df = pd.DataFrame(data, columns=["text", "int", "float", "bool", "date"])

with pytest.raises(ValueError) as err:
    df["text"].apply(pd.to_datetime)
assert 'Unknown string format' in str(err.value)

df["int"].apply(pd.to_datetime)
df["float"].apply(pd.to_datetime)
df["date"].apply(pd.to_datetime)
df["bool"].apply(pd.to_datetime)

Traceback (most recent call last):
  File "test.py", line 16, in <module>
    df["bool"].apply(pd.to_datetime)
  File "/home/kaotika/.virtualenvs/pandas-qt-test/local/lib/python2.7/site-packages/pandas/core/series.py", line 2169, in apply
    mapped = lib.map_infer(values, f, convert=convert_dtype)
  File "pandas/src/inference.pyx", line 1059, in pandas.lib.map_infer (pandas/lib.c:62578)
  File "/home/kaotika/.virtualenvs/pandas-qt-test/local/lib/python2.7/site-packages/pandas/util/decorators.py", line 89, in wrapper
    return func(*args, **kwargs)
  File "/home/kaotika/.virtualenvs/pandas-qt-test/local/lib/python2.7/site-packages/pandas/tseries/tools.py", line 276, in to_datetime
    unit=unit, infer_datetime_format=infer_datetime_format)
  File "/home/kaotika/.virtualenvs/pandas-qt-test/local/lib/python2.7/site-packages/pandas/tseries/tools.py", line 397, in _to_datetime
    return _convert_listlike(np.array([ arg ]), box, format)[0]
  File "/home/kaotika/.virtualenvs/pandas-qt-test/local/lib/python2.7/site-packages/pandas/tseries/tools.py", line 372, in _convert_listlike
    require_iso8601=require_iso8601)
  File "pandas/tslib.pyx", line 1847, in pandas.tslib.array_to_datetime (pandas/tslib.c:37155)
  File "pandas/tslib.pyx", line 2041, in pandas.tslib.array_to_datetime (pandas/tslib.c:36836)
  File "pandas/tslib.pyx", line 1986, in pandas.tslib.array_to_datetime (pandas/tslib.c:35842)
  File "pandas/tslib.pyx", line 1939, in pandas.tslib.array_to_datetime (pandas/tslib.c:34965)
TypeError: object of type 'bool' has no len()
```

**Comment by jreback** [comment]
yep, could be a more informative message.

pull-requests are welcome!

cc @sinhrks

**Comment by jreback** [comment]
note that the default changes for how errors are handled changed in 0.17.0

```
In [8]: df["bool"].apply(pd.to_datetime,errors='ignore')
Out[8]: 
0    True
Name: bool, dtype: bool
```

But the error could still be more informative

**Comment by kaotika** [comment]
Thanks for reply. I should read the changelogs in the future.
