### ISSUE TITLE
pandas import throws AttributeError: 'module' object has no attribute 'dtype'

### ISSUE THREAD

**Issue by gliptak** [pydata/pandas#11851]
In https://travis-ci.org/cloudera/spark-timeseries/jobs/97127307 

Compiled ```numpy-1.10.2``` and ```pandas-0.17.1```

```
======================================================================
ERROR: Failure: AttributeError ('module' object has no attribute 'dtype')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/cloudera/spark-timeseries/python/.eggs/nose-1.3.7-py2.7.egg/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/travis/build/cloudera/spark-timeseries/python/.eggs/nose-1.3.7-py2.7.egg/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/travis/build/cloudera/spark-timeseries/python/.eggs/nose-1.3.7-py2.7.egg/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/travis/build/cloudera/spark-timeseries/python/sparkts/test/test_datetimeindex.py", line 1, in <module>
    from test_utils import PySparkTestCase
  File "/home/travis/build/cloudera/spark-timeseries/python/sparkts/test/test_utils.py", line 2, in <module>
    from sparkts.utils import add_pyspark_path, quiet_py4j
  File "/home/travis/build/cloudera/spark-timeseries/python/sparkts/utils.py", line 4, in <module>
    import pandas as pd
  File "/home/travis/build/cloudera/spark-timeseries/python/.eggs/pandas-0.17.1-py2.7-linux-x86_64.egg/pandas/__init__.py", line 7, in <module>
    from pandas import hashtable, tslib, lib
  File "pandas/src/numpy.pxd", line 157, in init pandas.hashtable (pandas/hashtable.c:38262)
AttributeError: 'module' object has no attribute 'dtype'
```

**Comment by gliptak** [comment]
Similar to https://github.com/pydata/pandas/issues/3711 https://github.com/pydata/pandas/issues/7517

**Comment by jreback** [comment]
has this ever worked?

**Comment by gliptak** [comment]
The Travis build never worked.

Locally running ```python ./setup.py test``` with pip installed ```numpy (1.9.2)``` and ```pandas (0.17.1)``` the build was OK.

I just uninstalled those and pulling in ```numpy-1.10.2``` and ```pandas-0.17.1``` (by the ```setup.py```) my local is also now broken.

The Travis build is a `clean` install (although has a number of other dependencies) ...

**Comment by jreback** [comment]
not sure how you are installing
easiest to use conda

this is not directly s pandas issue it s build / install issue

**Comment by gliptak** [comment]
Installing running ```python ./setup.py test```

https://github.com/gliptak/spark-timeseries/blob/mavenpython/python/setup.py

@jreback What is the right forum to discuss this? Thanks

**Comment by jreback** [comment]
you need to have a higher pandas version requirement I would say

pandas doesn't have that kind of forward compat with numpy

**Comment by gliptak** [comment]
As per above, Pandas 0.17.1 got installed (which seems to be the latest version) with NumPy 0.10.2 (latest version too). What influence would the lower limit have in this case? Thanks

**Comment by jreback** [comment]
not really sure what your issue is
