### ISSUE TITLE
install pandas using pip3 not work 

### ISSUE THREAD

**Issue by Alwerdani** [pydata/pandas#11877]
Hello, 
i am trying to install pandas last commit on  virtualenv  and this error is raise  :
```
Traceback (most recent call last):

  File "/usr/lib/python3.4/distutils/core.py", line 148, in setup

    dist.run_commands()

  File "/usr/lib/python3.4/distutils/dist.py", line 955, in run_commands

    self.run_command(cmd)

  File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command

    cmd_obj.run()

  File "/home/username/.virtualenvs/envname/local/lib/python3.4/site-packages/setuptools/command/bdist_egg.py", line 185, in run

    cmd = self.call_command('install_lib', warn_dir=0)

  File "/home/username/.virtualenvs/envname/local/lib/python3.4/site-packages/setuptools/command/bdist_egg.py", line 171, in call_command

    self.run_command(cmdname)

  File "/usr/lib/python3.4/distutils/cmd.py", line 313, in run_command

    self.distribution.run_command(command)

  File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command

    cmd_obj.run()

  File "/home/username/.virtualenvs/envname/local/lib/python3.4/site-packages/setuptools/command/install_lib.py", line 20, in run

    self.build()

  File "/usr/lib/python3.4/distutils/command/install_lib.py", line 109, in build

    self.run_command('build_ext')

  File "/usr/lib/python3.4/distutils/cmd.py", line 313, in run_command

    self.distribution.run_command(command)

  File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command

    cmd_obj.run()

  File "/tmp/easy_install-856yra78/numpy-1.10.2/numpy/distutils/command/build_ext.py", line 257, in run

  File "/usr/lib/python3.4/distutils/command/build_ext.py", line 448, in build_extensions

    self.build_extension(ext)

  File "/tmp/easy_install-856yra78/numpy-1.10.2/numpy/distutils/command/build_ext.py", line 355, in build_extension

  File "/tmp/easy_install-856yra78/numpy-1.10.2/numpy/distutils/ccompiler.py", line 28, in <lambda>

  File "/tmp/easy_install-856yra78/numpy-1.10.2/numpy/distutils/ccompiler.py", line 231, in CCompiler_compile

  File "/tmp/easy_install-856yra78/numpy-1.10.2/numpy/distutils/ccompiler.py", line 195, in single_compile

  File "/tmp/easy_install-856yra78/numpy-1.10.2/numpy/distutils/ccompiler.py", line 28, in <lambda>

  File "/tmp/easy_install-856yra78/numpy-1.10.2/numpy/distutils/unixccompiler.py", line 52, in UnixCCompiler__compile

distutils.errors.CompileError: Command "x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -DHAVE_NPY_CONFIG_H=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -Ibuild/src.linux-x86_64-3.4/numpy/core/src/private -Inumpy/core/include -Ibuild/src.linux-x86_64-3.4/numpy/core/include/numpy -Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/usr/include/python3.4m -I/home/username/.virtualenvs/envname/include/python3.4m -Ibuild/src.linux-x86_64-3.4/numpy/core/src/private -Ibuild/src.linux-x86_64-3.4/numpy/core/src/private -Ibuild/src.linux-x86_64-3.4/numpy/core/src/private -c build/src.linux-x86_64-3.4/numpy/core/src/multiarray/lowlevel_strided_loops.c -o build/temp.linux-x86_64-3.4/build/src.linux-x86_64-3.4/numpy/core/src/multiarray/lowlevel_strided_loops.o" failed with exit status 4



During handling of the above exception, another exception occurred:



Traceback (most recent call last):

  File "/home/username/.virtualenvs/envname/local/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 1000, in run_setup

    run_setup(setup_script, args)

  File "/home/username/.virtualenvs/envname/local/lib/python3.4/site-packages/setuptools/sandbox.py", line 50, in run_setup

    lambda: execfile(

  File "/home/username/.virtualenvs/envname/local/lib/python3.4/site-packages/setuptools/sandbox.py", line 100, in run

    return func()

  File "/home/username/.virtualenvs/envname/local/lib/python3.4/site-packages/setuptools/sandbox.py", line 52, in <lambda>

    {'__file__':setup_script, '__name__':'__main__'}

  File "/home/username/.virtualenvs/envname/local/lib/python3.4/site-packages/setuptools/compat.py", line 78, in execfile

    exec(compile(source, fn, 'exec'), globs, locs)

  File "setup.py", line 263, in <module>

    'pandas/parser.pyx',

  File "setup.py", line 255, in setup_package

    class CheckSDist(sdist_class):

  File "/tmp/easy_install-856yra78/numpy-1.10.2/numpy/distutils/core.py", line 169, in setup

  File "/usr/lib/python3.4/distutils/core.py", line 163, in setup

    raise SystemExit("error: " + str(msg))

SystemExit: error: Command "x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -DHAVE_NPY_CONFIG_H=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -Ibuild/src.linux-x86_64-3.4/numpy/core/src/private -Inumpy/core/include -Ibuild/src.linux-x86_64-3.4/numpy/core/include/numpy -Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/usr/include/python3.4m -I/home/username/.virtualenvs/envname/include/python3.4m -Ibuild/src.linux-x86_64-3.4/numpy/core/src/private -Ibuild/src.linux-x86_64-3.4/numpy/core/src/private -Ibuild/src.linux-x86_64-3.4/numpy/core/src/private -c build/src.linux-x86_64-3.4/numpy/core/src/multiarray/lowlevel_strided_loops.c -o build/temp.linux-x86_64-3.4/build/src.linux-x86_64-3.4/numpy/core/src/multiarray/lowlevel_strided_loops.o" failed with exit status 4



During handling of the above exception, another exception occurred:



Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-o23ozwi2-build/setup.py", line 596, in <module>

    **setuptools_kwargs)

  File "/usr/lib/python3.4/distutils/core.py", line 108, in setup

    _setup_distribution = dist = klass(attrs)

  File "/home/username/.virtualenvs/envname/local/lib/python3.4/site-packages/setuptools/dist.py", line 239, in __init__

    self.fetch_build_eggs(attrs.pop('setup_requires'))

  File "/home/username/.virtualenvs/envname/local/lib/python3.4/site-packages/setuptools/dist.py", line 264, in fetch_build_eggs

    replace_conflicting=True

  File "/home/username/.virtualenvs/envname/local/lib/python3.4/site-packages/pkg_resources.py", line 580, in resolve

    dist = best[req.key] = env.best_match(req, ws, installer)

  File "/home/username/.virtualenvs/envname/local/lib/python3.4/site-packages/pkg_resources.py", line 818, in best_match

    return self.obtain(req, installer) # try and download/install

  File "/home/username/.virtualenvs/envname/local/lib/python3.4/site-packages/pkg_resources.py", line 830, in obtain

    return installer(requirement)

  File "/home/username/.virtualenvs/envname/local/lib/python3.4/site-packages/setuptools/dist.py", line 314, in fetch_build_egg

    return cmd.easy_install(req)

  File "/home/username/.virtualenvs/envname/local/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 593, in easy_install

    return self.install_item(spec, dist.location, tmpdir, deps)

  File "/home/username/.virtualenvs/envname/local/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 623, in install_item

    dists = self.install_eggs(spec, download, tmpdir)

  File "/home/username/.virtualenvs/envname/local/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 809, in install_eggs

    return self.build_and_install(setup_script, setup_base)

  File "/home/username/.virtualenvs/envname/local/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 1015, in build_and_install

    self.run_setup(setup_script, setup_base, args)

  File "/home/username/.virtualenvs/envname/local/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 1003, in run_setup

    raise DistutilsError("Setup script exited with %s" % (v.args[0],))

distutils.errors.DistutilsError: Setup script exited with error: Command "x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -DHAVE_NPY_CONFIG_H=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -Ibuild/src.linux-x86_64-3.4/numpy/core/src/private -Inumpy/core/include -Ibuild/src.linux-x86_64-3.4/numpy/core/include/numpy -Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/usr/include/python3.4m -I/home/username/.virtualenvs/envname/include/python3.4m -Ibuild/src.linux-x86_64-3.4/numpy/core/src/private -Ibuild/src.linux-x86_64-3.4/numpy/core/src/private -Ibuild/src.linux-x86_64-3.4/numpy/core/src/private -c build/src.linux-x86_64-3.4/numpy/core/src/multiarray/lowlevel_strided_loops.c -o build/temp.linux-x86_64-3.4/build/src.linux-x86_64-3.4/numpy/core/src/multiarray/lowlevel_strided_loops.o" failed with exit status 4

x86_64-linux-gnu-gcc: internal compiler error: Killed (program cc1)

Please submit a full bug report,

with preprocessed source if appropriate.

See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-o23ozwi2-build
Storing debug log for failure in /home/username/.pip/pip.log
```
aslo try to ``` pip3 install pandas ``` and not work

**Comment by TomAugspurger** [comment]
The first error, starting with `distutils.errors.CompileError: Command` is NumPy failing to build. Checkout [their](http://www.scipy.org/scipylib/building/linux.html) instructions, or use [anaconda](http://conda.pydata.org/miniconda.html).

Happy to reopen if you're able to get numpy installed and you still can't install pandas.
