### ISSUE TITLE
to_datetime() works until 2262-04-11

### ISSUE THREAD

**Issue by su79eu7k** [pydata/pandas#11929]
>>> import pandas as pd

    >>> print pd.to_datetime('22620411')
    2262-04-11 00:00:00

    >>> print pd.to_datetime('22620412')
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "C:\Anaconda3\envs\py27\lib\site-packages\pandas\util\decorators.py", line 89, in wrapper
        return func(*args, **kwargs)
      File "C:\Anaconda3\envs\py27\lib\site-packages\pandas\tseries\tools.py", line 276, in to_datetime
        unit=unit, infer_datetime_format=infer_datetime_format)
      File "C:\Anaconda3\envs\py27\lib\site-packages\pandas\tseries\tools.py", line 397, in _to_datetime
        return _convert_listlike(np.array([ arg ]), box, format)[0]
      File "C:\Anaconda3\envs\py27\lib\site-packages\pandas\tseries\tools.py", line 383, in _convert_listlike
        raise e
    pandas.tslib.OutOfBoundsDatetime: Out of bounds nanosecond timestamp: 2262-04-12 00:00:00
    >>>

Please someone confirm the to_datetime() error above. I checked on both python 2.7.11 and python 3.5.1. The exact day could be different with 22620411. You can reproduce easily with 99991231 which is the important day for many ERP related SQL database to represent permanent valid date. 

I think the above is very similar with https://github.com/pydata/pandas/issues/4255 which is the closed one.

**Comment by jreback** [comment]
this is as expected see docs: http://pandas.pydata.org/pandas-docs/stable/timeseries.html#representing-out-of-bounds-spans

**Comment by jreback** [comment]
you are getting an error because the default is to raise

see the to_datetime doc string about the errors kw
