### ISSUE TITLE
Test failure on OpenBSD: unexpected keyword argument 'encoding'

### ISSUE THREAD

**Issue by vext01** [pydata/pandas#11932]
On pandas-0.17.1 on OpenBSD, many tests are failing like this:

```
ERROR: test_infer_s3_compression (pandas.io.tests.test_parsers.TestS3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pandas/util/testing.py", line 1790, in wrapper
    return t(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pandas/io/tests/test_parsers.py", line 4368, in test_infer_s3_compression
    engine='python', compression='infer')
  File "/usr/local/lib/python2.7/site-packages/pandas/io/parsers.py", line 498, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python2.7/site-packages/pandas/io/parsers.py", line 262, in _read
    compression=kwds.get('compression', None))
  File "/usr/local/lib/python2.7/site-packages/pandas/io/common.py", line 290, in get_filepath_or_buffer
    encoding=encoding))
TypeError: get_contents_as_string() got an unexpected keyword argument 'encoding'
```

This is under Python-2.7.11.

**Comment by jreback** [comment]
check your version of boto, 2.38 seems ok. The error is from boto not pandas.
