### ISSUE TITLE
Test failure on OpenBSD: Couldn't find a tree builder with the features you requested: html5lib

### ISSUE THREAD

**Issue by vext01** [pydata/pandas#11931]
Hi,

I'm trying to port pandas-0.17.1 to OpenBSD. There are some failing tests. The first class of failure looks like this:

```
FAIL: test_invalid_url (pandas.io.tests.test_html.TestReadHtml)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pandas/util/testing.py", line 1790, in wrapper
    return t(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pandas/io/tests/test_html.py", line 290, in test_invalid_url
    tm.assert_equal(str(e), 'No tables found')
  File "/usr/local/lib/python2.7/site-packages/pandas/util/testing.py", line 600, in assert_equal
    assert a == b, "%s: %r != %r" % (msg.format(a,b), a, b)
AssertionError: : "Couldn't find a tree builder with the features you requested: html5lib. Do you need to install a parser library?" != 'No tables found'
```

I have installed:
```
py-beautifulsoup-3.2.1
py-beautifulsoup4-4.1.3
py-html5lib-0.11.1
```

Any ideas? Thanks.

**Comment by vext01** [comment]
Should mention, this is on Python-2.7.11

**Comment by vext01** [comment]
I also tried upgrading bs4 to 4.4.1, no change.

**Comment by vext01** [comment]
Update to a newer html5lib and these errors have gone. Closing.
