### ISSUE TITLE
Objects with __iter__ that raise in a Series (or DF presumably)

### ISSUE THREAD

**Issue by timdiels** [pydata/pandas#12006]
I ran into an issue with `plumbum.Path` objects that I want to put inside a Series. They have an `__iter__` that raises an error when the path is not a directory. Is this a design error of `plumbum`, i.e. `__iter__` should never throw, or is this something that `pandas` should work around, e.g. wrap in a try-except?

```python
>>> pd.Series(pb.local.path('/bin/ls'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/data/doc/work/deep_blue_genome/python3/venv/lib/python3.4/site-packages/pandas/core/base.py", line 63, in __repr__
    return str(self)
  File "/mnt/data/doc/work/deep_blue_genome/python3/venv/lib/python3.4/site-packages/pandas/core/base.py", line 42, in __str__
    return self.__unicode__()
  File "/mnt/data/doc/work/deep_blue_genome/python3/venv/lib/python3.4/site-packages/pandas/core/series.py", line 956, in __unicode__
    max_rows=max_rows)
  File "/mnt/data/doc/work/deep_blue_genome/python3/venv/lib/python3.4/site-packages/pandas/core/series.py", line 994, in to_string
    name=name, max_rows=max_rows)
  File "/mnt/data/doc/work/deep_blue_genome/python3/venv/lib/python3.4/site-packages/pandas/core/series.py", line 1024, in _get_repr
    result = formatter.to_string()
  File "/mnt/data/doc/work/deep_blue_genome/python3/venv/lib/python3.4/site-packages/pandas/core/format.py", line 225, in to_string
    fmt_values = self._get_formatted_values()
  File "/mnt/data/doc/work/deep_blue_genome/python3/venv/lib/python3.4/site-packages/pandas/core/format.py", line 215, in _get_formatted_values
    na_rep=self.na_rep)
  File "/mnt/data/doc/work/deep_blue_genome/python3/venv/lib/python3.4/site-packages/pandas/core/format.py", line 1976, in format_array
    return fmt_obj.get_result()
  File "/mnt/data/doc/work/deep_blue_genome/python3/venv/lib/python3.4/site-packages/pandas/core/format.py", line 1992, in get_result
    fmt_values = self._format_strings()
  File "/mnt/data/doc/work/deep_blue_genome/python3/venv/lib/python3.4/site-packages/pandas/core/format.py", line 2034, in _format_strings
    fmt_values.append(' %s' % _format(v))
  File "/mnt/data/doc/work/deep_blue_genome/python3/venv/lib/python3.4/site-packages/pandas/core/format.py", line 2018, in _format
    return '%s' % formatter(x)
  File "/mnt/data/doc/work/deep_blue_genome/python3/venv/lib/python3.4/site-packages/pandas/core/format.py", line 2005, in <lambda>
    (lambda x: com.pprint_thing(x, escape_chars=('\t', '\r', '\n')))
  File "/mnt/data/doc/work/deep_blue_genome/python3/venv/lib/python3.4/site-packages/pandas/core/common.py", line 2822, in pprint_thing
    elif is_sequence(thing) and _nest_lvl < \
  File "/mnt/data/doc/work/deep_blue_genome/python3/venv/lib/python3.4/site-packages/pandas/core/common.py", line 2378, in is_sequence
    iter(x)
  File "/mnt/data/doc/work/deep_blue_genome/python3/venv/lib/python3.4/site-packages/plumbum/path/base.py", line 42, in __iter__
    return iter(self.list())
  File "/mnt/data/doc/work/deep_blue_genome/python3/venv/lib/python3.4/site-packages/plumbum/path/local.py", line 112, in list
    return [self / fn for fn in os.listdir(str(self))]
NotADirectoryError: [Errno 20] Not a directory: '/bin/ls'
>>> sys.version
'3.4.3 (default, Oct 13 2015, 23:27:37) \n[GCC 5.2.0]'
>>> pandas.__version__
'0.17.1'
```

Thanks!

**Comment by timdiels** [comment]
I've decided to switch from `plumbum.Path` to `pathlib.Path`, which doesn't have an `__iter__` but instead has `iterdir` which probably is the better design choice as it avoids problems like these.

**Comment by jreback** [comment]
Series introspected the passed objects to see if they are list of objects 
hence if they are iterable

what you show above should probably raise a TypeError instead of a ValueError
