### ISSUE TITLE
nunique + TimeGrouper error

### ISSUE THREAD

**Issue by wavexx** [pydata/pandas#12352]
This used to work in the past:

````
tmp = pd.DataFrame({
        'ID': {pd.Timestamp('2015-06-05 00:00:00'): '0010100903', pd.Timestamp('2015-06-08 00:00:00'): '0010150847'},
        'DATE': {pd.Timestamp('2015-06-05 00:00:00'): '2015-06-05', pd.Timestamp('2015-06-08 00:00:00'): '2015-06-08'}})
tmp.groupby(pd.TimeGrouper('D')).ID.nunique()
````

but now I get the obscure:

````
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    tmp.groupby(pd.TimeGrouper('D')).ID.nunique()
  File "/usr/lib/python3/dist-packages/pandas/core/groupby.py", line 2697, in nunique
    name=self.name)
  File "/usr/lib/python3/dist-packages/pandas/core/series.py", line 227, in __init__
    data = SingleBlockManager(data, index, fastpath=True)
  File "/usr/lib/python3/dist-packages/pandas/core/internals.py", line 3736, in __init__
    ndim=1, fastpath=True)
  File "/usr/lib/python3/dist-packages/pandas/core/internals.py", line 2454, in make_block
    placement=placement)
  File "/usr/lib/python3/dist-packages/pandas/core/internals.py", line 87, in __init__
    len(self.values), len(self.mgr_locs)))
ValueError: Wrong number of items passed 2, placement implies 4
````

**Comment by wavexx** [comment]
The logically equivalent:

````
tmp.groupby(pd.TimeGrouper('D')).ID.apply(lambda x: x.nunique())
````

works as intended.

**Comment by jreback** [comment]
hmm, does look buggy.

**Comment by jreback** [comment]
this last worked in 0.16.2, and failed in 0.17.0 (and continues in 0.18.0),

**Comment by wavexx** [comment]
Thanks for investigating the exact breaking point. I'm currently revisiting some code that I wrote for python2.7 with pandas 0.16.* and now I'm porting to python3 and 0.17.1 (currently Debian unstable).

**Comment by jreback** [comment]
yeah there were some fixes related to this, but this one didn't take.
