### ISSUE TITLE
tz_localize NonExistentTimeError: 2013-03-31 02:00:00

### ISSUE THREAD

**Issue by LorenzoBottaccioli** [pydata/pandas#12446]
Hello I'm having troubles with the tz_localize function. 
I run the code :

```
    df = pd.read_csv('input.csv', sep=";", index_col='Date Time', decimal=',')
    df.index = pd.to_datetime(df.index, unit='s').tz_localize('Europe/Rome')
```
and I get this error:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 2820, in run_code
    exec code_obj in self.user_global_ns, self.user_ns
  File "<ipython-input-62-1e9889f6b894>", line 1, in <module>
    df.index = pd.to_datetime(df.index, unit='s').tz_localize('Europe/Rome')
  File "/usr/local/lib/python2.7/dist-packages/pandas/util/decorators.py", line 89, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pandas/tseries/index.py", line 1724, in tz_localize
    ambiguous=ambiguous)
  File "pandas/tslib.pyx", line 3781, in pandas.tslib.tz_localize_to_utc (pandas/tslib.c:64980)
NonExistentTimeError: 2013-03-31 02:00:00
```
I have pandas '0.17.1' running on python2.7. In attachment you find the input file [input.zip](https://github.com/pydata/pandas/files/147045/input.zip).

Best

**Comment by kawochen** [comment]
that's daylight saving (input is wonky)

**Comment by jreback** [comment]
that's not a valid time at all; it is possible to pass an ``ambiguous`` argument to ``.tz_localize(...)`` to deal with ambiguous times,, but 02:00:00 is not a valid time.

```
In [3]: Timestamp('2013-03-31 01:00:00').tz_localize('Europe/Rome')
Out[3]: Timestamp('2013-03-31 01:00:00+0100', tz='Europe/Rome')

In [4]: Timestamp('2013-03-31 03:00:00').tz_localize('Europe/Rome')
Out[4]: Timestamp('2013-03-31 03:00:00+0200', tz='Europe/Rome')

In [5]: Timestamp('2013-03-31 02:00:00').tz_localize('Europe/Rome')
NonExistentTimeError: 2013-03-31 02:00:00

In [6]: Timestamp('2013-03-31 03:00:00').tz_localize('Europe/Rome', ambiguous=False)
Out[6]: Timestamp('2013-03-31 03:00:00+0200', tz='Europe/Rome')

In [7]: Timestamp('2013-03-31 03:00:00').tz_localize('Europe/Rome', ambiguous=True)
Out[7]: Timestamp('2013-03-31 03:00:00+0200', tz='Europe/Rome')

In [8]: Timestamp('2013-03-31 01:00:00').tz_localize('Europe/Rome', ambiguous=True)
Out[8]: Timestamp('2013-03-31 01:00:00+0100', tz='Europe/Rome')

In [9]: Timestamp('2013-03-31 01:00:00').tz_localize('Europe/Rome', ambiguous=False)
Out[9]: Timestamp('2013-03-31 01:00:00+0100', tz='Europe/Rome')
```
