### ISSUE TITLE
pandas_for_finance TypeError: [unicode] is not implemented as a table column

### ISSUE THREAD

**Issue by LastAncientOne** [pydata/pandas#12447]
#### Code Sample, a copy-pastable example if possible
p.to_hdf('quotes.hdf','df',format='table')

#### Expected Output
Saves files

#### output of ``pd.show_versions()``
Traceback (most recent call last):

  File "<ipython-input-15-7be322c5e66c>", line 1, in <module>
    p.to_hdf('quotes.hdf','df',format='table')

  File "C:\Users\LastAncientOne\Anaconda2\lib\site-packages\pandas\core\generic.py", line 939, in to_hdf
    return pytables.to_hdf(path_or_buf, key, self, **kwargs)

  File "C:\Users\LastAncientOne\Anaconda2\lib\site-packages\pandas\io\pytables.py", line 257, in to_hdf
    f(store)

  File "C:\Users\LastAncientOne\Anaconda2\lib\site-packages\pandas\io\pytables.py", line 252, in <lambda>
    f = lambda store: store.put(key, value, **kwargs)

  File "C:\Users\LastAncientOne\Anaconda2\lib\site-packages\pandas\io\pytables.py", line 814, in put
    self._write_to_group(key, value, append=append, **kwargs)

  File "C:\Users\LastAncientOne\Anaconda2\lib\site-packages\pandas\io\pytables.py", line 1252, in _write_to_group
    s.write(obj=value, append=append, complib=complib, **kwargs)

  File "C:\Users\LastAncientOne\Anaconda2\lib\site-packages\pandas\io\pytables.py", line 4166, in write
    obj=obj, data_columns=data_columns, **kwargs)

  File "C:\Users\LastAncientOne\Anaconda2\lib\site-packages\pandas\io\pytables.py", line 3757, in write
    **kwargs)

  File "C:\Users\LastAncientOne\Anaconda2\lib\site-packages\pandas\io\pytables.py", line 3434, in create_axes
    raise e

TypeError: [unicode] is not implemented as a table column

Using Pandas u'0.17.1'

**Comment by jreback** [comment]
the webinar was showing python 3 (and as was the environment.yaml file). 

In py2 its a bit tricker as you have to encode the columns. You *could* also save a ``table='fixed'`` (which emit a warning as it is pickled)
```
In [16]: df = DataFrame({'A' : tm.makeUnicodeIndex(5)})

In [17]: df
Out[17]: 
            A
0  ךהאפל4רלשן
1  גמרי58ףן5ו
2  4זכאךט9ןדמ
3  ב999שגשלכם
4  שאךיםפקבה8

In [18]: df.A.values
Out[18]: 
array([u'\u05da\u05d4\u05d0\u05e4\u05dc4\u05e8\u05dc\u05e9\u05df',
       u'\u05d2\u05de\u05e8\u05d958\u05e3\u05df5\u05d5',
       u'4\u05d6\u05db\u05d0\u05da\u05d89\u05df\u05d3\u05de',
       u'\u05d1999\u05e9\u05d2\u05e9\u05dc\u05db\u05dd',
       u'\u05e9\u05d0\u05da\u05d9\u05dd\u05e4\u05e7\u05d1\u05d48'], dtype=object)

In [19]: df['A'] = df.A.str.encode('utf-8')

In [20]: df.A.values
Out[20]: 
array([ '\xd7\x9a\xd7\x94\xd7\x90\xd7\xa4\xd7\x9c4\xd7\xa8\xd7\x9c\xd7\xa9\xd7\x9f',
       '\xd7\x92\xd7\x9e\xd7\xa8\xd7\x9958\xd7\xa3\xd7\x9f5\xd7\x95',
       '4\xd7\x96\xd7\x9b\xd7\x90\xd7\x9a\xd7\x989\xd7\x9f\xd7\x93\xd7\x9e',
       '\xd7\x91999\xd7\xa9\xd7\x92\xd7\xa9\xd7\x9c\xd7\x9b\xd7\x9d',
       '\xd7\xa9\xd7\x90\xd7\x9a\xd7\x99\xd7\x9d\xd7\xa4\xd7\xa7\xd7\x91\xd7\x948'], dtype=object)

In [21]: df.to_hdf('test.h5','df',format='table')

In [22]: pd.read_hdf('test.h5','df'
   ....: )
Out[22]: 
            A
0  ךהאפל4רלשן
1  גמרי58ףן5ו
2  4זכאךט9ןדמ
3  ב999שגשלכם
4  שאךיםפקבה8
```
