### ISSUE TITLE
Pandas for Finance AttributeError: 'DataFrame' object has no attribute 'rolling'

### ISSUE THREAD

**Issue by LastAncientOne** [pydata/pandas#12478]
#### Code Sample, a copy-pastable example if possible
rets.rolling(window=22).min().plot.line(figsize=(15,10))

#### output of ``pd.show_versions()``
Traceback (most recent call last):

  File "<ipython-input-78-e1069c24fa37>", line 1, in <module>
    rets.rolling(window=22).min().plot.line(figsize=(15,10))

  File "C:\Users\LastAncientOne\Anaconda3\lib\site-packages\pandas\core\generic.py", line 2360, in __getattr__
    (type(self).__name__, name))

**Comment by jreback** [comment]
you need to use v0.18.0rc1 as indicated in the environment file
