### ISSUE TITLE
Pandas 0.18.1rc2 requires GLIBC_2.14, but uses only a few (basic) symbols - cannot be used on Debian wheezy

### ISSUE THREAD

**Issue by ctyler-wapiti** [pydata/pandas#12596]
We can install pandas 0.18.1rc2 on our wheezy VM but when we import it we get the following error:

```
Python 2.7.11 |Continuum Analytics, Inc.| (default, Dec  6 2015, 18:08:32) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
>>> import pandas
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/miniconda/lib/python2.7/site-packages/pandas/__init__.py", line 31, in <module>
    "extensions first.".format(module))
ImportError: C extension: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /opt/miniconda/lib/python2.7/site-packages/pandas/hashtable.so) not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace' to build the C extensions first.
```

Given that said hashtable.so only needs the following (non-libpython.so) symbols:

```
# nm -D /opt/miniconda/lib/python2.7/site-packages/pandas/hashtable.so | fgrep -v Py | fgrep ' U '
                 U calloc
                 U free
                 U malloc
                 U memcpy
                 U memset
                 U realloc
                 U strcmp
                 U strlen
                 U vsnprintf
```

would it be possible to make the releases in the pandas channel work with older versions of libc? Note that wheezy is still the version used by Google for their Appengine Python runtime image, among others. Thanks!

**Comment by jreback** [comment]
this is because I am building them in a local vm

the production builds are built to support this

just build from source
