### ISSUE TITLE
BUG: Index.str.partition gives ValueError while trying to compute index name (expand=False)

### ISSUE THREAD

**Issue by pwaller** [pydata/pandas#12617]
`Index.str.partition`'s behaviour changed in 3ab35b40274276e4f9b40918a7e260f1abb941c1 in a backwards incompatible way which doesn't seem intentional.

#### Code Sample, a copy-pastable example if possible

```
python3 -c 'import pandas; pandas.Index(["a,b", "c,d"], name="hello").str.partition(",")'
```

```pytb
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/pwaller/.local/src/pandas/pandas/core/strings.py", line 1432, in partition
    return self._wrap_result(result, expand=expand)
  File "/home/pwaller/.local/src/pandas/pandas/core/strings.py", line 1348, in _wrap_result
    return MultiIndex.from_tuples(result, names=name)
  File "/home/pwaller/.local/src/pandas/pandas/indexes/multi.py", line 889, in from_tuples
    return MultiIndex.from_arrays(arrays, sortorder=sortorder, names=names)
  File "/home/pwaller/.local/src/pandas/pandas/indexes/multi.py", line 844, in from_arrays
    names=names, verify_integrity=False)
  File "/home/pwaller/.local/src/pandas/pandas/indexes/multi.py", line 92, in __new__
    result._set_names(names)
  File "/home/pwaller/.local/src/pandas/pandas/indexes/multi.py", line 446, in _set_names
    raise ValueError('Length of names must match number of levels in '
ValueError: Length of names must match number of levels in MultiIndex.
```

#### Expected Output

```python
In [1]: import pandas; pandas.Index(["a,b", "c,d"], name="hello").str.partition(",")
Out[1]: 
MultiIndex(levels=[['a', 'c'], [','], ['b', 'd']],
           labels=[[0, 1], [0, 0], [0, 1]])
```

#### Versions

I bisected the problem to 3ab35b40274276e4f9b40918a7e260f1abb941c1 (cc @sinhrks). The problem is not present in 0.17.1 and is present in 0.18.0rc2. 

Note: when I use a `name="foo"`, it happens to work because it has the correct length, the index name ends up being `["f", "o", "o"]`, so it's possible this is tested somewhere and happens to work even though it's not correct for a large number of use cases.

**Comment by sinhrks** [comment]
Thanks, and sorry for the inconvenience. I'll check soon.

**Comment by jreback** [comment]
Tthis is not a regression. The ``name`` argument you were using in 0.17.1 didn't do anything (a ``MultiIndex`` does not have a ``name``, only ``names`` for the levels), 

So the result (w/o specifying name) is correct.

The ``expand=False`` case has a bug in it.

```
In [50]: pandas.Index(["a,b", "c,d"], expand=True).str.partition(",")
Out[50]: 
MultiIndex(levels=[[u'a', u'c'], [u','], [u'b', u'd']],
           labels=[[0, 1], [0, 0], [0, 1]])

In [51]: pandas.Index(["a,b", "c,d"], expand=True).str.partition(",").names
Out[51]: FrozenList([None, None, None])

In [52]: pd.__version__
Out[52]: '0.18.0+7.g17a5982'
```
