### ISSUE TITLE
COMPAT: sparse issue on compat build

### ISSUE THREAD

**Issue by jreback** [pydata/pandas#12784]
xref #12779 

https://travis-ci.org/pydata/pandas/jobs/120431675

I suspect because of ``numpy=1.7.1``
```
======================================================================
ERROR: test_take (pandas.sparse.tests.test_array.TestSparseArray)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/pydata/pandas/pandas/sparse/tests/test_array.py", line 40, in test_take
    self.assertEqual(self.arr.take(2), np.take(self.arr_data, 2))
  File "/home/travis/miniconda/envs/pandas/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 104, in take
    return take(indices, axis, out, mode)
ValueError: object of too small depth for desired array
```

on win64, python 3.5, numpy ==1.10.4
This is prob a take issue as well, I think these should *always* be ``int32`` (the block locations).
```
======================================================================
FAIL: test_sparse_max_row (pandas.tests.test_format.TestSeriesFormatting)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\conda\Documents\pandas3.5\pandas\tests\test_format.py", line 3721, in test_sparse_max_row
    self.assertEqual(result, exp)
AssertionError: '0   [98 chars]0, 3])\nBlock lengths: array([1, 1])' != '0   [98 chars]0, 3], dtype=int32)\nBlock length
s: array([1, 1], dtype=int32)'
  0    1.0
  1    NaN
  2    NaN
  3    3.0
  4    NaN
  dtype: float64
  BlockIndex
- Block locations: array([0, 3])
+ Block locations: array([0, 3], dtype=int32)
?                              +++++++++++++
- Block lengths: array([1, 1])+ Block lengths: array([1, 1], dtype=int32)?                            +++++++++++++
```

**Comment by jreback** [comment]
@sinhrks

**Comment by jreback** [comment]
2nd fixed here: https://github.com/jreback/pandas/commit/a6b1a221aa675fd2d0d0916f099af4cc3e60352f

**Comment by jreback** [comment]
@sinhrks ``np.take`` in < 1.8 doesn't support indexing via scalars :<
