### ISSUE TITLE
COMPAT: python-dateutil 2.5.3

### ISSUE THREAD

**Issue by jreback** [pydata/pandas#12944]
so this parade of dateutil changes causes havoc in the testsuite as we adjust.

previous fixes: #12731, #12613 

revert this: https://github.com/pydata/pandas/commit/161724470784da042f8fd5294cfb39acad6dc5c2

Let's see what the correct fixes are and maybe need to ban certain buggy versions.
```
======================================================================
FAIL: test_parsers_dayfirst_yearfirst (pandas.tseries.tests.test_tslib.TestDatetimeParsingWrappers)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jreback/pandas/pandas/tseries/tests/test_tslib.py", line 631, in test_parsers_dayfirst_yearfirst
    self.assertRaises(tslib.DateParseError, f, date_str)
  File "/Users/jreback/pandas/pandas/util/testing.py", line 2162, in assertRaises
    _callable(*args, **kwargs)
  File "/Users/jreback/pandas/pandas/util/testing.py", line 2232, in __exit__
    raise AssertionError("{0} not raised.".format(name))
AssertionError: DateParseError not raised.
```

**Comment by jreback** [comment]
xref #7599
