### ISSUE TITLE
url scraping error

### ISSUE THREAD

**Issue by csayantan** [pydata/pandas#12970]
```
from nsepy import get_history
from datetime import date
import pandas as pd
import requests
from io import BytesIO 
import certifi
from dateutil.relativedelta import relativedelta
#import numpy as np
#import matplotlib.pyplot as plt
import datetime
import numpy as np
import matplotlib.colors as colors
import matplotlib.finance as finance
import matplotlib.dates as mdates
import matplotlib.ticker as mticker
import matplotlib.mlab as mlab
import matplotlib.pyplot as plt
import matplotlib.font_manager as font_manager
import requests
from nsepy.archives import html_to_rows
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np
import matplotlib as plt
'''
import sys


reload(sys)  
sys.setdefaultencoding('Cp1252')
'''
url1 = 'http://www.nseindia.com/live_market/dynaContent/live_watch/option_chain/optionKeys.jsp?segmentLink=17&instrument=OPTIDX&symbol=NIFTY&date=26MAY2016'
def dataFromHtmlInPy(url):

	headers = { 'Accept' : '*/*',
	            'User-Agent' : 'Mozilla/5.0',
	            'Refers' : 'http://www.nseindia.com',
	            'Connection' : 'keep-alive'
	          }
            
	getContents = requests.get(url,headers=headers).text
	#dataFromHtm=pd.read_html(BytesIO(getContents))
        dataFromHtm = BeautifulSoup(getContents, "lxml")
        return dataFromHtm

data=pd.DataFrame(dataFromHtmlInPy(url=url1))
print(data.head())
```
I am new to panda and python.however I need dataframe as the same in the url1.
few info i need to scrapped from there. i need to calculate daily PCR. 
i encounter an error like:
```

Traceback (most recent call last):
  File "dataFromNsePage.py", line 46, in <module>
    data=pd.DataFrame(dataFromHtmlInPy(url=url1))
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/frame.py", line 282, in __init__
    raise TypeError("data argument can't be an iterator")
TypeError: data argument can't be an iterator 
```

**Comment by jreback** [comment]
pls read the [docs](http://pandas.pydata.org/pandas-docs/stable/io.html#reading-html-content)

``pd.read_html`` return a list
if you are manually parsing you are on your own; you are passing an interator, try putting a ``list()`` around it

**Comment by csayantan** [comment]
pd.read_html returning 
urllib2.HTTPError: HTTP Error 403: Forbidden
i need to paarse it through headers that is defined in the code.

**Comment by jreback** [comment]
you may need to pass an encoding or have other modifications to requests

**Comment by csayantan** [comment]
```
from nsepy import get_history
from datetime import date
import pandas as pd
import requests
from io import BytesIO 
import certifi
from dateutil.relativedelta import relativedelta
#import numpy as np
#import matplotlib.pyplot as plt
import datetime
import numpy as np
import matplotlib.colors as colors
import matplotlib.finance as finance
import matplotlib.dates as mdates
import matplotlib.ticker as mticker
import matplotlib.mlab as mlab
import matplotlib.pyplot as plt
import matplotlib.font_manager as font_manager
import requests
from nsepy.archives import html_to_rows
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np
import matplotlib as plt

import sys


reload(sys)  
sys.setdefaultencoding('Cp1252')

url1 = 'http://www.nseindia.com/live_market/dynaContent/live_watch/option_chain/optionKeys.jsp?segmentLink=17&instrument=OPTIDX&symbol=NIFTY&date=26MAY2016'
def dataFromHtmlInPy(url):

	headers = { 'Accept' : '*/*',
	            'User-Agent' : 'Mozilla/5.0',
	            'Refers' : 'http://www.nseindia.com',
	            'Connection' : 'keep-alive'
	          }
            
	getContents = requests.get(url,headers=headers).content
	dataFromHtm=pd.read_html(BytesIO(getContents))
        #dataFromHtm = BeautifulSoup(getContents, "lxml")
        return dataFromHtm

data=pd.DataFrame(dataFromHtmlInPy(url=url1))
print(data.to_html())
```

this code returned  data like this.but i am missing the table of content of it. please suggest 
```
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>0</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>0  \
0  Opt...</td>
    </tr>
    <tr>
      <th>1</th>
      <td>CALLS         Â     PUTS     Chart     OI ...</td>
    </tr>
    <tr>
      <th>2</th>
      <td>0
0  Top</td>
    </tr>
  </tbody>
</table>

```
