### ISSUE TITLE
TST: Can't Seem to Run Individual Test Suites in pandas/io

### ISSUE THREAD

**Issue by gfyoung** [pydata/pandas#13015]
```
$ python /home/user/Repositories/pandas/pandas/io/tests/test_data.py
Traceback (most recent call last):
  File "/home/user/Repositories/pandas/pandas/io/tests/test_data.py", line 4, in <module>
    from pandas import compat
  File "/home/user/miniconda2/envs/pandas-dev/lib/python2.7/site-packages/pandas/__init__.py", line 39, in <module>
    from pandas.core.api import *
  File "/home/user/miniconda2/envs/pandas-dev/lib/python2.7/site-packages/pandas/core/api.py", line 10, in <module>
    from pandas.core.groupby import Grouper
  File "/home/user/miniconda2/envs/pandas-dev/lib/python2.7/site-packages/pandas/core/groupby.py", line 18, in <module>
    from pandas.core.frame import DataFrame
  File "/home/user/miniconda2/envs/pandas-dev/lib/python2.7/site-packages/pandas/core/frame.py", line 39, in <module>
    from pandas.core.series import Series
  File "/home/user/miniconda2/envs/pandas-dev/lib/python2.7/site-packages/pandas/core/series.py", line 2929, in <module>
    import pandas.tools.plotting as _gfx  # noqa
  File "/home/user/miniconda2/envs/pandas-dev/lib/python2.7/site-packages/pandas/tools/plotting.py", line 25, in <module>
    import pandas.tseries.converter as conv
  File "/home/user/miniconda2/envs/pandas-dev/lib/python2.7/site-packages/pandas/tseries/converter.py", line 7, in <module>
    import matplotlib.units as units
  File "/home/user/miniconda2/envs/pandas-dev/lib/python2.7/site-packages/matplotlib/__init__.py", line 135, in <module>
    __version__ = str(get_versions()['version'])
  File "/home/user/miniconda2/envs/pandas-dev/lib/python2.7/site-packages/matplotlib/_version.py", line 21, in get_versions
    return json.loads(version_json)
AttributeError: 'module' object has no attribute 'loads'
```
INSTALLED VERSIONS
------------------
pandas: 0.18.0+174.g65ed3af
nose: 1.3.7
pip: 8.1.1
setuptools: 20.0
Cython: 0.23.4
numpy: 1.11.0
scipy: 0.17.0
statsmodels: 0.6.1
xarray: 0.7.2
IPython: None
sphinx: None
patsy: 0.4.1
dateutil: 2.5.3
pytz: 2016.4
blosc: None
bottleneck: 1.0.0
tables: 3.2.2
numexpr: 2.5
matplotlib: 1.5.1
openpyxl: 2.3.3
xlrd: 0.9.4
xlwt: 1.0.0
xlsxwriter: 0.8.4
lxml: 3.6.0
bs4: 4.4.1
html5lib: 0.9999999
httplib2: None
apiclient: None
sqlalchemy: 1.0.12
pymysql: None
psycopg2: None
jinja2: 2.8
boto: 2.39.0
pandas_datareader: None

Somewhere in the last 32 commits or so to the `master` branch this broke because my branch for refactoring `test_parsers` was that many commits behind when it last worked.  I also confirmed the breakage on `master` too.

**Comment by jreback** [comment]
we don't support that, though I guess it would be nice (and the reason things have ``__main__`` in them). But its not documented / tested anywhere.
```
[jreback-~/pandas] nosetests  pandas/io/tests/test_data.py
.S...SS...S...^C
----------------------------------------------------------------------
Ran 15 tests in 18.535s

OK (SKIP=4)
[jreback-~/pandas] 
```

**Comment by gfyoung** [comment]
The thing was I was able to run it before just fine.  Also, you can run other test suites (outside of `pandas/io`) just fine using the command above.

**Comment by gfyoung** [comment]
Hmmm...well at least `nosetests` works, so I'll close this then.

**Comment by gfyoung** [comment]
Hmmm...well at least `nosetests` works, so I'll close this then.

**Comment by jreback** [comment]
this happens on other files as well

not really sure why

**Comment by gfyoung** [comment]
Yeah...well it's not documented as being supported (I didn't know that until you mentioned it), so technically not an issue, and at least I still have means of running individual test suites.
