### ISSUE TITLE
AttributeError when trying to freeze pandas.io.sql.read_sql() with cx_freeze

### ISSUE THREAD

**Issue by dougthor42** [pydata/pandas#13100]
#### Summary
When freezing an application that uses `pandas.io.sql.read_sql()` (alias: `pd.read_sql()`) via cx_freeze, the build succeeds but the execution fails with `AttributeError: 'str' object has no attribute 'cursor'`.

#### Code
Below are the minimum requirements to recreate the issue. Put both files in an empty directory and run `python build_exe.py build`. Then execute `.\build\exe.win-amd64-3.4\test.exe`. An error will be displayed (text below). 

```
# test.py
import pandas as pd
URL = <redacted>             # mysql+pyodbc://...
QUERY = <redacted>
print(pd.read_sql(QUERY, URL).tail())    # comment this line for a successful build+execute
print("got to the end")
```

```
# build_exe.py         $ python build_exe.py build
from cx_Freeze import setup, Executable

setup(
    name="a",
    version="0.0.1",
    description="a",
    options={
        "build_exe": {
            "packages": ["sqlalchemy.dialects.mysql", ],
            "silent": True,
            }
    },
    executables=[
        Executable(
            "test.py",
            base=None,
            ),
    ],
)
```

#### Error output:
```
Traceback (most recent call last):
  File "C:\WinPython34_x64\python-3.4.3.amd64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
    exec(code, m.__dict__)
  File "test.py", line 16, in <module>
  File "C:\WinPython34_x64\python-3.4.3.amd64\lib\site-packages\pandas\io\sql.py", line 499, in read_sql
    chunksize=chunksize)
  File "C:\WinPython34_x64\python-3.4.3.amd64\lib\site-packages\pandas\io\sql.py", line 1599, in read_query
    cursor = self.execute(*args)
  File "C:\WinPython34_x64\python-3.4.3.amd64\lib\site-packages\pandas\io\sql.py", line 1559, in execute
    cur = self.con.cursor()
AttributeError: 'str' object has no attribute 'cursor'
```

#### Expected Output
N/A

#### output of ``pd.show_versions()``
```
INSTALLED VERSIONS
------------------
commit: None
python: 3.4.3.final.0
python-bits: 64
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 42 Stepping 7, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None

pandas: 0.18.1
nose: 1.3.7
pip: 8.1.1
setuptools: 21.0.0
Cython: 0.22
numpy: 1.11.0
scipy: 0.17.0
statsmodels: 0.6.1
xarray: None
IPython: 4.2.0
sphinx: 1.4.1
patsy: 0.4.1
dateutil: 2.5.3
pytz: 2016.4
blosc: None
bottleneck: None
tables: 3.1.1
numexpr: 2.4
matplotlib: 1.5.1
openpyxl: None
xlrd: 0.9.4
xlwt: None
xlsxwriter: 0.8.6
lxml: None
bs4: 4.4.1
html5lib: 0.9999999
httplib2: 0.9.1
apiclient: 1.4.1
sqlalchemy: 1.0.12
pymysql: None
psycopg2: 2.6.1 (dt dec pq3 ext lo64)
jinja2: 2.8
boto: None
pandas_datareader: None
```

#### Other Versions:
```
cx_freeze: 4.3.4
pyodbc: 3.0.10
```

**Comment by jreback** [comment]
pls post to cx_freeze
your packaging is not working

**Comment by dougthor42** [comment]
Posted to [cx_freeze#196](https://bitbucket.org/anthony_tuininga/cx_freeze/issues/196/).

**Comment by dougthor42** [comment]
## For anyone who finds this in the future:
Turns out that using an SQLAlchemy engine rather than the raw connection string fixes the issue [[source](http://stackoverflow.com/a/30653988/1354930)].

```python
# test.py
import pandas as pd
from sqlalchemy import create_engine
URL = <redacted>             # mysql+pyodbc://...
ENGINE = create_engine(URL, echo=False)
QUERY = <redacted>
print(pd.read_sql(QUERY, URL).tail())    # comment this line for a successful build+execute
print("got to the end")
```

When doing that, you also need to add the dialect (in my case, `pyodbc`) to the packages list of cx_freeze:

```python
...
    options={
        "build_exe": {
            "packages": ["sqlalchemy.dialects.mysql", "pyodbc"],
            "silent": True,
            }
    },
...
```
