### ISSUE TITLE
FAIL: test_getitem_setitem_datetime_tz_dateutil (pandas.tests.series.test_timeseries.TestSeriesTimeSeries) in 0.18.1

### ISSUE THREAD

**Issue by neirbowj** [pydata/pandas#13186]
This test fails under py27 and py34.

#### Code Sample, a copy-pastable example if possible

```
% nosetests-2.7 pandas.tests.series.test_timeseries:TestSeriesTimeSeries.test_getitem_setitem_datetime_tz_dateutil
F
======================================================================
FAIL: test_getitem_setitem_datetime_tz_dateutil (pandas.tests.series.test_timeseries.TestSeriesTimeSeries)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pandas/tests/series/test_timeseries.py", line 373, in test_getitem_setitem_datetime_tz_dateutil
    assert_series_equal(result, ts)
  File "/usr/local/lib/python2.7/site-packages/pandas/util/testing.py", line 1049, in assert_series_equal
    check_less_precise, obj='{0}'.format(obj))
  File "pandas/src/testing.pyx", line 58, in pandas._testing.assert_almost_equal (pandas/src/testing.c:3887)
  File "pandas/src/testing.pyx", line 147, in pandas._testing.assert_almost_equal (pandas/src/testing.c:2769)
  File "/usr/local/lib/python2.7/site-packages/pandas/util/testing.py", line 915, in raise_assert_detail
    raise AssertionError(msg)
AssertionError: Series are different

Series values are different (2.0 %)
[left]:  [-1.86439680803, -1.48753990623, 1.70014886271, -0.681093073082, -0.681093073082, -1.53036995139, -0.874340620421, -0.449379718617, 0.199006661768, -0.216851984269, 0.678233107275, 0.845483557984, -0.591939974933, -0.710426528489, -0.246902534317, 1.62090443334, -0.29205483777, 0.734444716348, -0.124417337768, -0.708111449895, -0.399676812698, -0.165487765543, -1.52919474544, -0.743328414533, -0.826169397925, -0.621684486914, -1.02101828767, 0.507572292251, 1.64945264051, -1.16729493131, -1.59575805184, 1.22194630958, -0.324260225115, -2.70908723091, 0.419972356697, 0.199954966493, 1.51343480756, 0.0528252604798, -1.59926845777, 1.72143823853, -0.391567581633, 0.302380438723, 0.151857495879, -0.770407214622, 1.11355519113, 0.373448388224, -0.0993048929725, -2.01116150929, -0.953752431803, -0.53637958571]
[right]: [-1.86439680803, -1.48753990623, 1.70014886271, 0.328450105526, -0.681093073082, -1.53036995139, -0.874340620421, -0.449379718617, 0.199006661768, -0.216851984269, 0.678233107275, 0.845483557984, -0.591939974933, -0.710426528489, -0.246902534317, 1.62090443334, -0.29205483777, 0.734444716348, -0.124417337768, -0.708111449895, -0.399676812698, -0.165487765543, -1.52919474544, -0.743328414533, -0.826169397925, -0.621684486914, -1.02101828767, 0.507572292251, 1.64945264051, -1.16729493131, -1.59575805184, 1.22194630958, -0.324260225115, -2.70908723091, 0.419972356697, 0.199954966493, 1.51343480756, 0.0528252604798, -1.59926845777, 1.72143823853, -0.391567581633, 0.302380438723, 0.151857495879, -0.770407214622, 1.11355519113, 0.373448388224, -0.0993048929725, -2.01116150929, -0.953752431803, -0.53637958571]

----------------------------------------------------------------------
Ran 1 test in 0.076s

FAILED (failures=1)
% nosetests-3.4 pandas.tests.series.test_timeseries:TestSeriesTimeSeries.test_getitem_setitem_datetime_tz_dateutil
F
======================================================================
FAIL: test_getitem_setitem_datetime_tz_dateutil (pandas.tests.series.test_timeseries.TestSeriesTimeSeries)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/pandas/tests/series/test_timeseries.py", line 373, in test_getitem_setitem_datetime_tz_dateutil
    assert_series_equal(result, ts)
  File "/usr/local/lib/python3.4/site-packages/pandas/util/testing.py", line 1049, in assert_series_equal
    check_less_precise, obj='{0}'.format(obj))
  File "pandas/src/testing.pyx", line 58, in pandas._testing.assert_almost_equal (pandas/src/testing.c:3887)
  File "pandas/src/testing.pyx", line 147, in pandas._testing.assert_almost_equal (pandas/src/testing.c:2769)
  File "/usr/local/lib/python3.4/site-packages/pandas/util/testing.py", line 915, in raise_assert_detail
    raise AssertionError(msg)
AssertionError: Series are different

Series values are different (2.0 %)
[left]:  [-1.62055133384, -0.40032873599, -0.0413126236653, -0.0874632372333, -0.0874632372333, 0.963355896157, -1.14800978329, 0.900767884316, -0.311906151027, -0.86659183859, 0.103124666827, -1.05425628959, 0.151391743507, 2.37804326267, -0.565799316283, 0.106545790548, 0.270492212263, -0.234666171836, 1.94563993527, 0.772557437014, 1.00327635974, 1.64773195089, -1.39852655695, 2.63998681932, -1.04312074403, 0.439769938036, -1.37277863866, -0.0158894503064, -0.436093446088, -0.14146511313, -0.641742768338, 2.34834910935, 0.203726407935, 0.107095272346, 1.88232213003, -1.19930651532, 0.247541076124, -1.85409991944, 0.403116803679, 0.198896287287, 1.04642546617, -0.351747059523, -0.760612947304, 1.0257071291, 1.02611993308, -0.83529928137, -0.223900372029, 0.140186002284, -0.352805019677, 0.311596888265]
[right]: [-1.62055133384, -0.40032873599, -0.0413126236653, 1.69209510358, -0.0874632372333, 0.963355896157, -1.14800978329, 0.900767884316, -0.311906151027, -0.86659183859, 0.103124666827, -1.05425628959, 0.151391743507, 2.37804326267, -0.565799316283, 0.106545790548, 0.270492212263, -0.234666171836, 1.94563993527, 0.772557437014, 1.00327635974, 1.64773195089, -1.39852655695, 2.63998681932, -1.04312074403, 0.439769938036, -1.37277863866, -0.0158894503064, -0.436093446088, -0.14146511313, -0.641742768338, 2.34834910935, 0.203726407935, 0.107095272346, 1.88232213003, -1.19930651532, 0.247541076124, -1.85409991944, 0.403116803679, 0.198896287287, 1.04642546617, -0.351747059523, -0.760612947304, 1.0257071291, 1.02611993308, -0.83529928137, -0.223900372029, 0.140186002284, -0.352805019677, 0.311596888265]

----------------------------------------------------------------------
Ran 1 test in 0.075s

FAILED (failures=1)
```

In both cases it is only the fourth element that disagrees: -0.681093073082 vs. 0.328450105526 for py27; and -0.0874632372333 vs. 1.69209510358 for py34.

#### Expected Output

I expect the test to pass.

#### output of ``pd.show_versions()``

For py27:
```
INSTALLED VERSIONS
------------------
commit: None
python: 2.7.11.final.0
python-bits: 64
OS: FreeBSD
OS-release: 10.2-STABLE
machine: amd64
processor: amd64
byteorder: little
LC_ALL: None
LANG: None

pandas: 0.18.1
nose: 1.3.7
pip: 8.0.2
setuptools: 20.0
Cython: None
numpy: 1.11.0
scipy: 0.16.1
statsmodels: None
xarray: None
IPython: None
sphinx: None
patsy: None
dateutil: 2.5.0
pytz: 2016.4
blosc: None
bottleneck: 1.0.0
tables: 3.2.2
numexpr: 2.5.2
matplotlib: 1.5.0
openpyxl: 2.3.5
xlrd: 0.9.3
xlwt: 0.7.5
xlsxwriter: 0.8.5
lxml: 3.5.0
bs4: 4.4.1
html5lib: 0.9999999
httplib2: None
apiclient: None
sqlalchemy: 0.7.10
pymysql: None
psycopg2: None
jinja2: 2.8
boto: 2.39.0
pandas_datareader: None
```

For py34:
```
INSTALLED VERSIONS
------------------
commit: None
python: 3.4.4.final.0
python-bits: 64
OS: FreeBSD
OS-release: 10.2-STABLE
machine: amd64
processor: amd64
byteorder: little
LC_ALL: None
LANG: None

pandas: 0.18.1
nose: 1.3.7
pip: None
setuptools: 20.0
Cython: 0.23.5
numpy: 1.11.0
scipy: 0.16.1
statsmodels: None
xarray: None
IPython: None
sphinx: None
patsy: None
dateutil: 2.5.0
pytz: 2016.4
blosc: None
bottleneck: 1.0.0
tables: 3.2.2
numexpr: 2.5.2
matplotlib: None
openpyxl: 2.3.5
xlrd: 0.9.3
xlwt: None
xlsxwriter: 0.8.5
lxml: 3.5.0
bs4: 4.4.1
html5lib: 0.9999999
httplib2: None
apiclient: None
sqlalchemy: 0.7.10
pymysql: None
psycopg2: None
jinja2: 2.8
boto: 2.39.0
pandas_datareader: None
```

**Comment by jreback** [comment]
@neirbowj you would have to debug this and see why. This passes on all other systems. If you find the issue and want to submit a PR pls do so.

**Comment by neirbowj** [comment]
OK, thanks Jeff. Here are some clues to help my future self and anybody else who encounters this.

Ubuntu 15.04 installs a symlink from `/usr/share/zoneinfo/America/Chicago` to `../US/Central`
```
>>> from dateutil.tz import gettz
>>> gettz('US/Central')
tzfile('/usr/share/zoneinfo/US/Central')
>>> gettz('America/Chicago')
tzfile('/usr/share/zoneinfo/America/Chicago')
>>>
```

Mac OS X 10.10.5 (and MacPorts 2.3.4) uses hardlinks so that `/usr/share/zoneinfo/{America/Chicago,US/Central}` are the same file
```
>>> from dateutil.tz import gettz
>>> gettz('US/Central')
tzfile('/usr/share/zoneinfo/US/Central')
>>> gettz('America/Chicago')
tzfile('/usr/share/zoneinfo/America/Chicago')
>>>
```

FreeBSD 10.2-STABLE (r292840) doesn't install a file for "US/Central".
```
>>> from dateutil.tz import gettz
>>> gettz('US/Central')
>>> gettz('America/Chicago')
tzfile('/usr/share/zoneinfo/America/Chicago')
>>>
```

I should be able to modify the test to use "America/New_York" and "America/Chicago" instead of "US/Eastern" and "US/Central", but it still fails. I'll continue to dig.

**Comment by neirbowj** [comment]
Ah, just a typo: "America/Chagago". Test passes now. Look for a PR shortly.
