### ISSUE TITLE
ImportError: cannot import name 'hashtable'

### ISSUE THREAD

**Issue by klonuo** [pydata/pandas#13308]
I cloned this repo and tried to generate docs:

```pytb
D:\src\pandas\doc>python make.py html
[NbConvertApp] Converting notebook source/html-styling.ipynb to html
[NbConvertApp] Writing 620631 bytes to source\source/html-styling.html
Traceback (most recent call last):
  File "c:\python35\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python35\Scripts\jupyter-nbconvert.exe\__main__.py", line 9, in <module>
  File "c:\python35\lib\site-packages\jupyter_core\application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "c:\python35\lib\site-packages\traitlets\config\application.py", line 596, in launch_instance
    app.start()
  File "c:\python35\lib\site-packages\nbconvert\nbconvertapp.py", line 293, in start
    self.convert_notebooks()
  File "c:\python35\lib\site-packages\nbconvert\nbconvertapp.py", line 457, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "c:\python35\lib\site-packages\nbconvert\nbconvertapp.py", line 429, in convert_single_notebook
    write_results = self.write_single_notebook(output, resources)
  File "c:\python35\lib\site-packages\nbconvert\nbconvertapp.py", line 390, in write_single_notebook
    output, resources, notebook_name=notebook_name)
  File "c:\python35\lib\site-packages\nbconvert\writers\files.py", line 127, in write
    with io.open(dest, 'w', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'source\\source/html-styling.html'
Running Sphinx v1.4.1
Exception occurred while building, starting debugger:
Traceback (most recent call last):
  File "D:\src\pandas\pandas\__init__.py", line 25, in <module>
    from pandas import hashtable, tslib, lib
ImportError: cannot import name 'hashtable'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python35\lib\site-packages\sphinx\cmdline.py", line 243, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "c:\python35\lib\site-packages\sphinx\application.py", line 132, in __init__
    confoverrides or {}, self.tags)
  File "c:\python35\lib\site-packages\sphinx\config.py", line 289, in __init__
    execfile_(filename, config)
  File "c:\python35\lib\site-packages\sphinx\util\pycompat.py", line 130, in execfile_
    exec_(code, _globals)
  File "conf.py", line 16, in <module>
  File "D:\src\pandas\pandas\__init__.py", line 31, in <module>
    "the C extensions first.".format(module))
ImportError: C extension: 'hashtable' not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace --force' to build the C extensions first.
> d:\src\pandas\pandas\__init__.py(31)<module>()
-> "the C extensions first.".format(module))
(Pdb) q
'rm' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the path specified.
```

I noticed this exception `ImportError: cannot import name 'hashtable'` maybe 2 years ago, and as it's still here I thought to report it.

FYI, just in case, exception has nothing to do with nbconvert failure

**Comment by MaximilianR** [comment]
Did you run this? `ImportError: C extension: 'hashtable' not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace --force' to build the C extensions first`

**Comment by jreback** [comment]
you need to build and install pandas or use ``python setup.py develop``; then build the docs

**Comment by jreback** [comment]
http://pandas.pydata.org/pandas-docs/stable/contributing.html#how-to-build-the-pandas-documentation

**Comment by klonuo** [comment]
> Did you run this? ...

Ah, you are right, sorry...
