### ISSUE TITLE
Test failures on 32-bit Linux

### ISSUE THREAD

**Issue by matthew-brett** [pydata/pandas#13566]
Testing 32-bit Manylinux1 wheels for Pandas 0.18.1 gives the following errors:

```
======================================================================
ERROR: test_read_dta12 (pandas.io.tests.test_stata.TestStata)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/venv/local/lib/python2.7/site-packages/pandas/io/tests/test_stata.py", line 244, in test_read_dta12
    parsed_117 = self.read_dta(self.dta21_117)
  File "/venv/local/lib/python2.7/site-packages/pandas/io/tests/test_stata.py", line 86, in read_dta
    return read_stata(file, convert_dates=True)
  File "/venv/local/lib/python2.7/site-packages/pandas/io/stata.py", line 170, in read_stata
    return reader.read()
  File "/venv/local/lib/python2.7/site-packages/pandas/io/stata.py", line 1499, in read
    data = self._insert_strls(data)
  File "/venv/local/lib/python2.7/site-packages/pandas/io/stata.py", line 1595, in _insert_strls
    data.iloc[:, i] = [self.GSO[k] for k in data.iloc[:, i]]
KeyError: 4294967299
======================================================================
FAIL: test_isin (pandas.tseries.tests.test_timedeltas.TestTimedeltaIndex)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/venv/local/lib/python2.7/site-packages/pandas/tseries/tests/test_timedeltas.py", line 1681, in test_isin
    self.assertTrue(result.all())
AssertionError: False is not true
======================================================================
FAIL: test_isin (pandas.tseries.tests.test_timeseries.TestDatetimeIndex)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/venv/local/lib/python2.7/site-packages/pandas/tseries/tests/test_timeseries.py", line 3452, in test_isin
    self.assertTrue(result.all())
AssertionError: False is not true
======================================================================
FAIL: test_isin_with_i8 (pandas.tests.series.test_analytics.TestSeriesAnalytics)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/venv/local/lib/python2.7/site-packages/pandas/tests/series/test_analytics.py", line 1128, in test_isin_with_i8
    assert_series_equal(result, expected)
  File "/venv/local/lib/python2.7/site-packages/pandas/util/testing.py", line 1049, in assert_series_equal
    check_less_precise, obj='{0}'.format(obj))
  File "pandas/src/testing.pyx", line 58, in pandas._testing.assert_almost_equal (pandas/src/testing.c:3887)
  File "pandas/src/testing.pyx", line 147, in pandas._testing.assert_almost_equal (pandas/src/testing.c:2769)
  File "/venv/local/lib/python2.7/site-packages/pandas/util/testing.py", line 915, in raise_assert_detail
    raise AssertionError(msg)
AssertionError: Series are different
Series values are different (40.0 %)
[left]:  [False, False, False, False, False]
[right]: [True, True, False, False, False]
======================================================================
FAIL: test_basic (pandas.tests.test_algos.TestIsin)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/venv/local/lib/python2.7/site-packages/pandas/tests/test_algos.py", line 371, in test_basic
    tm.assert_numpy_array_equal(result, expected)
  File "/venv/local/lib/python2.7/site-packages/pandas/util/testing.py", line 957, in assert_numpy_array_equal
    raise_assert_detail(obj, msg, left, right)
  File "/venv/local/lib/python2.7/site-packages/pandas/util/testing.py", line 915, in raise_assert_detail
    raise AssertionError(msg)
AssertionError: numpy array are different
numpy array values are different (33.33333 %)
[left]:  [False, False, False]
[right]: [True, False, False]
======================================================================
FAIL: test_drop_level_nonunique_datetime (pandas.tests.test_multilevel.TestMultiLevel)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/venv/local/lib/python2.7/site-packages/pandas/tests/test_multilevel.py", line 1978, in test_drop_level_nonunique_datetime
    assert_frame_equal(result, expected)
  File "/venv/local/lib/python2.7/site-packages/pandas/util/testing.py", line 1119, in assert_frame_equal
    '{0}, {1}'.format(right.shape[0], right.index))
  File "/venv/local/lib/python2.7/site-packages/pandas/util/testing.py", line 915, in raise_assert_detail
    raise AssertionError(msg)
AssertionError: DataFrame are different
DataFrame shape (number of rows) are different
[left]:  5, MultiIndex(levels=[[2, 3, 4, 5], [2016-03-23 14:00:00, 2016-03-23 15:00:00, 2016-03-23 16:00:00, 2016-03-23 17:00:00]],
           labels=[[0, 1, 2, 2, 3], [0, 1, 2, 2, 3]],
           names=[u'id', u'tstamp'])
[right]: 3, MultiIndex(levels=[[2, 3, 4, 5], [2016-03-23 14:00:00, 2016-03-23 15:00:00, 2016-03-23 16:00:00, 2016-03-23 17:00:00]],
           labels=[[0, 1, 3], [0, 1, 3]],
           names=[u'id', u'tstamp'])
```

https://travis-ci.org/MacPython/pandas-wheels/jobs/142424407

**Comment by matthew-brett** [comment]
Failures only on Python 2.7 32-bit builds : https://travis-ci.org/MacPython/pandas-wheels/builds/142424402

**Comment by jreback** [comment]
yeah these are cases where we need to use platform_int to do things. I wonder how much 32-bit is used anymore. maybe we should drop support for 32-bit linux. (as we don't normally test this).

**Comment by jorisvandenbossche** [comment]
I still have a linux 32 bit (although more by mistake :-) and it's only because I will have a new laptop shortly that I didn't change it anymore). But in any case, I can take a look at those failures

Regarding supporting 32bit, are there some data points? 
Any ideas about usage? Untill shortly, eg Ubuntu did still provide 32bit downloads by default.
Are there other packages not supporting this anymore?
For example, `conda-forge` does not build packages for linux 32bit (but does for windows)

**Comment by jreback** [comment]
http://www.lfd.uci.edu/~gohlke/pythonlibs/#pandas

does build 32 bit for Windows

but no reason at all to support this going forward 
it's just extra testing
