### ISSUE TITLE
Failure to load Pandas in Docker  

### ISSUE THREAD

**Issue by mnfienen** [pydata/pandas#13893]
#### Code Sample, a copy-pastable example if possible
More difficult than that. Trying to import pandas when Running Python 3.5 in a Docker container, passing the --user option to 'docker run'. in this case, running Python 3.5 in a docker container using HTCondor
#### Expected Output
Should quietly load

#### Actual Output
Traceback (most recent call last):
  File "foo.py", line 1, in <module>
    import pandas
  File "/opt/conda/lib/python3.5/site-packages/pandas/__init__.py", line 39, in <module>
    from pandas.core.api import *
  File "/opt/conda/lib/python3.5/site-packages/pandas/core/api.py", line 10, in <module>
    from pandas.core.groupby import Grouper
  File "/opt/conda/lib/python3.5/site-packages/pandas/core/groupby.py", line 18, in <module>
    from pandas.core.frame import DataFrame
  File "/opt/conda/lib/python3.5/site-packages/pandas/core/frame.py", line 39, in <module>
    from pandas.core.series import Series
  File "/opt/conda/lib/python3.5/site-packages/pandas/core/series.py", line 2944, in <module>
    import pandas.tools.plotting as _gfx  # noqa
  File "/opt/conda/lib/python3.5/site-packages/pandas/tools/plotting.py", line 27, in <module>
    import pandas.tseries.converter as conv
  File "/opt/conda/lib/python3.5/site-packages/pandas/tseries/converter.py", line 7, in <module>
    import matplotlib.units as units
  File "/opt/conda/lib/python3.5/site-packages/matplotlib/__init__.py", line 1131, in <module>
    rcParams = rc_params()
  File "/opt/conda/lib/python3.5/site-packages/matplotlib/__init__.py", line 965, in rc_params
    fname = matplotlib_fname()
  File "/opt/conda/lib/python3.5/site-packages/matplotlib/__init__.py", line 794, in matplotlib_fname
    configdir = _get_configdir()
  File "/opt/conda/lib/python3.5/site-packages/matplotlib/__init__.py", line 649, in _get_configdir
    return _get_config_or_cache_dir(_get_xdg_config_dir())
  File "/opt/conda/lib/python3.5/site-packages/matplotlib/__init__.py", line 626, in _get_config_or_cache_dir
    return _create_tmp_config_dir()
  File "/opt/conda/lib/python3.5/site-packages/matplotlib/__init__.py", line 555, in _create_tmp_config_dir
    tempdir = os.path.join(tempdir, 'matplotlib-%s' % getpass.getuser())
  File "/opt/conda/lib/python3.5/getpass.py", line 170, in getuser
    return pwd.getpwuid(os.getuid())[0]
KeyError: 'getpwuid(): uid not found: 99'

#### output of ``pd.show_versions()``
INSTALLED VERSIONS
------------------
commit: None
python: 3.5.2.final.0
python-bits: 64
OS: Linux
OS-release: 3.10.0-327.22.2.el7.x86_64
machine: x86_64
processor: 
byteorder: little
LC_ALL: C.UTF-8
LANG: C.UTF-8

pandas: 0.18.1
nose: 1.3.7
pip: 8.1.2
setuptools: 23.0.0
Cython: 0.24
numpy: 1.11.1
scipy: 0.17.1
statsmodels: 0.6.1
xarray: None
IPython: 4.2.0
sphinx: 1.4.1
patsy: 0.4.1
dateutil: 2.5.3
pytz: 2016.4
blosc: None
bottleneck: 1.1.0
tables: 3.2.2
numexpr: 2.6.0
matplotlib: 1.5.1
openpyxl: 2.3.2
xlrd: 1.0.0
xlwt: 1.1.2
xlsxwriter: 0.9.2
lxml: 3.6.0
bs4: 4.4.1
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 1.0.13
pymysql: None
psycopg2: None
jinja2: 2.8
boto: 2.40.0
pandas_datareader: None
>>>

**Comment by jreback** [comment]
pls read our installation instructions [here](http://pandas.pydata.org/pandas-docs/stable/install.html)

you are mixing something up in the config for the docker creation. this is out of scope for pandas and you should consult the container builder.

**Comment by mnfienen** [comment]
OK. Using a Docker image created by Continuum so was hoping that it would be configured correctly

**Comment by jreback** [comment]
you should bring it up with them in that case

**Comment by mnfienen** [comment]
got it. seemed strange to me that pandas would need to know information about the user to run but I will give up and talk to Continuum then
