### ISSUE TITLE
TST: blosc>1.4.1 failing

### ISSUE THREAD

**Issue by jreback** [pydata/pandas#14143]
xref: https://github.com/pydata/pandas/pull/14142

seems this update just hit and failing 1 tests [here](https://travis-ci.org/pydata/pandas/jobs/157218567)
worked [here](https://travis-ci.org/pydata/pandas/jobs/157068571)

seems like a back-compat issue (new blosc not reading older blosc?)
```
======================================================================
ERROR: pandas.io.tests.test_packers.TestMsgpack.test_msgpack('0.17.1',)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/pandas/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/pydata/pandas/pandas/io/tests/test_packers.py", line 873, in read_msgpacks
    self.compare(vf, version)
  File "/home/travis/build/pydata/pandas/pandas/io/tests/test_packers.py", line 817, in compare
    data = read_msgpack(vf, encoding='latin-1')
  File "/home/travis/build/pydata/pandas/pandas/io/packers.py", line 202, in read_msgpack
    return read(fh)
  File "/home/travis/build/pydata/pandas/pandas/io/packers.py", line 187, in read
    l = list(unpack(fh, encoding=encoding, **kwargs))
  File "_unpacker.pyx", line 459, in pandas.msgpack._unpacker.Unpacker.__next__ (pandas/msgpack/_unpacker.cpp:4709)
  File "_unpacker.pyx", line 390, in pandas.msgpack._unpacker.Unpacker._unpack (pandas/msgpack/_unpacker.cpp:3843)
  File "/home/travis/build/pydata/pandas/pandas/io/packers.py", line 628, in decode
    blocks = [create_block(b) for b in obj[u'blocks']]
  File "/home/travis/build/pydata/pandas/pandas/io/packers.py", line 615, in create_block
    b[u'compress']), b[u'shape'])
  File "/home/travis/build/pydata/pandas/pandas/io/packers.py", line 329, in unconvert
    _move_into_mutable_buffer(decompress(values)),
  File "/home/travis/miniconda/envs/pandas/lib/python2.7/site-packages/blosc/toplevel.py", line 485, in decompress
    return _ext.decompress(bytesobj, as_bytearray)
error: Error -1 while decompressing data
----------------------------------------------------------------------
```

**Comment by jreback** [comment]
cc @kawochen 
cc @llllllllll
