### ISSUE TITLE
rename() take datetime.date as a function

### ISSUE THREAD

**Issue by fluency03** [pydata/pandas#14250]
I would like to rename a pd.Series but got two results on two different platforms.

For example, if I have a pd.Series as `a` and a datetime.date as `one_date`, and I do:

    a.rename(one_date)

On my own laptop (Window 7, Python 2.7), I got no error.

But when I do this on a server (Linux, Python 2.7), I got an error: 

Traceback (most recent call last):
  File "as.py", line 626, in <module>
    run_batch(sys.argv[1:])
  File "as.py", line 549, in run_batch
    analyzer.analyze_batch(one_user, batch_index_user, user_index)
  File "as.py", line 467, in analyze_batch
    clicks_one_date)
  File "as.py", line 434, in analyze_one_date_batch
    return counts_on_date.rename(one_date)
  File "/home/xxx/anaconda2/anaconda/lib/python2.7/site-packages/pandas/core/series.py", line 2264, in rename
    return super(Series, self).rename(index=index, **kwargs)
  File "/home/xxx/anaconda2/anaconda/lib/python2.7/site-packages/pandas/core/generic.py", line 606, in rename
    result._data = result._data.rename_axis(f, axis=baxis, copy=copy)
  File "/home/xxx/anaconda2/anaconda/lib/python2.7/site-packages/pandas/core/internals.py", line 2588, in rename_axis
    obj.set_axis(axis, _transform_index(self.axes[axis], mapper))
  File "/home/xxx/anaconda2/anaconda/lib/python2.7/site-packages/pandas/core/internals.py", line 4391, in _transform_index
    items = [func(x) for x in index]
TypeError: 'datetime.date' object is not callable

---

It seems like the method `rename` take the `one_date` as a function instead of a scalar value. Then it tried to call the `datetime.date` as a function but it is not callable.

Anyone has some idea about how to deal with it?

Thanks.

**Comment by fluency03** [comment]
@TomAugspurger Thanks. I think this should be the reason. I will check the Pandas version on the server. If it is the old version, I will solve the problem and come back for closing this issue.

**Comment by fluency03** [comment]
I have check the version of pandas on both server and my local laptop. @TomAugspurger is correct. 

On the laptop, the pandas version is 0.18.1. On the server, it is 0.17.0. According to [this](http://pandas.pydata.org/pandas-docs/version/0.18.0/whatsnew.html#changes-to-rename) pandas 0.18.0 documentation, method `rename` was changed to be able to take the scalar input.
