### ISSUE TITLE
TST: 3.5 c-locale

### ISSUE THREAD

**Issue by jreback** [pydata/pandas#14275]
https://travis-ci.org/pydata/pandas/jobs/161159736

xref #14114, #12337
 
```
======================================================================
ERROR: test_to_latex_filename (pandas.tests.formats.test_format.TestDataFrameFormatting)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/pydata/pandas/pandas/tests/formats/test_format.py", line 2825, in test_to_latex_filename
    df.to_latex(path)
  File "/home/travis/build/pydata/pandas/pandas/core/frame.py", line 1661, in to_latex
    encoding=encoding)
  File "/home/travis/build/pydata/pandas/pandas/formats/format.py", line 662, in to_latex
    latex_renderer.write_result(f)
  File "/home/travis/build/pydata/pandas/pandas/formats/format.py", line 906, in write_result
    buf.write(' & '.join(crow))
UnicodeEncodeError: 'ascii' codec can't encode character '\xdf' in position 7: ordinal not in range(128)
----------------------------------------------------------------------
Ran 10273 tests in 375.734s
```

cc @nbonnotte

**Comment by jreback** [comment]
cc @nbonnotte
