### ISSUE TITLE
Travis pip install finds 0.19rc1 which fails

### ISSUE THREAD

**Issue by michaelaye** [pydata/pandas#14325]
#### A small, complete example of the issue

```python
# Your code here

# This is what I have in my project's setup.py
 install_requires=['pandas']
```
and my install command is the usual `python setup.py install`

#### Expected Output
pip installs an official release of pandas

#### Actual Output
```bash
Processing dependencies for pyciss==0.5.2
Searching for pandas
Reading https://pypi.python.org/simple/pandas/
Downloading https://pypi.python.org/packages/d5/fc/8e1ba6427ab71e3e8f84b04db8800c0ea3a9a6f84cf9cc5ba1256b619a82/pandas-0.19.0rc1.zip#md5=1063ac85410a2f6ed70195b16f0e36cb
Best match: pandas 0.19.0rc1
Processing pandas-0.19.0rc1.zip
Writing /tmp/easy_install-oatji_7q/pandas-0.19.0rc1/setup.cfg
Running pandas-0.19.0rc1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-oatji_7q/pandas-0.19.0rc1/egg-dist-tmp-hpr8nxvu
package init file 'pandas/io/tests/sas/__init__.py' not found (or not a regular file)
warning: no files found matching 'README.rst'
no previously-included directories found matching 'doc/build'
warning: no directories found matching 'examples'
warning: no previously-included files matching '*.so' found anywhere in distribution
warning: no previously-included files matching '*.pyd' found anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*~' found anywhere in distribution
warning: no previously-included files matching '#*' found anywhere in distribution
warning: no previously-included files matching '.git*' found anywhere in distribution
warning: no previously-included files matching '.DS_Store' found anywhere in distribution
warning: no previously-included files matching '*.png' found anywhere in distribution
package init file 'pandas/io/tests/sas/__init__.py' not found (or not a regular file)
package init file 'pandas/io/tests/sas/__init__.py' not found (or not a regular file)
UPDATING build/lib.linux-x86_64-3.5/pandas/_version.py
set build/lib.linux-x86_64-3.5/pandas/_version.py to '0.19.0rc1'
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/test-environment/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/setuptools/sandbox.py", line 156, in save_modules
  File "/home/travis/miniconda/envs/test-environment/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/setuptools/sandbox.py", line 197, in setup_context
  File "/home/travis/miniconda/envs/test-environment/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/setuptools/sandbox.py", line 246, in run_setup
  File "/home/travis/miniconda/envs/test-environment/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/setuptools/sandbox.py", line 276, in run
  File "/home/travis/miniconda/envs/test-environment/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/setuptools/sandbox.py", line 245, in runner
  File "/home/travis/miniconda/envs/test-environment/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/setuptools/sandbox.py", line 47, in _execfile
  File "/tmp/easy_install-oatji_7q/pandas-0.19.0rc1/setup.py", line 677, in <module>
  File "/home/travis/miniconda/envs/test-environment/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/travis/miniconda/envs/test-environment/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/travis/miniconda/envs/test-environment/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/travis/miniconda/envs/test-environment/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/setuptools/command/bdist_egg.py", line 161, in run
  File "/home/travis/miniconda/envs/test-environment/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/setuptools/command/bdist_egg.py", line 147, in call_command
  File "/home/travis/miniconda/envs/test-environment/lib/python3.5/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/travis/miniconda/envs/test-environment/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/travis/miniconda/envs/test-environment/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/setuptools/command/install_lib.py", line 11, in run
  File "/home/travis/miniconda/envs/test-environment/lib/python3.5/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/home/travis/miniconda/envs/test-environment/lib/python3.5/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/travis/miniconda/envs/test-environment/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/travis/miniconda/envs/test-environment/lib/python3.5/distutils/command/build_ext.py", line 338, in run
    self.build_extensions()
  File "/tmp/easy_install-oatji_7q/pandas-0.19.0rc1/setup.py", line 368, in build_extensions
  File "/tmp/easy_install-oatji_7q/pandas-0.19.0rc1/setup.py", line 140, in build_extensions
NameError: name 'tempita' is not defined
```

**Comment by TomAugspurger** [comment]
Can you link to your travis.yml file? Presumably it's being called with a `--pre` flag.

**Comment by jreback** [comment]
this is fixed in 0.19.0  (releasing shortly) in any event: https://github.com/pydata/pandas/commit/461e0e9fba67b1f5cbe6ac5bd1db0272042777ee

**Comment by michaelaye** [comment]
here's my travis.yml, don't think there's a `--pre` in there. Which means the RC should not have been picked up, right?
https://github.com/michaelaye/pyciss/blob/master/.travis.yml

**Comment by chris-b1** [comment]
Apparently using `setup_requires` in a `setup.py` uses `easy_install` instead of `pip` - you probably instead want to use `install_requires`.

**Comment by michaelaye** [comment]
oh, wow. thanks a bunch! distribution never gets boring..

**Comment by jorisvandenbossche** [comment]
That's a gotcha! 
OK, closing then.
