### ISSUE TITLE
ExcelFile parse of empty sheet fails with "IndexError: list index out of range"

### ISSUE THREAD

**Issue by myourshaw** [pydata/pandas#6403]
Using pandas 0.13.1 on OS X Mavericks to parse a blank Excel spreadsheet causes "IndexError: list index out of range". Apparently the default header=0 in ```_parse_excel``` causes the execution of ```_trim_excel_header(data[header])```. Perhaps when nrows==0 this should not be executed.

```python
import pandas as pd
xl_file = pd.ExcelFile('blank.xlsx')
xl_file.parse('Sheet1') #Sheet1 has no data
```

STDERR:

```
Traceback (most recent call last):
  File "/Users/myourshaw/lab/pypeline/python2/excel_example.py", line 10, in <module>
    xl_file.parse('Sheet1')
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pandas/io/excel.py", line 208, in parse
    **kwds)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pandas/io/excel.py", line 291, in _parse_excel
    data[header] = _trim_excel_header(data[header])
IndexError: list index out of range
```

**Comment by jetheurer** [comment]
I'm also having trouble with this on Windows 7

```
IndexError                                Traceback (most recent call last)
<ipython-input-10-cff728300bb3> in <module>()
     22     if not len(power):
     23         print 'error - no data: %s'%installationid, ' only %s days'
---> 24         writer.save()
     25         continue
     26     if not 'Production' in power.columns:

C:\Anaconda\lib\site-packages\pandas\io\excel.pyc in save(self)
   1100         Save workbook to disk.
   1101         """
-> 1102         return self.book.save(self.path)
   1103 
   1104     def write_cells(self, cells, sheet_name=None, startrow=0, startcol=0):

C:\Anaconda\lib\site-packages\xlwt\Workbook.pyc in save(self, filename)
    660 
    661         doc = CompoundDoc.XlsDoc()
--> 662         doc.save(filename, self.get_biff_data())
    663 
    664 

C:\Anaconda\lib\site-packages\xlwt\Workbook.pyc in get_biff_data(self)
    641         eof = self.__eof_rec()
    642 
--> 643         self.__worksheets[self.__active_sheet].selected = True
    644         sheets = ''
    645         sheet_biff_lens = []

IndexError: list index out of range
```
Is there a solution?
