### ISSUE TITLE
IndexError when doing groupby idxmax on large series 

### ISSUE THREAD

**Issue by amcpherson** [pydata/pandas#8127]
The following code works when `sz = 1000000`, but produces IndexError when `sz=10000000`.  Seems similar to #5727.

    df = pd.DataFrame({'A':np.random.randint(0, sz, sz),
    				   'B':np.random.randint(0, 2, sz),
    				   'C':np.random.randn(sz)})
    df.set_index(['A', 'B'])\
      .groupby(level=[0, 1])['C'].sum()\
      .groupby(level=[0]).idxmax()

Exception:

    Traceback (most recent call last):
      File "<stdin>", line 3, in <module>
      File "/home/amcpherson/scratch/anaconda/lib/python2.7/site-packages/pandas/core/groupby.py", line 482, in __getattr__
        if attr in self.obj:
      File "/home/amcpherson/scratch/anaconda/lib/python2.7/site-packages/pandas/core/generic.py", line 682, in __contains__
        return key in self._info_axis
      File "/home/amcpherson/scratch/anaconda/lib/python2.7/site-packages/pandas/core/index.py", line 2908, in __contains__
        self.get_loc(key)
      File "/home/amcpherson/scratch/anaconda/lib/python2.7/site-packages/pandas/core/index.py", line 3411, in get_loc
        return self._get_level_indexer(key, level=0)
      File "/home/amcpherson/scratch/anaconda/lib/python2.7/site-packages/pandas/core/index.py", line 3585, in _get_level_indexer
        loc = level_index.get_loc(key)
      File "/home/amcpherson/scratch/anaconda/lib/python2.7/site-packages/pandas/core/index.py", line 1181, in get_loc
        return self._engine.get_loc(_values_from_object(key))
      File "index.pyx", line 129, in pandas.index.IndexEngine.get_loc (pandas/index.c:3354)
      File "index.pyx", line 138, in pandas.index.IndexEngine.get_loc (pandas/index.c:3107)
      File "util.pxd", line 40, in util.get_value_at (pandas/index.c:13413)
    IndexError: index out of bounds

Version information:

	>>> pd.show_versions()
    
	INSTALLED VERSIONS
	------------------
	commit: None
	python: 2.7.6.final.0
	python-bits: 64
	OS: Linux
	OS-release: 2.6.18-194.el5
	machine: x86_64
	processor: x86_64
	byteorder: little
	LC_ALL: None
	LANG: en_US.UTF-8
    
	pandas: 0.14.1
	nose: 1.3.0
	Cython: 0.20.1
	numpy: 1.8.2
	scipy: 0.13.3
	statsmodels: 0.5.0
	IPython: 1.1.0
	sphinx: 1.2.1
	patsy: 0.2.1
	scikits.timeseries: None
	dateutil: 2.2
	pytz: 2014.4
	bottleneck: None
	tables: 3.1.0
	numexpr: 2.3.1
	matplotlib: 1.3.1
	openpyxl: 1.8.2
	xlrd: 0.9.2
	xlwt: 0.7.5
	xlsxwriter: 0.5.2
	lxml: 3.3.1
	bs4: 4.3.1
	html5lib: None
	httplib2: None
	apiclient: None
	rpy2: None
	sqlalchemy: 0.9.2
	pymysql: None
	psycopg2: None

**Comment by jreback** [comment]
closing as stale. pls reopen if still an issue.

**Comment by amcpherson** [comment]
Verified as fixed on master, closed.
