### ISSUE TITLE
python make.py html failure

### ISSUE THREAD

**Issue by nilswagner** [pydata/pandas#8878]
nils@linux-5fmr:~/git/pandas/doc> python make.py html
Traceback (most recent call last):
  File "/home/nils/local/bin/sphinx-build", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2829, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 706, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 604, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: Sphinx==1.3b2dev-20141122
Building HTML failed.

nils@linux-5fmr:~/git/pandas/doc> sphinx-build --version
Sphinx (sphinx-build) 1.3b2

**Comment by jorisvandenbossche** [comment]
I am closing this as we have not enough information to help or reproduce. @nilswagner If you still have this problem, feel free to re-open and provide more info!
