### ISSUE TITLE
"certificate verify failed" errors on macports

### ISSUE THREAD

**Issue by matthew-brett** [pydata/pandas#9290]
Sorry for this sketch of a bug report, but I am seeing these errors with Macports Python 2.7 and the current pandas 0.15.2 release:

https://travis-ci.org/MacPython/scipy-stack-osx-testing/jobs/47389975#L757

Here's an example error:

```
======================================================================
ERROR: test_url (pandas.io.tests.test_json.test_pandas.TestPandasContainer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pandas/util/testing.py", line 1441, in wrapper
    return t(*args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pandas/io/tests/test_json/test_pandas.py", line 599, in test_url
    result = read_json(url, convert_dates=True)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pandas/io/json.py", line 174, in read_json
    filepath_or_buffer, _ = get_filepath_or_buffer(path_or_buf)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pandas/io/common.py", line 118, in get_filepath_or_buffer
    req = _urlopen(str(filepath_or_buffer))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1240, in https_open
    context=self._context)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)>
```

No such errors for Python 3:

https://travis-ci.org/MacPython/scipy-stack-osx-testing/jobs/47389977

Is this a bug in Macports Python or Pandas?

**Comment by TomAugspurger** [comment]
Could also be an ssl error, or a problem w/ how it was linked to python.

FWIW, I've had way more luck with homebrew vs. Macports.

**Comment by shoyer** [comment]
My guess is that this is *somehow* related to updated SSL module in Python 2.7.9: https://www.python.org/dev/peps/pep-0466/

And my guess is that it's a Macports Python bug, given that all pandas does here is calling a standard library function. Try this to see if you can reproduce it:
```python
from urllib2 import urlopen
urlopen('https://api.github.com/repos/pydata/pandas/issues?per_page=5').read()
```

**Comment by matthew-brett** [comment]
Thanks for making it clearer.  Yes, indeed, I get the same error from the urlopen command above.

I suspect this is https://trac.macports.org/ticket/46596 - currently waiting for a fix.
