### ISSUE TITLE
Error: “pandas.hashtable.PyObjectHashTable.get_item”

### ISSUE THREAD

**Issue by sergeyf** [pydata/pandas#9410]
I'm seeing some odd behavior from Pandas 0.15.2 on Python 3.4.2.

First, I import the data with no issues:

import pandas as pd

hourly = pd.read_csv("fremont_bridge_data.csv", index_col='Date', parse_dates=True)
weekly = hourly.resample('w','sum')

But when trying to access, I run into some odd behavior. This works fine:

In[289]:   weekly['2013-12']
Out[289]: 
            northbound  southbound  total
Date                                     
2013-12-01        5053        5480  10533
2013-12-08        5432        5836  11268
2013-12-15        5381        5760  11141
2013-12-22        5182        5455  10637
2013-12-29        3118        3567   6685

But this fails:

In[290]:   weekly['2013-12-29']

Traceback (most recent call last):

  File "<ipython-input-290-96e181f8ff0a>", line 1, in <module>
    weekly['2013-12-29']

  File "C:\Anaconda\envs\py34\lib\site-packages\pandas\core\frame.py", line 1780, in __getitem__
    return self._getitem_column(key)

  File "C:\Anaconda\envs\py34\lib\site-packages\pandas\core\frame.py", line 1787, in _getitem_column
    return self._get_item_cache(key)

  File "C:\Anaconda\envs\py34\lib\site-packages\pandas\core\generic.py", line 1068, in _get_item_cache
    values = self._data.get(item)

  File "C:\Anaconda\envs\py34\lib\site-packages\pandas\core\internals.py", line 2849, in get
    loc = self.items.get_loc(item)

  File "C:\Anaconda\envs\py34\lib\site-packages\pandas\core\index.py", line 1402, in get_loc
    return self._engine.get_loc(_values_from_object(key))

  File "pandas\index.pyx", line 134, in pandas.index.IndexEngine.get_loc (pandas\index.c:3807)

  File "pandas\index.pyx", line 154, in pandas.index.IndexEngine.get_loc (pandas\index.c:3687)

  File "pandas\hashtable.pyx", line 696, in pandas.hashtable.PyObjectHashTable.get_item (pandas\hashtable.c:12310)

  File "pandas\hashtable.pyx", line 704, in pandas.hashtable.PyObjectHashTable.get_item (pandas\hashtable.c:12261)

KeyError: '2013-12-29'

Any ideas? This also fails: weekly[weekly.index[0]], and seems like it shouldn't.

Ditto with .loc. weekly.loc['2012-12-30'] works fine, but weekly.loc[['2012-12-30','2012-12-30']] fails!

The data is here: https://github.com/sergeyf/Python_data_science_class/blob/master/code/data/fremont_bridge_data.csv

Thank you.

**Comment by jreback** [comment]
see docs here: http://pandas.pydata.org/pandas-docs/stable/timeseries.html#datetimeindex-partial-string-indexing

partial string indexing is for slices only 
otherwise it tried column selection

**Comment by sergeyf** [comment]
Ah, thanks, and sorry for the bother!
