### ISSUE TITLE
Support for tables with unlimited columns in HDF

### ISSUE THREAD

**Issue by Chris7** [pydata/pandas#9590]
I wrote a small class that will allow users to utilize HDF tables with significantly more columns than the ~2000 limit currently imposed. I work with mass spec data, and have matrices of ~20,000 x 20,000 x sample_number to deal with so I need things to be written on disk, and compressed.

I'm asking if this is something that would be appreciated to be cleaned up and put in as a PR. It's currently just addressing my needs as they arise, but I could extend and optimize it if there's interest. Alternatively, if I'm reinventing a wheel that already exists in pandas, I'd love to know that as well.

Here's the code for the interested

```python
class WideTable(object):
    """
    Breaks up a massive table into individual chunks and stores these chunks as separate tables.
    Extends the select and append method to be pandas-like and handle this indexing to mimic a single
    DataFrame
    """
    def __init__(self, store, chunk_size=None, min_itemsize=255):
        self.store = store
        self.index_name = '_store_index'
        self.chunk_size_name = '_chunk_size'
        self.index_itemsize = min_itemsize
        try:
            self.store_index = self.store.select(self.index_name)
        except KeyError:
            self.store_index = pd.DataFrame(columns=['chunk'])
            self.store.put(self.index_name, self.store_index)
        finally:
            self.tables = [i[0] for i in self.store.iteritems()]
        try:
            # stored as a series
            self.chunk_size = self.store.select(self.chunk_size_name)
        except KeyError:
            self.chunk_size = pd.Series(chunk_size if chunk_size is not None else 100)
            self.store.append(self.chunk_size_name, self.chunk_size)
        self.chunk_size = self.chunk_size[0]
        
    def get_chunk_name(self, name, chunk):
        return '_{0}_{1}'.format(name, chunk)
        
    def append(self, name, data, column=0):
        # get the existing chunks from the data and insert them to those blocks
        chunks = self.store_index['chunk']
        existing_map = chunks[data.columns]
        new = existing_map[existing_map.isnull()] # Series of new columns
        existing = existing_map.dropna().to_dict() # dict of {'column': 'chunk'}, we want {'chunk': columns set}
        existing_rev = {}
        for key, value in existing.iteritems():
            try:
                existing_rev[value].append(key)
            except KeyError:
                existing_rev[value] = [key]
        
        # update existing entries
        columns_added = []
        for chunk_index, chunk_columns in existing_rev.iteritems():
            print self.get_chunk_name(name, chunk_index), chunk_columns
            self.store.append(self.get_chunk_name(name, chunk_index), data.loc[:,chunk_columns])
            columns_added.extend(chunk_columns)
        
        new_cols = list(set(data.columns)-set(columns_added))
        if new_cols:
            data2 = data[new_cols]
            current_chunk = chunks.astype('int').max()
            if pd.isnull(current_chunk):
                current_chunk = 0
            space_taken = len(chunks.where(chunks == str(current_chunk)).dropna())
            if space_taken >= self.chunk_size:
                current_chunk += 1
                end = self.chunk_size
            else:
                end = self.chunk_size-space_taken
            if end > len(new_cols):
                end = len(new_cols)
            start = 0
            while start < len(new_cols):
                chunk_name = self.get_chunk_name(name, current_chunk)
                td = data2.iloc[:,start:end]
                self.store.append(chunk_name, td)
                for col_name in td.columns:
                    self.store_index.loc[col_name,'chunk'] = str(current_chunk)
                self.tables.append(chunk_name)
                start = end
                end += self.chunk_size
                if end > len(new_cols):
                    end = len(new_cols)
                current_chunk += 1
            self.store.put(self.index_name, self.store_index)
        
    def get_matching_tables(self, name):
        return [i for i in self.tables if i.startswith('/_{0}_'.format(name))]
        
    def select(self, name, **kwargs):
        t = pd.DataFrame()
        for i in self.get_matching_tables(name):
            values = self.store.select(i,**kwargs)
            if values.empty:
                continue
            t = t.join(values, how='outer')
        return t
```

Basic usage:

```python
import pandas as pd
import numpy as np
# chunk size is how many columns you want per sub-table and is only required for new tables
wt = WideTable(pd.HDFStore('wide_table.h5', complevel=9, complib='blosc'), chunk_size=3)
df = pd.DataFrame(np.random.randn(8, 10), index=range(8), columns=[chr(i) for i in xrange(70,70+10)])
wt.append('test_table', df)

# show that chunk size is optional
wt = WideTable(pd.HDFStore('wide_table.h5', complevel=9, complib='blosc'))
print wt.chunk_size
# select data
print wt.select('test_table', where='columns==J')
# across tables
print wt.select('test_table', where='columns==[N,I,H]')
print wt.select('test_table', where='columns==[F,J,O]')

```

**Comment by jreback** [comment]
so you are basically emulating a column store with a 'convention'. see #4454 

I think we would definitly support this format, e.g. ``format='column'`` or whatever directly in HDFStore. 
Alternateively this is what ``bcolz`` does in effect. BUT I think having it accesible via ``HDFStore`` would be great!.

Would welcome a PR with tests for this!

**Comment by Chris7** [comment]
I'll have a PR up with some tests in a week or so. I'm using it locally for a bit on my data to see if any more bugs crop up.

Advice on the following would be appreciated if possible:
The natural attribute access (table names with a . in them) -- does this need to be supported in pandas? A work around is to have a table_name.replace('.', '_') or something of that sort. But if panda's doesn't use attribute access anyways I'd rather not change the name and let the warning propagate to the user.

**Comment by Chris7** [comment]
Initial test of this can be found here:

https://github.com/Chris7/pandas/commit/183d1dd1e4e153c87fb860a9d37e72b9a65b94e0

I'd appreciate any feedback on my approach.

**Comment by jreback** [comment]
- you need to subclass ``AppendableFrameTable`` to support this format generically
- all of the data needs to exist under the current node, not in the root of the file (so you could potentially have different / multiple of 'column'/'table' stores)
- repr needs to be tested for column stores
- need to see if ``data_columns`` is necessary for this type (e.g. you are effectively storing collections of columns), but they could in theory be stored exactly like tables
- need tests for multi dtypes
- need tests for add / delete columns, adding duplicate columns

**Comment by jreback** [comment]
hows this coming?

**Comment by chrismit** [comment]
Hey,

Work got a bit crazy for the past few weeks -- and I ended up circumventing the need for this structure using an alternative approach. Though I'm still interesting in tackling this issue since pandas really scratches a lot of itches I have quite nicely.

Thanks for the feedback, I'm going to implement it with your guidelines when I get some more of that elusive free time. I should have a new PR with a more generic design pattern this week.

**Comment by Chris7** [comment]
Hey,

Work got a bit crazy for the past few weeks -- and I ended up circumventing the need for this structure using an alternative approach. Though I'm still interesting in tackling this issue since pandas really scratches a lot of itches I have quite nicely.

Thanks for the feedback, I'm going to implement it with your guidelines when I get some more of that elusive free time. I should have a new PR with a more generic design pattern this week.

**Comment by jreback** [comment]
awesome! lmk

**Comment by chrismit** [comment]
Just a heads up, I'm trying to finish my dissertation at the moment but I still am interested in finishing this bit after that.

**Comment by hnykda** [comment]
This looks great! Thank you for this.

Could we also possibly enhance the current error when trying to save wide tables? This is what you get for:
```python
import pandas as pd
df = pd.DataFrame(columns=['Some Teribly Long String With Many Characters' + str(i) for i in range(10000)])
df.loc[0] = 3
df.to_hdf('test.hdf', 'main', format='table')
```

## Error
```python
---------------------------------------------------------------------------
HDF5ExtError                              Traceback (most recent call last)
<ipython-input-7-f85f8d86c365> in <module>()
----> 1 df.to_hdf('test.hdf', 'main', format='table')

/home/dan/.local/opt/miniconda3/envs/mathbs/lib/python3.5/site-packages/pandas/core/generic.py in to_hdf(self, path_or_buf, key, **kwargs)
   1094 
   1095         from pandas.io import pytables
-> 1096         return pytables.to_hdf(path_or_buf, key, self, **kwargs)
   1097 
   1098     def to_msgpack(self, path_or_buf=None, encoding='utf-8', **kwargs):

/home/dan/.local/opt/miniconda3/envs/mathbs/lib/python3.5/site-packages/pandas/io/pytables.py in to_hdf(path_or_buf, key, value, mode, complevel, complib, append, **kwargs)
    258         with HDFStore(path_or_buf, mode=mode, complevel=complevel,
    259                       complib=complib) as store:
--> 260             f(store)
    261     else:
    262         f(path_or_buf)

/home/dan/.local/opt/miniconda3/envs/mathbs/lib/python3.5/site-packages/pandas/io/pytables.py in <lambda>(store)
    253         f = lambda store: store.append(key, value, **kwargs)
    254     else:
--> 255         f = lambda store: store.put(key, value, **kwargs)
    256 
    257     if isinstance(path_or_buf, string_types):

/home/dan/.local/opt/miniconda3/envs/mathbs/lib/python3.5/site-packages/pandas/io/pytables.py in put(self, key, value, format, append, **kwargs)
    824             format = get_option("io.hdf.default_format") or 'fixed'
    825         kwargs = self._validate_format(format, kwargs)
--> 826         self._write_to_group(key, value, append=append, **kwargs)
    827 
    828     def remove(self, key, where=None, start=None, stop=None):

/home/dan/.local/opt/miniconda3/envs/mathbs/lib/python3.5/site-packages/pandas/io/pytables.py in _write_to_group(self, key, value, format, index, append, complib, encoding, **kwargs)
   1262 
   1263         # write the object
-> 1264         s.write(obj=value, append=append, complib=complib, **kwargs)
   1265 
   1266         if s.is_table and index:

/home/dan/.local/opt/miniconda3/envs/mathbs/lib/python3.5/site-packages/pandas/io/pytables.py in write(self, obj, axes, append, complib, complevel, fletcher32, min_itemsize, chunksize, expectedrows, dropna, **kwargs)
   3799 
   3800             # set the table attributes
-> 3801             self.set_attrs()
   3802 
   3803             # create the table

/home/dan/.local/opt/miniconda3/envs/mathbs/lib/python3.5/site-packages/pandas/io/pytables.py in set_attrs(self)
   3050         self.attrs.index_cols = self.index_cols()
   3051         self.attrs.values_cols = self.values_cols()
-> 3052         self.attrs.non_index_axes = self.non_index_axes
   3053         self.attrs.data_columns = self.data_columns
   3054         self.attrs.nan_rep = self.nan_rep

/home/dan/.local/opt/miniconda3/envs/mathbs/lib/python3.5/site-packages/tables/attributeset.py in __setattr__(self, name, value)
    459 
    460         # Set the attribute.
--> 461         self._g__setattr(name, value)
    462 
    463         # Log new attribute addition.

/home/dan/.local/opt/miniconda3/envs/mathbs/lib/python3.5/site-packages/tables/attributeset.py in _g__setattr(self, name, value)
    401             value = stvalue[()]
    402 
--> 403         self._g_setattr(self._v_node, name, stvalue)
    404 
    405         # New attribute or value. Introduce it into the local

tables/hdf5extension.pyx in tables.hdf5extension.AttributeSet._g_setattr (tables/hdf5extension.c:7824)()

HDF5ExtError: HDF5 error back trace

  File "H5A.c", line 259, in H5Acreate2
    unable to create attribute
  File "H5Aint.c", line 275, in H5A_create
    unable to create attribute in object header
  File "H5Oattribute.c", line 347, in H5O_attr_create
    unable to create new attribute in header
  File "H5Omessage.c", line 224, in H5O_msg_append_real
    unable to create new message
  File "H5Omessage.c", line 1945, in H5O_msg_alloc
    unable to allocate space for message
  File "H5Oalloc.c", line 1142, in H5O_alloc
    object header message is too large

End of HDF5 error back trace

Can't set attribute 'non_index_axes' in node:
 /main (Group) ''.

```

**Comment by jreback** [comment]
@hnykda this is just a proposal. would take a pull-request to complete this.

**Comment by shoyer** [comment]
FWIW, very wide dataframes is usually is a sign that you're slightly abusing the dataframe data model -- you'll be happier if you can stick to [tidy data](http://vita.had.co.nz/papers/tidy-data.pdf). If your data is intrinsically multi-dimensional, you might be happier trying [xarray](http://xarray.pydata.org/), which inter-operates with pandas and can efficiently write multi-dimensional data to netCDF/HDF5.

**Comment by hnykda** [comment]
@shoyer: We use pandas in our data processing pipeline. My data are about suveys, which mostly have binary answers (yes or no). Furthermore, because some companies we cooperate with demands to have data fully one-hot-encoded. Because of this (and legacy reasons, e.g. loading it to platform, which needs all the columns), we have to store datasets usually about 50k rows and up to 10k columns. I don't know how anything from _tidy data_  can help me here, unfortunately. And data are strictly flat, so `xarray` won't help much either.

**Comment by jbrockmendel** [comment]
pandas support for HDF is in bugfix-only mode, closing as no-action.
