### ISSUE TITLE
Problems reading an specific attribute with a dataframe

### ISSUE THREAD

**Issue by cypherpunker** [pydata/pandas#9860]
I have a pretty large file like this:

SynsetTerms,PosScore,NegScore
a prueba de,0.208333333333,0.0833333333333
a reacción,0,0.0625
a salvo,0.1875,0.0625
a través de,0.1875,0.0
a ultranza,0.125,0.0

I would like to place in a list all the SynsetTerms that has PosScore > 0 . I tried this:

pos_score = [df[df.NegScore > 0].SynsetTerms.unique()]

But I get:

Traceback (most recent call last):
  File "file.py", line 31, in <module>
    pos_score = [df[df.NegScore > 0].SynsetTerms.unique()]
  File "/usr/local/lib/python2.7/site-packages/pandas/core/generic.py", line 1978, in __getattr__
    (type(self).__name__, name))
AttributeError: 'DataFrame' object has no attribute 'SynsetTerms'

I dont get what is happening since the object SynsetTerms is in the .csv file do you guys this issue is about a bug in  0.16.0 version?.

**Comment by shoyer** [comment]
Can you print `df.columns` for us?

**Comment by cypherpunker** [comment]
Thanks for the feed. When I print the columns I get this:
`Index([u'SynsetTerms', u'PosScore', u'NegScore'], dtype='object')`

**Comment by sinhrks** [comment]
Unable to reproduce. Maybe you can attach all the code including data preparation, and ``pd.show_version()``?

```
# -*- coding: utf-8 -*-
import pandas as pd
import io

pd.show_versions()
# pandas: 0.16.0

df = pd.read_csv(io.StringIO(u"""SynsetTerms,PosScore,NegScore
a prueba de,0.208333333333,0.0833333333333
a reacción,0,0.0625
a salvo,0.1875,0.0625
a través de,0.1875,0.0
a ultranza,0.125,0.0
"""))
df
#    SynsetTerms  PosScore  NegScore
# 0  a prueba de  0.208333  0.083333
# 1   a reacción  0.000000  0.062500
# 2      a salvo  0.187500  0.062500
# 3  a través de  0.187500  0.000000
# 4   a ultranza  0.125000  0.000000

df.columns
# Index([u'SynsetTerms', u'PosScore', u'NegScore'], dtype='object')

pos_score = [df[df.NegScore > 0].SynsetTerms.unique()]
pos_score
# [array(['a prueba de', 'a reacci\xc3\xb3n', 'a salvo'], dtype=object)]
```
