### ISSUE TITLE
Broken URL to Google Finance in tests

### ISSUE THREAD

**Issue by chrish42** [pydata/pandas#9900]
I'm running all the tests for pandas, and I get the following failure:

```
ERROR: test_read_google (pandas.io.tests.test_data.TestDataReader)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/chrish/Code/pandas/pandas/util/testing.py", line 1461, in wrapper
    return t(*args, **kwargs)
  File "/Users/chrish/Code/pandas/pandas/io/tests/test_data.py", line 470, in test_read_google
    gs = DataReader("GS", "google")
  File "/Users/chrish/Code/pandas/pandas/io/data.py", line 81, in DataReader
    retry_count=retry_count, pause=pause)
  File "/Users/chrish/Code/pandas/pandas/io/data.py", line 458, in get_data_google
    adjust_price, ret_index, chunksize, 'google')
  File "/Users/chrish/Code/pandas/pandas/io/data.py", line 365, in _get_data_from
    hist_data = src_fn(symbols, start, end, interval, retry_count, pause)
  File "/Users/chrish/Code/pandas/pandas/io/data.py", line 229, in _get_hist_google
    return _retry_read_url(url, retry_count, pause, 'Google')
  File "/Users/chrish/Code/pandas/pandas/io/data.py", line 185, in _retry_read_url
    "return a 200 for url %r" % (retry_count, name, url))
IOError: after 3 tries, Google did not return a 200 for url 'http://www.google.com/finance/historical?q=GS&startdate=Jan+01%2C+2010&enddate=Apr+14%2C+2015&output=csv'
```

Going to the URL in a browser returns a 404 page, with message "The requested URL was not found on this server.", so I don't think this test will be passing as is in the future...

**Comment by chrish42** [comment]
The new URL format for downloading Google Finance data to csv looks like this:

    http://www.google.com/finance/historical?cid=663137&startdate=Apr+15%2C+2014&enddate=Apr+14%2C+2015&num=30&ei=LD8tVbGfGszLigKAx4HADQ&output=csv

The `ei` parameter is actually not required (the URL still works without it), but the cid one is. I assume that `cid` one relates to the ticker name.

**Comment by jreback** [comment]
you an report this to https://github.com/pydata/pandas-datareader/issues
as all io/data.py issues are now tracked (and fixed there)
