### ISSUE TITLE
nosetest failed for pandas 0.16.0

### ISSUE THREAD

**Issue by leo4183** [pydata/pandas#9992]
Hi there,

I recently upgraded pandas from 0.15.1 to 0.16.0.  after running the nosetest i got the following error msgs.  wondering if anything series (i tested HDF5 writing/reading.  everything looks normal).

======================================================================
ERROR: test_conv_read_write (pandas.io.tests.test_pytables.TestHDFStore)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/pandas/io/tests/test_pytables.py", line 205, in test_conv_read_write
    assert_series_equal(o, roundtrip('series',o))
  File "/usr/local/lib/python3.4/site-packages/pandas/io/tests/test_pytables.py", line 201, in roundtrip
    obj.to_hdf(self.path, key,**kwargs)
  File "/usr/local/lib/python3.4/site-packages/pandas/core/generic.py", line 913, in to_hdf
    return pytables.to_hdf(path_or_buf, key, self, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/pandas/io/pytables.py", line 266, in to_hdf
    complib=complib) as store:
  File "/usr/local/lib/python3.4/site-packages/pandas/io/pytables.py", line 396, in __init__
    self.open(mode=mode, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/pandas/io/pytables.py", line 536, in open
    self._handle = tables.open_file(self._path, 'r', **kwargs)
  File "/usr/local/lib/python3.4/site-packages/tables/file.py", line 318, in open_file
    return File(filename, mode, title, root_uep, filters, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/tables/file.py", line 791, in __init__
    self._g_new(filename, mode, **params)
  File "hdf5extension.pyx", line 359, in tables.hdf5extension.File._g_new (tables/hdf5extension.c:3756)
  File "/usr/local/lib/python3.4/site-packages/tables/utils.py", line 157, in check_file_access
    raise IOError("``%s`` does not exist" % (filename,))
nose.proxy.OSError: ``tmp.__5JMnSD5gVu__.h5`` does not exist
-------------------- >> begin captured stdout << ---------------------
Opening tmp.__5JMnSD5gVu__.h5 in read-only mode

--------------------- >> end captured stdout << ----------------------

======================================================================
ERROR: test_copy (pandas.io.tests.test_pytables.TestHDFStore)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/pandas/io/tests/test_pytables.py", line 4331, in test_copy
    st = HDFStore(self.path)
  File "/usr/local/lib/python3.4/site-packages/pandas/io/pytables.py", line 396, in __init__
    self.open(mode=mode, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/pandas/io/pytables.py", line 536, in open
    self._handle = tables.open_file(self._path, 'r', **kwargs)
  File "/usr/local/lib/python3.4/site-packages/tables/file.py", line 318, in open_file
    return File(filename, mode, title, root_uep, filters, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/tables/file.py", line 791, in __init__
    self._g_new(filename, mode, **params)
  File "hdf5extension.pyx", line 359, in tables.hdf5extension.File._g_new (tables/hdf5extension.c:3756)
  File "/usr/local/lib/python3.4/site-packages/tables/utils.py", line 157, in check_file_access
    raise IOError("``%s`` does not exist" % (filename,))
nose.proxy.OSError: ``tmp.__NZTYQk5IW2__.h5`` does not exist
-------------------- >> begin captured stdout << ---------------------
Opening tmp.__NZTYQk5IW2__.h5 in read-only mode

--------------------- >> end captured stdout << ----------------------

======================================================================
ERROR: test_factory_fun (pandas.io.tests.test_pytables.TestHDFStore)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/pandas/io/tests/test_pytables.py", line 160, in test_factory_fun
    with get_store(self.path) as tbl:
  File "/usr/local/lib/python3.4/site-packages/pandas/io/pytables.py", line 1273, in get_store
    return HDFStore(path, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/pandas/io/pytables.py", line 396, in __init__
    self.open(mode=mode, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/pandas/io/pytables.py", line 536, in open
    self._handle = tables.open_file(self._path, 'r', **kwargs)
  File "/usr/local/lib/python3.4/site-packages/tables/file.py", line 318, in open_file
    return File(filename, mode, title, root_uep, filters, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/tables/file.py", line 791, in __init__
    self._g_new(filename, mode, **params)
  File "hdf5extension.pyx", line 359, in tables.hdf5extension.File._g_new (tables/hdf5extension.c:3756)
  File "/usr/local/lib/python3.4/site-packages/tables/utils.py", line 157, in check_file_access
    raise IOError("``%s`` does not exist" % (filename,))
nose.proxy.OSError: ``tmp.__lL9hBPXiYa__.h5`` does not exist
-------------------- >> begin captured stdout << ---------------------
Opening tmp.__lL9hBPXiYa__.h5 in read-only mode

--------------------- >> end captured stdout << ----------------------

my python/pandas environment (Redhat server v6.5):

certifi (14.05.14)
Cython (0.21.1)
ipython (2.3.1)
jieba3k (0.35.1)
Jinja2 (2.7.3)
lxml (3.4.0)
MarkupSafe (0.23)
matplotlib (1.4.2)
mysql-connector-python (2.0.2)
nltk (3.0.1)
nose (1.3.4)
numexpr (2.4)
numpy (1.8.2)
openpyxl (1.6.1)
oursql (0.9.4)
pandas (0.16.0)
patsy (0.3.0)
pip (1.5.6)
pyparsing (2.0.3)
pyreadline (2.0)
python-dateutil (2.2)
pytz (2014.9)
pyzmq (14.4.1)
scipy (0.14.0)
setuptools (2.1)
six (1.8.0)
SQLAlchemy (0.9.8)
statsmodels (0.6.0)
tables (3.1.1)
tornado (4.0.2)
xlrd (0.9.3)

**Comment by jreback** [comment]
looks like something intermittent with the temporary file. if you rerun just pandas/io/tests/test_pytables.py does this persist?

**Comment by leo4183** [comment]
yes, the issue remains:


test_api (__main__.TestHDFStore) ... ok
test_api_default_format (__main__.TestHDFStore) ... ok
test_append (__main__.TestHDFStore) ... ok
test_append_all_nans (__main__.TestHDFStore) ... ok
test_append_diff_item_order (__main__.TestHDFStore) ... ok
test_append_frame_column_oriented (__main__.TestHDFStore) ... ok
test_append_hierarchical (__main__.TestHDFStore) ... ok
test_append_misc (__main__.TestHDFStore) ... ok
test_append_raise (__main__.TestHDFStore) ... ok
test_append_series (__main__.TestHDFStore) ... ok
test_append_some_nans (__main__.TestHDFStore) ... ok
test_append_to_multiple (__main__.TestHDFStore) ... ok
test_append_to_multiple_dropna (__main__.TestHDFStore) ... ok
test_append_with_data_columns (__main__.TestHDFStore) ... ok
test_append_with_diff_col_name_types_raises_value_error (__main__.TestHDFStore) ... ok
test_append_with_different_block_ordering (__main__.TestHDFStore) ... ok
test_append_with_strings (__main__.TestHDFStore) ... ok
test_append_with_timedelta (__main__.TestHDFStore) ... ok
test_append_with_timezones_dateutil (__main__.TestHDFStore) ... ok
test_append_with_timezones_pytz (__main__.TestHDFStore) ... ok
test_backwards_compat_without_term_object (__main__.TestHDFStore) ... ok
test_calendar_roundtrip_issue (__main__.TestHDFStore) ... ok
test_can_serialize_dates (__main__.TestHDFStore) ... ok
test_categorical (__main__.TestHDFStore) ... ok
test_column_multiindex (__main__.TestHDFStore) ... ok
test_contains (__main__.TestHDFStore) ... ok
test_context (__main__.TestHDFStore) ... Opening tmp.__ZhpolDfsqD__.h5 in read-only mode
> /usr/local/lib/python3.4/site-packages/tables/utils.py(157)check_file_access()
-> raise IOError("``%s`` does not exist" % (filename,))
(Pdb) exit
ERROR

======================================================================
ERROR: test_context (__main__.TestHDFStore)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/pandas/io/pytables.py", line 532, in open
    self._handle = tables.open_file(self._path, self._mode, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/tables/file.py", line 318, in open_file
    return File(filename, mode, title, root_uep, filters, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/tables/file.py", line 791, in __init__
    self._g_new(filename, mode, **params)
  File "hdf5extension.pyx", line 359, in tables.hdf5extension.File._g_new (tables/hdf5extension.c:3756)
  File "/usr/local/lib/python3.4/site-packages/tables/utils.py", line 185, in check_file_access
    check_file_access(filename, 'w')
  File "/usr/local/lib/python3.4/site-packages/tables/utils.py", line 180, in check_file_access
    "written" % (parentname,))
OSError: directory ``.`` exists but it can not be written

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/pandas/io/tests/test_pytables.py", line 179, in test_context
    with HDFStore(self.path) as tbl:
  File "/usr/local/lib/python3.4/site-packages/pandas/io/pytables.py", line 396, in __init__
    self.open(mode=mode, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/pandas/io/pytables.py", line 536, in open
    self._handle = tables.open_file(self._path, 'r', **kwargs)
  File "/usr/local/lib/python3.4/site-packages/tables/file.py", line 318, in open_file
    return File(filename, mode, title, root_uep, filters, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/tables/file.py", line 791, in __init__
    self._g_new(filename, mode, **params)
  File "hdf5extension.pyx", line 359, in tables.hdf5extension.File._g_new (tables/hdf5extension.c:3756)
  File "/usr/local/lib/python3.4/site-packages/tables/utils.py", line 157, in check_file_access
    raise IOError("``%s`` does not exist" % (filename,))
OSError: ``tmp.__ZhpolDfsqD__.h5`` does not exist

----------------------------------------------------------------------

**Comment by jreback** [comment]
so this particular test writes in the current directly rather in a created temporary. It appears that you don't have write permission where its being run (not sure why its using the source dir though).

So I think there are 3 tests (test_context/test_factory_fun/test_conv_read_write) that directly use ``self.path`` rather than and ``ensure_clean*`` routines (as these are testing the actual creation / destruction). These should use a ``path = create_tempfile(self.path)``

want to do a pull-request?

**Comment by vikramls** [comment]
I submitted a PR for this ticket: https://github.com/pydata/pandas/pull/10080. If there are issues, please let me know how I can improve.

**Comment by jreback** [comment]
closed via #10080
